namespace ProtocolBus {	// Generated by protoc-gen-vala 0.1.0 from SampleData.proto, do not edit
	
	public class DataPck : Protobuf.Message
	{
	    public string a;
	    public GLib.ByteArray Data;
	
	    public DataPck ()
	    {
	        this.a = "hola";
	        this.Data = null;
	    }
	
	    public DataPck.from_data (Protobuf.DecodeBuffer buffer, ssize_t data_length = -1)
	    {
	        decode (buffer, data_length);
	    }
	
	    public override bool decode (Protobuf.DecodeBuffer buffer, ssize_t data_length = -1)
	    {
	        size_t end;
	        if (data_length < 0)
	            end = buffer.buffer.length;
	        else
	            end = buffer.read_index + data_length;
	        var have_a = false;
	        var have_Data = false;
	
	        this.a = "hola";
	        this.Data = null;
	        while (buffer.read_index < end)
	        {
	            var key = buffer.decode_varint ();
	            var wire_type = key & 0x7;
	            var field_number = key >> 3;
	
	            if (field_number == 1 && wire_type == 2)
	            {
	                this.a = buffer.decode_string ((size_t) buffer.decode_varint ());
	                have_a = true;
	            }
	            else if (field_number == 2 && wire_type == 2)
	            {
	                this.Data = buffer.decode_bytes ((size_t) buffer.decode_varint ());
	                have_Data = true;
	            }
	            else
	                this.unknown_fields.prepend (buffer.decode_unknown_field (key));
	        }
	
	        if (buffer.read_index != end)
	            buffer.error = true;
	        else if (!have_a || !have_Data)
	            buffer.error = true;
	
	        return !buffer.error;
	    }
	
	    public override size_t encode (Protobuf.EncodeBuffer buffer)
	    {
	        size_t n_written = 0;
	
	        foreach (var f in this.unknown_fields)
	            n_written += buffer.encode_unknown_field (f);
	        var Data_length = buffer.encode_bytes (this.Data);
	        n_written += Data_length;
	        n_written += buffer.encode_varint (Data_length);
	        n_written += buffer.encode_varint (18);
	        var a_length = buffer.encode_string (this.a);
	        n_written += a_length;
	        n_written += buffer.encode_varint (a_length);
	        n_written += buffer.encode_varint (10);
	
	        return n_written;
	    }
	
	    public override string to_string (string indent = "")
	    {
	        var text = "";
	
	        text += indent + "a: %s\n".printf (Protobuf.string_to_string (this.a));
	        text += indent + "Data: %s\n".printf (Protobuf.bytes_to_string (this.Data));
	
	        return text;
	    }
	}
	
}