/* protocolbus.h generated by valac 0.56.0, the Vala compiler, do not modify */

#ifndef ___HOME_CHUCO_MYPROGS_VALA_VK6BUS_LIB_PROTOCOLBUS_H__
#define ___HOME_CHUCO_MYPROGS_VALA_VK6BUS_LIB_PROTOCOLBUS_H__

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define PROTOBUF_TYPE_MESSAGE (protobuf_message_get_type ())
#define PROTOBUF_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOBUF_TYPE_MESSAGE, ProtobufMessage))
#define PROTOBUF_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOBUF_TYPE_MESSAGE, ProtobufMessageClass))
#define PROTOBUF_IS_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOBUF_TYPE_MESSAGE))
#define PROTOBUF_IS_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOBUF_TYPE_MESSAGE))
#define PROTOBUF_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOBUF_TYPE_MESSAGE, ProtobufMessageClass))

typedef struct _ProtobufMessage ProtobufMessage;
typedef struct _ProtobufMessageClass ProtobufMessageClass;
typedef struct _ProtobufMessagePrivate ProtobufMessagePrivate;

#define PROTOBUF_TYPE_ENCODE_BUFFER (protobuf_encode_buffer_get_type ())
#define PROTOBUF_ENCODE_BUFFER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOBUF_TYPE_ENCODE_BUFFER, ProtobufEncodeBuffer))
#define PROTOBUF_ENCODE_BUFFER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOBUF_TYPE_ENCODE_BUFFER, ProtobufEncodeBufferClass))
#define PROTOBUF_IS_ENCODE_BUFFER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOBUF_TYPE_ENCODE_BUFFER))
#define PROTOBUF_IS_ENCODE_BUFFER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOBUF_TYPE_ENCODE_BUFFER))
#define PROTOBUF_ENCODE_BUFFER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOBUF_TYPE_ENCODE_BUFFER, ProtobufEncodeBufferClass))

typedef struct _ProtobufEncodeBuffer ProtobufEncodeBuffer;
typedef struct _ProtobufEncodeBufferClass ProtobufEncodeBufferClass;

#define PROTOBUF_TYPE_DECODE_BUFFER (protobuf_decode_buffer_get_type ())
#define PROTOBUF_DECODE_BUFFER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOBUF_TYPE_DECODE_BUFFER, ProtobufDecodeBuffer))
#define PROTOBUF_DECODE_BUFFER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOBUF_TYPE_DECODE_BUFFER, ProtobufDecodeBufferClass))
#define PROTOBUF_IS_DECODE_BUFFER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOBUF_TYPE_DECODE_BUFFER))
#define PROTOBUF_IS_DECODE_BUFFER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOBUF_TYPE_DECODE_BUFFER))
#define PROTOBUF_DECODE_BUFFER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOBUF_TYPE_DECODE_BUFFER, ProtobufDecodeBufferClass))

typedef struct _ProtobufDecodeBuffer ProtobufDecodeBuffer;
typedef struct _ProtobufDecodeBufferClass ProtobufDecodeBufferClass;

#define PROTOBUF_TYPE_UNKNOWN_FIELD (protobuf_unknown_field_get_type ())
#define PROTOBUF_UNKNOWN_FIELD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOBUF_TYPE_UNKNOWN_FIELD, ProtobufUnknownField))
#define PROTOBUF_UNKNOWN_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOBUF_TYPE_UNKNOWN_FIELD, ProtobufUnknownFieldClass))
#define PROTOBUF_IS_UNKNOWN_FIELD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOBUF_TYPE_UNKNOWN_FIELD))
#define PROTOBUF_IS_UNKNOWN_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOBUF_TYPE_UNKNOWN_FIELD))
#define PROTOBUF_UNKNOWN_FIELD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOBUF_TYPE_UNKNOWN_FIELD, ProtobufUnknownFieldClass))

typedef struct _ProtobufUnknownField ProtobufUnknownField;
typedef struct _ProtobufUnknownFieldClass ProtobufUnknownFieldClass;

#define PROTOCOL_BUS_TYPE_APP_CONFIG (protocol_bus_app_config_get_type ())
#define PROTOCOL_BUS_APP_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_APP_CONFIG, ProtocolBusAppConfig))
#define PROTOCOL_BUS_APP_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_APP_CONFIG, ProtocolBusAppConfigClass))
#define PROTOCOL_BUS_IS_APP_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_APP_CONFIG))
#define PROTOCOL_BUS_IS_APP_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_APP_CONFIG))
#define PROTOCOL_BUS_APP_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_APP_CONFIG, ProtocolBusAppConfigClass))

typedef struct _ProtocolBusAppConfig ProtocolBusAppConfig;
typedef struct _ProtocolBusAppConfigClass ProtocolBusAppConfigClass;
typedef struct _ProtocolBusAppConfigPrivate ProtocolBusAppConfigPrivate;

#define PROTOCOL_BUS_TYPE_DOMAIN_CFG (protocol_bus_domain_cfg_get_type ())
#define PROTOCOL_BUS_DOMAIN_CFG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_DOMAIN_CFG, ProtocolBusDomainCfg))
#define PROTOCOL_BUS_DOMAIN_CFG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_DOMAIN_CFG, ProtocolBusDomainCfgClass))
#define PROTOCOL_BUS_IS_DOMAIN_CFG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_DOMAIN_CFG))
#define PROTOCOL_BUS_IS_DOMAIN_CFG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_DOMAIN_CFG))
#define PROTOCOL_BUS_DOMAIN_CFG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_DOMAIN_CFG, ProtocolBusDomainCfgClass))

typedef struct _ProtocolBusDomainCfg ProtocolBusDomainCfg;
typedef struct _ProtocolBusDomainCfgClass ProtocolBusDomainCfgClass;

#define PROTOCOL_BUS_TYPE_APP_CONFIG_TEXT (protocol_bus_app_config_text_get_type ())
#define PROTOCOL_BUS_APP_CONFIG_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_APP_CONFIG_TEXT, ProtocolBusAppConfigText))
#define PROTOCOL_BUS_APP_CONFIG_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_APP_CONFIG_TEXT, ProtocolBusAppConfigTextClass))
#define PROTOCOL_BUS_IS_APP_CONFIG_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_APP_CONFIG_TEXT))
#define PROTOCOL_BUS_IS_APP_CONFIG_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_APP_CONFIG_TEXT))
#define PROTOCOL_BUS_APP_CONFIG_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_APP_CONFIG_TEXT, ProtocolBusAppConfigTextClass))

typedef struct _ProtocolBusAppConfigText ProtocolBusAppConfigText;
typedef struct _ProtocolBusAppConfigTextClass ProtocolBusAppConfigTextClass;
typedef struct _ProtocolBusAppConfigTextPrivate ProtocolBusAppConfigTextPrivate;
typedef struct _ProtocolBusDomainCfgPrivate ProtocolBusDomainCfgPrivate;

#define PROTOCOL_BUS_TYPE_TRANSPORT_DEF (protocol_bus_transport_def_get_type ())
#define PROTOCOL_BUS_TRANSPORT_DEF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_TRANSPORT_DEF, ProtocolBusTransportDef))
#define PROTOCOL_BUS_TRANSPORT_DEF_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_TRANSPORT_DEF, ProtocolBusTransportDefClass))
#define PROTOCOL_BUS_IS_TRANSPORT_DEF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_TRANSPORT_DEF))
#define PROTOCOL_BUS_IS_TRANSPORT_DEF_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_TRANSPORT_DEF))
#define PROTOCOL_BUS_TRANSPORT_DEF_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_TRANSPORT_DEF, ProtocolBusTransportDefClass))

typedef struct _ProtocolBusTransportDef ProtocolBusTransportDef;
typedef struct _ProtocolBusTransportDefClass ProtocolBusTransportDefClass;

#define PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF (protocol_bus_cross_connector_def_get_type ())
#define PROTOCOL_BUS_CROSS_CONNECTOR_DEF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF, ProtocolBusCrossConnectorDef))
#define PROTOCOL_BUS_CROSS_CONNECTOR_DEF_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF, ProtocolBusCrossConnectorDefClass))
#define PROTOCOL_BUS_IS_CROSS_CONNECTOR_DEF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF))
#define PROTOCOL_BUS_IS_CROSS_CONNECTOR_DEF_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF))
#define PROTOCOL_BUS_CROSS_CONNECTOR_DEF_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF, ProtocolBusCrossConnectorDefClass))

typedef struct _ProtocolBusCrossConnectorDef ProtocolBusCrossConnectorDef;
typedef struct _ProtocolBusCrossConnectorDefClass ProtocolBusCrossConnectorDefClass;

#define PROTOCOL_BUS_TYPE_DOMAIN_CFG_TEXT (protocol_bus_domain_cfg_text_get_type ())
#define PROTOCOL_BUS_DOMAIN_CFG_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_DOMAIN_CFG_TEXT, ProtocolBusDomainCfgText))
#define PROTOCOL_BUS_DOMAIN_CFG_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_DOMAIN_CFG_TEXT, ProtocolBusDomainCfgTextClass))
#define PROTOCOL_BUS_IS_DOMAIN_CFG_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_DOMAIN_CFG_TEXT))
#define PROTOCOL_BUS_IS_DOMAIN_CFG_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_DOMAIN_CFG_TEXT))
#define PROTOCOL_BUS_DOMAIN_CFG_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_DOMAIN_CFG_TEXT, ProtocolBusDomainCfgTextClass))

typedef struct _ProtocolBusDomainCfgText ProtocolBusDomainCfgText;
typedef struct _ProtocolBusDomainCfgTextClass ProtocolBusDomainCfgTextClass;
typedef struct _ProtocolBusDomainCfgTextPrivate ProtocolBusDomainCfgTextPrivate;
typedef struct _ProtocolBusTransportDefPrivate ProtocolBusTransportDefPrivate;

#define PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG (protocol_bus_mcast_def_config_get_type ())
#define PROTOCOL_BUS_MCAST_DEF_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG, ProtocolBusMCastDefConfig))
#define PROTOCOL_BUS_MCAST_DEF_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG, ProtocolBusMCastDefConfigClass))
#define PROTOCOL_BUS_IS_MCAST_DEF_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG))
#define PROTOCOL_BUS_IS_MCAST_DEF_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG))
#define PROTOCOL_BUS_MCAST_DEF_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG, ProtocolBusMCastDefConfigClass))

typedef struct _ProtocolBusMCastDefConfig ProtocolBusMCastDefConfig;
typedef struct _ProtocolBusMCastDefConfigClass ProtocolBusMCastDefConfigClass;

#define PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG (protocol_bus_bcast_def_config_get_type ())
#define PROTOCOL_BUS_BCAST_DEF_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG, ProtocolBusBCastDefConfig))
#define PROTOCOL_BUS_BCAST_DEF_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG, ProtocolBusBCastDefConfigClass))
#define PROTOCOL_BUS_IS_BCAST_DEF_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG))
#define PROTOCOL_BUS_IS_BCAST_DEF_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG))
#define PROTOCOL_BUS_BCAST_DEF_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG, ProtocolBusBCastDefConfigClass))

typedef struct _ProtocolBusBCastDefConfig ProtocolBusBCastDefConfig;
typedef struct _ProtocolBusBCastDefConfigClass ProtocolBusBCastDefConfigClass;

#define PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG (protocol_bus_udp_star_def_config_get_type ())
#define PROTOCOL_BUS_UDP_STAR_DEF_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG, ProtocolBusUDPStarDefConfig))
#define PROTOCOL_BUS_UDP_STAR_DEF_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG, ProtocolBusUDPStarDefConfigClass))
#define PROTOCOL_BUS_IS_UDP_STAR_DEF_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG))
#define PROTOCOL_BUS_IS_UDP_STAR_DEF_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG))
#define PROTOCOL_BUS_UDP_STAR_DEF_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG, ProtocolBusUDPStarDefConfigClass))

typedef struct _ProtocolBusUDPStarDefConfig ProtocolBusUDPStarDefConfig;
typedef struct _ProtocolBusUDPStarDefConfigClass ProtocolBusUDPStarDefConfigClass;

#define PROTOCOL_BUS_TYPE_TRANSPORT_DEF_TEXT (protocol_bus_transport_def_text_get_type ())
#define PROTOCOL_BUS_TRANSPORT_DEF_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_TRANSPORT_DEF_TEXT, ProtocolBusTransportDefText))
#define PROTOCOL_BUS_TRANSPORT_DEF_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_TRANSPORT_DEF_TEXT, ProtocolBusTransportDefTextClass))
#define PROTOCOL_BUS_IS_TRANSPORT_DEF_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_TRANSPORT_DEF_TEXT))
#define PROTOCOL_BUS_IS_TRANSPORT_DEF_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_TRANSPORT_DEF_TEXT))
#define PROTOCOL_BUS_TRANSPORT_DEF_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_TRANSPORT_DEF_TEXT, ProtocolBusTransportDefTextClass))

typedef struct _ProtocolBusTransportDefText ProtocolBusTransportDefText;
typedef struct _ProtocolBusTransportDefTextClass ProtocolBusTransportDefTextClass;
typedef struct _ProtocolBusTransportDefTextPrivate ProtocolBusTransportDefTextPrivate;
typedef struct _ProtocolBusMCastDefConfigPrivate ProtocolBusMCastDefConfigPrivate;

#define PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG_TEXT (protocol_bus_mcast_def_config_text_get_type ())
#define PROTOCOL_BUS_MCAST_DEF_CONFIG_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG_TEXT, ProtocolBusMCastDefConfigText))
#define PROTOCOL_BUS_MCAST_DEF_CONFIG_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG_TEXT, ProtocolBusMCastDefConfigTextClass))
#define PROTOCOL_BUS_IS_MCAST_DEF_CONFIG_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG_TEXT))
#define PROTOCOL_BUS_IS_MCAST_DEF_CONFIG_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG_TEXT))
#define PROTOCOL_BUS_MCAST_DEF_CONFIG_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_MCAST_DEF_CONFIG_TEXT, ProtocolBusMCastDefConfigTextClass))

typedef struct _ProtocolBusMCastDefConfigText ProtocolBusMCastDefConfigText;
typedef struct _ProtocolBusMCastDefConfigTextClass ProtocolBusMCastDefConfigTextClass;
typedef struct _ProtocolBusMCastDefConfigTextPrivate ProtocolBusMCastDefConfigTextPrivate;
typedef struct _ProtocolBusBCastDefConfigPrivate ProtocolBusBCastDefConfigPrivate;

#define PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG_TEXT (protocol_bus_bcast_def_config_text_get_type ())
#define PROTOCOL_BUS_BCAST_DEF_CONFIG_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG_TEXT, ProtocolBusBCastDefConfigText))
#define PROTOCOL_BUS_BCAST_DEF_CONFIG_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG_TEXT, ProtocolBusBCastDefConfigTextClass))
#define PROTOCOL_BUS_IS_BCAST_DEF_CONFIG_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG_TEXT))
#define PROTOCOL_BUS_IS_BCAST_DEF_CONFIG_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG_TEXT))
#define PROTOCOL_BUS_BCAST_DEF_CONFIG_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_BCAST_DEF_CONFIG_TEXT, ProtocolBusBCastDefConfigTextClass))

typedef struct _ProtocolBusBCastDefConfigText ProtocolBusBCastDefConfigText;
typedef struct _ProtocolBusBCastDefConfigTextClass ProtocolBusBCastDefConfigTextClass;
typedef struct _ProtocolBusBCastDefConfigTextPrivate ProtocolBusBCastDefConfigTextPrivate;
typedef struct _ProtocolBusUDPStarDefConfigPrivate ProtocolBusUDPStarDefConfigPrivate;

#define PROTOCOL_BUS_TYPE_END_POINT_DEF (protocol_bus_end_point_def_get_type ())
#define PROTOCOL_BUS_END_POINT_DEF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_END_POINT_DEF, ProtocolBusEndPointDef))
#define PROTOCOL_BUS_END_POINT_DEF_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_END_POINT_DEF, ProtocolBusEndPointDefClass))
#define PROTOCOL_BUS_IS_END_POINT_DEF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_END_POINT_DEF))
#define PROTOCOL_BUS_IS_END_POINT_DEF_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_END_POINT_DEF))
#define PROTOCOL_BUS_END_POINT_DEF_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_END_POINT_DEF, ProtocolBusEndPointDefClass))

typedef struct _ProtocolBusEndPointDef ProtocolBusEndPointDef;
typedef struct _ProtocolBusEndPointDefClass ProtocolBusEndPointDefClass;

#define PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG_TEXT (protocol_bus_udp_star_def_config_text_get_type ())
#define PROTOCOL_BUS_UDP_STAR_DEF_CONFIG_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG_TEXT, ProtocolBusUDPStarDefConfigText))
#define PROTOCOL_BUS_UDP_STAR_DEF_CONFIG_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG_TEXT, ProtocolBusUDPStarDefConfigTextClass))
#define PROTOCOL_BUS_IS_UDP_STAR_DEF_CONFIG_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG_TEXT))
#define PROTOCOL_BUS_IS_UDP_STAR_DEF_CONFIG_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG_TEXT))
#define PROTOCOL_BUS_UDP_STAR_DEF_CONFIG_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_UDP_STAR_DEF_CONFIG_TEXT, ProtocolBusUDPStarDefConfigTextClass))

typedef struct _ProtocolBusUDPStarDefConfigText ProtocolBusUDPStarDefConfigText;
typedef struct _ProtocolBusUDPStarDefConfigTextClass ProtocolBusUDPStarDefConfigTextClass;
typedef struct _ProtocolBusUDPStarDefConfigTextPrivate ProtocolBusUDPStarDefConfigTextPrivate;
typedef struct _ProtocolBusEndPointDefPrivate ProtocolBusEndPointDefPrivate;

#define PROTOCOL_BUS_TYPE_END_POINT_DEF_TEXT (protocol_bus_end_point_def_text_get_type ())
#define PROTOCOL_BUS_END_POINT_DEF_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_END_POINT_DEF_TEXT, ProtocolBusEndPointDefText))
#define PROTOCOL_BUS_END_POINT_DEF_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_END_POINT_DEF_TEXT, ProtocolBusEndPointDefTextClass))
#define PROTOCOL_BUS_IS_END_POINT_DEF_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_END_POINT_DEF_TEXT))
#define PROTOCOL_BUS_IS_END_POINT_DEF_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_END_POINT_DEF_TEXT))
#define PROTOCOL_BUS_END_POINT_DEF_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_END_POINT_DEF_TEXT, ProtocolBusEndPointDefTextClass))

typedef struct _ProtocolBusEndPointDefText ProtocolBusEndPointDefText;
typedef struct _ProtocolBusEndPointDefTextClass ProtocolBusEndPointDefTextClass;
typedef struct _ProtocolBusEndPointDefTextPrivate ProtocolBusEndPointDefTextPrivate;
typedef struct _ProtocolBusCrossConnectorDefPrivate ProtocolBusCrossConnectorDefPrivate;

#define PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF_TEXT (protocol_bus_cross_connector_def_text_get_type ())
#define PROTOCOL_BUS_CROSS_CONNECTOR_DEF_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF_TEXT, ProtocolBusCrossConnectorDefText))
#define PROTOCOL_BUS_CROSS_CONNECTOR_DEF_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF_TEXT, ProtocolBusCrossConnectorDefTextClass))
#define PROTOCOL_BUS_IS_CROSS_CONNECTOR_DEF_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF_TEXT))
#define PROTOCOL_BUS_IS_CROSS_CONNECTOR_DEF_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF_TEXT))
#define PROTOCOL_BUS_CROSS_CONNECTOR_DEF_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_CROSS_CONNECTOR_DEF_TEXT, ProtocolBusCrossConnectorDefTextClass))

typedef struct _ProtocolBusCrossConnectorDefText ProtocolBusCrossConnectorDefText;
typedef struct _ProtocolBusCrossConnectorDefTextClass ProtocolBusCrossConnectorDefTextClass;
typedef struct _ProtocolBusCrossConnectorDefTextPrivate ProtocolBusCrossConnectorDefTextPrivate;

#define PROTOCOL_BUS_TYPE_WAIT_HANDLE (protocol_bus_wait_handle_get_type ())
#define PROTOCOL_BUS_WAIT_HANDLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_WAIT_HANDLE, ProtocolBusWaitHandle))
#define PROTOCOL_BUS_WAIT_HANDLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_WAIT_HANDLE, ProtocolBusWaitHandleClass))
#define PROTOCOL_BUS_IS_WAIT_HANDLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_WAIT_HANDLE))
#define PROTOCOL_BUS_IS_WAIT_HANDLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_WAIT_HANDLE))
#define PROTOCOL_BUS_WAIT_HANDLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_WAIT_HANDLE, ProtocolBusWaitHandleClass))

typedef struct _ProtocolBusWaitHandle ProtocolBusWaitHandle;
typedef struct _ProtocolBusWaitHandleClass ProtocolBusWaitHandleClass;
typedef struct _ProtocolBusWaitHandlePrivate ProtocolBusWaitHandlePrivate;

#define PROTOCOL_BUS_TYPE_ILOGGER (protocol_bus_ilogger_get_type ())
#define PROTOCOL_BUS_ILOGGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_ILOGGER, ProtocolBusILogger))
#define PROTOCOL_BUS_ILOGGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_ILOGGER, ProtocolBusILoggerClass))
#define PROTOCOL_BUS_IS_ILOGGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_ILOGGER))
#define PROTOCOL_BUS_IS_ILOGGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_ILOGGER))
#define PROTOCOL_BUS_ILOGGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_ILOGGER, ProtocolBusILoggerClass))

typedef struct _ProtocolBusILogger ProtocolBusILogger;
typedef struct _ProtocolBusILoggerClass ProtocolBusILoggerClass;

#define PROTOCOL_BUS_TYPE_APP_SYNC (protocol_bus_app_sync_get_type ())
#define PROTOCOL_BUS_APP_SYNC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_APP_SYNC, ProtocolBusAppSync))
#define PROTOCOL_BUS_APP_SYNC_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_APP_SYNC, ProtocolBusAppSyncClass))
#define PROTOCOL_BUS_IS_APP_SYNC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_APP_SYNC))
#define PROTOCOL_BUS_IS_APP_SYNC_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_APP_SYNC))
#define PROTOCOL_BUS_APP_SYNC_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_APP_SYNC, ProtocolBusAppSyncClass))

typedef struct _ProtocolBusAppSync ProtocolBusAppSync;
typedef struct _ProtocolBusAppSyncClass ProtocolBusAppSyncClass;

#define PROTOCOL_BUS_TYPE_MANUAL_RESET_EVENT (protocol_bus_manual_reset_event_get_type ())
#define PROTOCOL_BUS_MANUAL_RESET_EVENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_MANUAL_RESET_EVENT, ProtocolBusManualResetEvent))
#define PROTOCOL_BUS_MANUAL_RESET_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_MANUAL_RESET_EVENT, ProtocolBusManualResetEventClass))
#define PROTOCOL_BUS_IS_MANUAL_RESET_EVENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_MANUAL_RESET_EVENT))
#define PROTOCOL_BUS_IS_MANUAL_RESET_EVENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_MANUAL_RESET_EVENT))
#define PROTOCOL_BUS_MANUAL_RESET_EVENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_MANUAL_RESET_EVENT, ProtocolBusManualResetEventClass))

typedef struct _ProtocolBusManualResetEvent ProtocolBusManualResetEvent;
typedef struct _ProtocolBusManualResetEventClass ProtocolBusManualResetEventClass;
typedef struct _ProtocolBusManualResetEventPrivate ProtocolBusManualResetEventPrivate;
typedef struct _ProtocolBusILoggerPrivate ProtocolBusILoggerPrivate;
typedef struct _ProtocolBusAppSyncPrivate ProtocolBusAppSyncPrivate;

#define PROTOCOL_BUS_TYPE_CIPHERING (protocol_bus_ciphering_get_type ())
#define PROTOCOL_BUS_CIPHERING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_CIPHERING, ProtocolBusCiphering))
#define PROTOCOL_BUS_CIPHERING_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_CIPHERING, ProtocolBusCipheringClass))
#define PROTOCOL_BUS_IS_CIPHERING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_CIPHERING))
#define PROTOCOL_BUS_IS_CIPHERING_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_CIPHERING))
#define PROTOCOL_BUS_CIPHERING_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_CIPHERING, ProtocolBusCipheringClass))

typedef struct _ProtocolBusCiphering ProtocolBusCiphering;
typedef struct _ProtocolBusCipheringClass ProtocolBusCipheringClass;
typedef struct _ProtocolBusCipheringPrivate ProtocolBusCipheringPrivate;

#define PROTOCOL_BUS_TYPE_DICTIONARY_ENTRY (protocol_bus_dictionary_entry_get_type ())
#define PROTOCOL_BUS_DICTIONARY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_DICTIONARY_ENTRY, ProtocolBusDictionaryEntry))
#define PROTOCOL_BUS_DICTIONARY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_DICTIONARY_ENTRY, ProtocolBusDictionaryEntryClass))
#define PROTOCOL_BUS_IS_DICTIONARY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_DICTIONARY_ENTRY))
#define PROTOCOL_BUS_IS_DICTIONARY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_DICTIONARY_ENTRY))
#define PROTOCOL_BUS_DICTIONARY_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_DICTIONARY_ENTRY, ProtocolBusDictionaryEntryClass))

typedef struct _ProtocolBusDictionaryEntry ProtocolBusDictionaryEntry;
typedef struct _ProtocolBusDictionaryEntryClass ProtocolBusDictionaryEntryClass;
typedef struct _ProtocolBusDictionaryEntryPrivate ProtocolBusDictionaryEntryPrivate;

#define PROTOCOL_BUS_TYPE_QUEUE_MGR (protocol_bus_queue_mgr_get_type ())
#define PROTOCOL_BUS_QUEUE_MGR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_QUEUE_MGR, ProtocolBusQueueMgr))
#define PROTOCOL_BUS_QUEUE_MGR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_QUEUE_MGR, ProtocolBusQueueMgrClass))
#define PROTOCOL_BUS_IS_QUEUE_MGR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_QUEUE_MGR))
#define PROTOCOL_BUS_IS_QUEUE_MGR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_QUEUE_MGR))
#define PROTOCOL_BUS_QUEUE_MGR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_QUEUE_MGR, ProtocolBusQueueMgrClass))

typedef struct _ProtocolBusQueueMgr ProtocolBusQueueMgr;
typedef struct _ProtocolBusQueueMgrClass ProtocolBusQueueMgrClass;

#define PROTOCOL_BUS_TYPE_DOMAIN (protocol_bus_domain_get_type ())
#define PROTOCOL_BUS_DOMAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_DOMAIN, ProtocolBusDomain))
#define PROTOCOL_BUS_IS_DOMAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_DOMAIN))

typedef struct _ProtocolBusDomain ProtocolBusDomain;

#define PROTOCOL_BUS_TYPE_TRANSPORT (protocol_bus_transport_get_type ())
#define PROTOCOL_BUS_TRANSPORT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_TRANSPORT, ProtocolBusTransport))
#define PROTOCOL_BUS_TRANSPORT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_TRANSPORT, ProtocolBusTransportClass))
#define PROTOCOL_BUS_IS_TRANSPORT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_TRANSPORT))
#define PROTOCOL_BUS_IS_TRANSPORT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_TRANSPORT))
#define PROTOCOL_BUS_TRANSPORT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_TRANSPORT, ProtocolBusTransportClass))

typedef struct _ProtocolBusTransport ProtocolBusTransport;
typedef struct _ProtocolBusTransportClass ProtocolBusTransportClass;

#define PROTOCOL_BUS_TYPE_MSG (protocol_bus_msg_get_type ())
#define PROTOCOL_BUS_MSG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_MSG, ProtocolBusMsg))
#define PROTOCOL_BUS_MSG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_MSG, ProtocolBusMsgClass))
#define PROTOCOL_BUS_IS_MSG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_MSG))
#define PROTOCOL_BUS_IS_MSG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_MSG))
#define PROTOCOL_BUS_MSG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_MSG, ProtocolBusMsgClass))

typedef struct _ProtocolBusMsg ProtocolBusMsg;
typedef struct _ProtocolBusMsgClass ProtocolBusMsgClass;
typedef struct _ProtocolBusQueueMgrPrivate ProtocolBusQueueMgrPrivate;

#define PROTOCOL_BUS_TYPE_GSUB (protocol_bus_gsub_get_type ())
#define PROTOCOL_BUS_GSUB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_GSUB, ProtocolBusGSub))
#define PROTOCOL_BUS_GSUB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_GSUB, ProtocolBusGSubClass))
#define PROTOCOL_BUS_IS_GSUB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_GSUB))
#define PROTOCOL_BUS_IS_GSUB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_GSUB))
#define PROTOCOL_BUS_GSUB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_GSUB, ProtocolBusGSubClass))

typedef struct _ProtocolBusGSub ProtocolBusGSub;
typedef struct _ProtocolBusGSubClass ProtocolBusGSubClass;
typedef struct _ProtocolBusGSubPrivate ProtocolBusGSubPrivate;

#define PROTOCOL_BUS_TYPE_GPUB (protocol_bus_gpub_get_type ())
#define PROTOCOL_BUS_GPUB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_GPUB, ProtocolBusGPub))
#define PROTOCOL_BUS_GPUB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_GPUB, ProtocolBusGPubClass))
#define PROTOCOL_BUS_IS_GPUB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_GPUB))
#define PROTOCOL_BUS_IS_GPUB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_GPUB))
#define PROTOCOL_BUS_GPUB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_GPUB, ProtocolBusGPubClass))

typedef struct _ProtocolBusGPub ProtocolBusGPub;
typedef struct _ProtocolBusGPubClass ProtocolBusGPubClass;
typedef struct _ProtocolBusGPubPrivate ProtocolBusGPubPrivate;
typedef enum  {
	PROTOCOL_BUS_TRACE_LEVEL_ERROR = 0,
	PROTOCOL_BUS_TRACE_LEVEL_WARNING,
	PROTOCOL_BUS_TRACE_LEVEL_INFO,
	PROTOCOL_BUS_TRACE_LEVEL_TRACE
} ProtocolBusTraceLevel;

#define PROTOCOL_BUS_TYPE_TRACE_LEVEL (protocol_bus_trace_level_get_type ())

#define PROTOCOL_BUS_TYPE_PAIR (protocol_bus_pair_get_type ())
#define PROTOCOL_BUS_PAIR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_PAIR, ProtocolBusPair))
#define PROTOCOL_BUS_PAIR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_PAIR, ProtocolBusPairClass))
#define PROTOCOL_BUS_IS_PAIR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_PAIR))
#define PROTOCOL_BUS_IS_PAIR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_PAIR))
#define PROTOCOL_BUS_PAIR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_PAIR, ProtocolBusPairClass))

typedef struct _ProtocolBusPair ProtocolBusPair;
typedef struct _ProtocolBusPairClass ProtocolBusPairClass;
typedef struct _ProtocolBusPairPrivate ProtocolBusPairPrivate;

#define PROTOCOL_BUS_TYPE_LOGGER (protocol_bus_logger_get_type ())
#define PROTOCOL_BUS_LOGGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_LOGGER, ProtocolBusLogger))
#define PROTOCOL_BUS_IS_LOGGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_LOGGER))

typedef struct _ProtocolBusLogger ProtocolBusLogger;
typedef enum  {
	PROTOCOL_BUS_BATCH_MODE_INMEDIATE,
	PROTOCOL_BUS_BATCH_MODE_BATCH
} ProtocolBusBatchMode;

#define PROTOCOL_BUS_TYPE_BATCH_MODE (protocol_bus_batch_mode_get_type ())
typedef enum  {
	PROTOCOL_BUS_STREAM_MODE_UP,
	PROTOCOL_BUS_STREAM_MODE_DOWN
} ProtocolBusStreamMode;

#define PROTOCOL_BUS_TYPE_STREAM_MODE (protocol_bus_stream_mode_get_type ())
typedef struct _ProtocolBusTransportPrivate ProtocolBusTransportPrivate;

#define PROTOCOL_BUS_TYPE_PACKET (protocol_bus_packet_get_type ())
#define PROTOCOL_BUS_PACKET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_PACKET, ProtocolBusPacket))
#define PROTOCOL_BUS_PACKET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_PACKET, ProtocolBusPacketClass))
#define PROTOCOL_BUS_IS_PACKET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_PACKET))
#define PROTOCOL_BUS_IS_PACKET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_PACKET))
#define PROTOCOL_BUS_PACKET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_PACKET, ProtocolBusPacketClass))

typedef struct _ProtocolBusPacket ProtocolBusPacket;
typedef struct _ProtocolBusPacketClass ProtocolBusPacketClass;
typedef struct _ProtobufUnknownFieldPrivate ProtobufUnknownFieldPrivate;
typedef struct _ProtobufDecodeBufferPrivate ProtobufDecodeBufferPrivate;
typedef struct _ProtobufEncodeBufferPrivate ProtobufEncodeBufferPrivate;
typedef struct _ProtocolBusMsgPrivate ProtocolBusMsgPrivate;
typedef struct _ProtocolBusPacketPrivate ProtocolBusPacketPrivate;

#define PROTOCOL_BUS_TYPE_KEY_REGISTRY (protocol_bus_key_registry_get_type ())
#define PROTOCOL_BUS_KEY_REGISTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_KEY_REGISTRY, ProtocolBusKeyRegistry))
#define PROTOCOL_BUS_KEY_REGISTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_KEY_REGISTRY, ProtocolBusKeyRegistryClass))
#define PROTOCOL_BUS_IS_KEY_REGISTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_KEY_REGISTRY))
#define PROTOCOL_BUS_IS_KEY_REGISTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_KEY_REGISTRY))
#define PROTOCOL_BUS_KEY_REGISTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_KEY_REGISTRY, ProtocolBusKeyRegistryClass))

typedef struct _ProtocolBusKeyRegistry ProtocolBusKeyRegistry;
typedef struct _ProtocolBusKeyRegistryClass ProtocolBusKeyRegistryClass;
typedef struct _ProtocolBusKeyRegistryPrivate ProtocolBusKeyRegistryPrivate;

struct _ProtobufMessage {
	GObject parent_instance;
	ProtobufMessagePrivate * priv;
	GList* unknown_fields;
};

struct _ProtobufMessageClass {
	GObjectClass parent_class;
	gsize (*encode) (ProtobufMessage* self, ProtobufEncodeBuffer* buffer);
	gboolean (*decode) (ProtobufMessage* self, ProtobufDecodeBuffer* buffer, gssize data_length);
	gchar* (*to_string) (ProtobufMessage* self, const gchar* indent);
};

struct _ProtocolBusAppConfig {
	ProtobufMessage parent_instance;
	ProtocolBusAppConfigPrivate * priv;
	gboolean ActivateTrace;
	gint32 TraceLevel;
	GList* Domain;
};

struct _ProtocolBusAppConfigClass {
	ProtobufMessageClass parent_class;
};

struct _ProtocolBusAppConfigText {
	ProtocolBusAppConfig parent_instance;
	ProtocolBusAppConfigTextPrivate * priv;
};

struct _ProtocolBusAppConfigTextClass {
	ProtocolBusAppConfigClass parent_class;
};

struct _ProtocolBusDomainCfg {
	ProtobufMessage parent_instance;
	ProtocolBusDomainCfgPrivate * priv;
	gint32 Id;
	gboolean ActivateDefaultTransport;
	gboolean DirectDispacthToSubs;
	gchar* KeyFile;
	GList* Transport;
	ProtocolBusCrossConnectorDef* CrossConnector;
};

struct _ProtocolBusDomainCfgClass {
	ProtobufMessageClass parent_class;
};

struct _ProtocolBusDomainCfgText {
	ProtocolBusDomainCfg parent_instance;
	ProtocolBusDomainCfgTextPrivate * priv;
};

struct _ProtocolBusDomainCfgTextClass {
	ProtocolBusDomainCfgClass parent_class;
};

struct _ProtocolBusTransportDef {
	ProtobufMessage parent_instance;
	ProtocolBusTransportDefPrivate * priv;
	gchar* TransportName;
	gchar* DllImport;
	gchar* TransportClass;
	gboolean ReceiveOwnMsgs;
	ProtocolBusMCastDefConfig* MCastParams;
	ProtocolBusBCastDefConfig* BCastParams;
	ProtocolBusUDPStarDefConfig* UDPStarParams;
};

struct _ProtocolBusTransportDefClass {
	ProtobufMessageClass parent_class;
};

struct _ProtocolBusTransportDefText {
	ProtocolBusTransportDef parent_instance;
	ProtocolBusTransportDefTextPrivate * priv;
};

struct _ProtocolBusTransportDefTextClass {
	ProtocolBusTransportDefClass parent_class;
};

struct _ProtocolBusMCastDefConfig {
	ProtobufMessage parent_instance;
	ProtocolBusMCastDefConfigPrivate * priv;
	gchar* LocalAddress;
	gchar* MCastAddress;
	gint32 Port;
	gint32 TTL;
	gint32 ReceiveBuffer;
	gint32 SendBuffer;
};

struct _ProtocolBusMCastDefConfigClass {
	ProtobufMessageClass parent_class;
};

struct _ProtocolBusMCastDefConfigText {
	ProtocolBusMCastDefConfig parent_instance;
	ProtocolBusMCastDefConfigTextPrivate * priv;
};

struct _ProtocolBusMCastDefConfigTextClass {
	ProtocolBusMCastDefConfigClass parent_class;
};

struct _ProtocolBusBCastDefConfig {
	ProtobufMessage parent_instance;
	ProtocolBusBCastDefConfigPrivate * priv;
	gchar* LocalAddress;
	gchar* BCastAddress;
	gint32 Port;
	gint32 ReceiveBuffer;
	gint32 SendBuffer;
};

struct _ProtocolBusBCastDefConfigClass {
	ProtobufMessageClass parent_class;
};

struct _ProtocolBusBCastDefConfigText {
	ProtocolBusBCastDefConfig parent_instance;
	ProtocolBusBCastDefConfigTextPrivate * priv;
};

struct _ProtocolBusBCastDefConfigTextClass {
	ProtocolBusBCastDefConfigClass parent_class;
};

struct _ProtocolBusUDPStarDefConfig {
	ProtobufMessage parent_instance;
	ProtocolBusUDPStarDefConfigPrivate * priv;
	gchar* LocalAddress;
	gint32 Port;
	GList* EndPoint;
	gint32 ReceiveBuffer;
	gint32 SendBuffer;
};

struct _ProtocolBusUDPStarDefConfigClass {
	ProtobufMessageClass parent_class;
};

struct _ProtocolBusUDPStarDefConfigText {
	ProtocolBusUDPStarDefConfig parent_instance;
	ProtocolBusUDPStarDefConfigTextPrivate * priv;
};

struct _ProtocolBusUDPStarDefConfigTextClass {
	ProtocolBusUDPStarDefConfigClass parent_class;
};

struct _ProtocolBusEndPointDef {
	ProtobufMessage parent_instance;
	ProtocolBusEndPointDefPrivate * priv;
	gchar* Host;
	gint32 Port;
};

struct _ProtocolBusEndPointDefClass {
	ProtobufMessageClass parent_class;
};

struct _ProtocolBusEndPointDefText {
	ProtocolBusEndPointDef parent_instance;
	ProtocolBusEndPointDefTextPrivate * priv;
};

struct _ProtocolBusEndPointDefTextClass {
	ProtocolBusEndPointDefClass parent_class;
};

struct _ProtocolBusCrossConnectorDef {
	ProtobufMessage parent_instance;
	ProtocolBusCrossConnectorDefPrivate * priv;
	GList* Transport;
};

struct _ProtocolBusCrossConnectorDefClass {
	ProtobufMessageClass parent_class;
};

struct _ProtocolBusCrossConnectorDefText {
	ProtocolBusCrossConnectorDef parent_instance;
	ProtocolBusCrossConnectorDefTextPrivate * priv;
};

struct _ProtocolBusCrossConnectorDefTextClass {
	ProtocolBusCrossConnectorDefClass parent_class;
};

struct _ProtocolBusWaitHandle {
	GObject parent_instance;
	ProtocolBusWaitHandlePrivate * priv;
	GCond miaKond;
	GMutex miaMut;
	gboolean estasSignalita;
};

struct _ProtocolBusWaitHandleClass {
	GObjectClass parent_class;
};

struct _ProtocolBusManualResetEvent {
	ProtocolBusWaitHandle parent_instance;
	ProtocolBusManualResetEventPrivate * priv;
};

struct _ProtocolBusManualResetEventClass {
	ProtocolBusWaitHandleClass parent_class;
};

struct _ProtocolBusILogger {
	GObject parent_instance;
	ProtocolBusILoggerPrivate * priv;
};

struct _ProtocolBusILoggerClass {
	GObjectClass parent_class;
};

struct _ProtocolBusAppSync {
	ProtocolBusILogger parent_instance;
	ProtocolBusAppSyncPrivate * priv;
};

struct _ProtocolBusAppSyncClass {
	ProtocolBusILoggerClass parent_class;
};

struct _ProtocolBusCiphering {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ProtocolBusCipheringPrivate * priv;
};

struct _ProtocolBusCipheringClass {
	GTypeClass parent_class;
	void (*finalize) (ProtocolBusCiphering *self);
};

struct _ProtocolBusDictionaryEntry {
	GObject parent_instance;
	ProtocolBusDictionaryEntryPrivate * priv;
	gchar* Key;
	ProtocolBusQueueMgr* Value;
};

struct _ProtocolBusDictionaryEntryClass {
	GObjectClass parent_class;
};

struct _ProtocolBusQueueMgr {
	ProtocolBusILogger parent_instance;
	ProtocolBusQueueMgrPrivate * priv;
	ProtocolBusWaitHandle** ContinueWH;
	gint ContinueWH_length1;
	gchar* Name;
};

struct _ProtocolBusQueueMgrClass {
	ProtocolBusILoggerClass parent_class;
	void (*DispatchMsg) (ProtocolBusQueueMgr* self, GeeArrayList* msgList);
};

struct _ProtocolBusGSub {
	ProtocolBusQueueMgr parent_instance;
	ProtocolBusGSubPrivate * priv;
};

struct _ProtocolBusGSubClass {
	ProtocolBusQueueMgrClass parent_class;
	void (*OnDataReceived) (ProtocolBusGSub* self, gconstpointer myObj);
};

struct _ProtocolBusGPub {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ProtocolBusGPubPrivate * priv;
	guint64 myTypeName;
};

struct _ProtocolBusGPubClass {
	GTypeClass parent_class;
	void (*finalize) (ProtocolBusGPub *self);
};

struct _ProtocolBusPair {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ProtocolBusPairPrivate * priv;
	ProtocolBusTraceLevel tl;
	gchar* trace;
};

struct _ProtocolBusPairClass {
	GTypeClass parent_class;
	void (*finalize) (ProtocolBusPair *self);
};

struct _ProtocolBusTransport {
	ProtocolBusILogger parent_instance;
	ProtocolBusTransportPrivate * priv;
	ProtocolBusDomain* myDomain;
	gchar* myName;
	GThread* myThread;
	gboolean isStarted;
	ProtocolBusAppSync* theSync;
	gboolean ReceiveOwnMessages;
};

struct _ProtocolBusTransportClass {
	ProtocolBusILoggerClass parent_class;
	gboolean (*SendBytes) (ProtocolBusTransport* self, GBytes* data);
	void (*MainLoop) (ProtocolBusTransport* self);
};

struct _ProtobufUnknownField {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ProtobufUnknownFieldPrivate * priv;
	guint64 key;
	guint64 varint;
	GByteArray* data;
};

struct _ProtobufUnknownFieldClass {
	GTypeClass parent_class;
	void (*finalize) (ProtobufUnknownField *self);
};

struct _ProtobufDecodeBuffer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ProtobufDecodeBufferPrivate * priv;
	guint8* buffer;
	gint buffer_length1;
	gsize read_index;
	gboolean error;
};

struct _ProtobufDecodeBufferClass {
	GTypeClass parent_class;
	void (*finalize) (ProtobufDecodeBuffer *self);
};

struct _ProtobufEncodeBuffer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ProtobufEncodeBufferPrivate * priv;
	gsize write_index;
};

struct _ProtobufEncodeBufferClass {
	GTypeClass parent_class;
	void (*finalize) (ProtobufEncodeBuffer *self);
};

struct _ProtocolBusMsg {
	ProtobufMessage parent_instance;
	ProtocolBusMsgPrivate * priv;
	GList* channels;
	guint64 msgType;
	GByteArray* payLoad;
};

struct _ProtocolBusMsgClass {
	ProtobufMessageClass parent_class;
};

struct _ProtocolBusPacket {
	ProtobufMessage parent_instance;
	ProtocolBusPacketPrivate * priv;
	GList* messages;
	guint64 OutOfBand;
};

struct _ProtocolBusPacketClass {
	ProtobufMessageClass parent_class;
};

struct _ProtocolBusKeyRegistry {
	ProtobufMessage parent_instance;
	ProtocolBusKeyRegistryPrivate * priv;
	gchar* Date;
	gchar* Time;
	gchar* Sender;
	gchar* Phrase;
	gchar* Salt;
	GByteArray* AESKey;
	GByteArray* AESIV;
};

struct _ProtocolBusKeyRegistryClass {
	ProtobufMessageClass parent_class;
};

VALA_EXTERN GType protobuf_message_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtobufMessage, g_object_unref)
VALA_EXTERN gpointer protobuf_encode_buffer_ref (gpointer instance);
VALA_EXTERN void protobuf_encode_buffer_unref (gpointer instance);
VALA_EXTERN GParamSpec* protobuf_param_spec_encode_buffer (const gchar* name,
                                               const gchar* nick,
                                               const gchar* blurb,
                                               GType object_type,
                                               GParamFlags flags);
VALA_EXTERN void protobuf_value_set_encode_buffer (GValue* value,
                                       gpointer v_object);
VALA_EXTERN void protobuf_value_take_encode_buffer (GValue* value,
                                        gpointer v_object);
VALA_EXTERN gpointer protobuf_value_get_encode_buffer (const GValue* value);
VALA_EXTERN GType protobuf_encode_buffer_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtobufEncodeBuffer, protobuf_encode_buffer_unref)
VALA_EXTERN gpointer protobuf_decode_buffer_ref (gpointer instance);
VALA_EXTERN void protobuf_decode_buffer_unref (gpointer instance);
VALA_EXTERN GParamSpec* protobuf_param_spec_decode_buffer (const gchar* name,
                                               const gchar* nick,
                                               const gchar* blurb,
                                               GType object_type,
                                               GParamFlags flags);
VALA_EXTERN void protobuf_value_set_decode_buffer (GValue* value,
                                       gpointer v_object);
VALA_EXTERN void protobuf_value_take_decode_buffer (GValue* value,
                                        gpointer v_object);
VALA_EXTERN gpointer protobuf_value_get_decode_buffer (const GValue* value);
VALA_EXTERN GType protobuf_decode_buffer_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtobufDecodeBuffer, protobuf_decode_buffer_unref)
VALA_EXTERN gpointer protobuf_unknown_field_ref (gpointer instance);
VALA_EXTERN void protobuf_unknown_field_unref (gpointer instance);
VALA_EXTERN GParamSpec* protobuf_param_spec_unknown_field (const gchar* name,
                                               const gchar* nick,
                                               const gchar* blurb,
                                               GType object_type,
                                               GParamFlags flags);
VALA_EXTERN void protobuf_value_set_unknown_field (GValue* value,
                                       gpointer v_object);
VALA_EXTERN void protobuf_value_take_unknown_field (GValue* value,
                                        gpointer v_object);
VALA_EXTERN gpointer protobuf_value_get_unknown_field (const GValue* value);
VALA_EXTERN GType protobuf_unknown_field_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtobufUnknownField, protobuf_unknown_field_unref)
VALA_EXTERN GType protocol_bus_app_config_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusAppConfig, g_object_unref)
VALA_EXTERN GType protocol_bus_domain_cfg_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusDomainCfg, g_object_unref)
VALA_EXTERN GType protocol_bus_app_config_text_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusAppConfigText, g_object_unref)
VALA_EXTERN ProtocolBusAppConfigText* protocol_bus_app_config_text_new_from_text (const gchar* teksto);
VALA_EXTERN ProtocolBusAppConfigText* protocol_bus_app_config_text_construct_from_text (GType object_type,
                                                                            const gchar* teksto);
VALA_EXTERN ProtocolBusAppConfigText* protocol_bus_app_config_text_new (void);
VALA_EXTERN ProtocolBusAppConfigText* protocol_bus_app_config_text_construct (GType object_type);
VALA_EXTERN GType protocol_bus_transport_def_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusTransportDef, g_object_unref)
VALA_EXTERN GType protocol_bus_cross_connector_def_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusCrossConnectorDef, g_object_unref)
VALA_EXTERN GType protocol_bus_domain_cfg_text_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusDomainCfgText, g_object_unref)
VALA_EXTERN ProtocolBusDomainCfgText* protocol_bus_domain_cfg_text_new_from_text (const gchar* teksto);
VALA_EXTERN ProtocolBusDomainCfgText* protocol_bus_domain_cfg_text_construct_from_text (GType object_type,
                                                                            const gchar* teksto);
VALA_EXTERN ProtocolBusDomainCfgText* protocol_bus_domain_cfg_text_new (void);
VALA_EXTERN ProtocolBusDomainCfgText* protocol_bus_domain_cfg_text_construct (GType object_type);
VALA_EXTERN GType protocol_bus_mcast_def_config_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusMCastDefConfig, g_object_unref)
VALA_EXTERN GType protocol_bus_bcast_def_config_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusBCastDefConfig, g_object_unref)
VALA_EXTERN GType protocol_bus_udp_star_def_config_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusUDPStarDefConfig, g_object_unref)
VALA_EXTERN GType protocol_bus_transport_def_text_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusTransportDefText, g_object_unref)
VALA_EXTERN ProtocolBusTransportDefText* protocol_bus_transport_def_text_new_from_text (const gchar* teksto);
VALA_EXTERN ProtocolBusTransportDefText* protocol_bus_transport_def_text_construct_from_text (GType object_type,
                                                                                  const gchar* teksto);
VALA_EXTERN ProtocolBusTransportDefText* protocol_bus_transport_def_text_new (void);
VALA_EXTERN ProtocolBusTransportDefText* protocol_bus_transport_def_text_construct (GType object_type);
VALA_EXTERN GType protocol_bus_mcast_def_config_text_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusMCastDefConfigText, g_object_unref)
VALA_EXTERN ProtocolBusMCastDefConfigText* protocol_bus_mcast_def_config_text_new_from_text (const gchar* teksto);
VALA_EXTERN ProtocolBusMCastDefConfigText* protocol_bus_mcast_def_config_text_construct_from_text (GType object_type,
                                                                                       const gchar* teksto);
VALA_EXTERN ProtocolBusMCastDefConfigText* protocol_bus_mcast_def_config_text_new (void);
VALA_EXTERN ProtocolBusMCastDefConfigText* protocol_bus_mcast_def_config_text_construct (GType object_type);
VALA_EXTERN GType protocol_bus_bcast_def_config_text_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusBCastDefConfigText, g_object_unref)
VALA_EXTERN ProtocolBusBCastDefConfigText* protocol_bus_bcast_def_config_text_new_from_text (const gchar* teksto);
VALA_EXTERN ProtocolBusBCastDefConfigText* protocol_bus_bcast_def_config_text_construct_from_text (GType object_type,
                                                                                       const gchar* teksto);
VALA_EXTERN ProtocolBusBCastDefConfigText* protocol_bus_bcast_def_config_text_new (void);
VALA_EXTERN ProtocolBusBCastDefConfigText* protocol_bus_bcast_def_config_text_construct (GType object_type);
VALA_EXTERN GType protocol_bus_end_point_def_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusEndPointDef, g_object_unref)
VALA_EXTERN GType protocol_bus_udp_star_def_config_text_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusUDPStarDefConfigText, g_object_unref)
VALA_EXTERN ProtocolBusUDPStarDefConfigText* protocol_bus_udp_star_def_config_text_new_from_text (const gchar* teksto);
VALA_EXTERN ProtocolBusUDPStarDefConfigText* protocol_bus_udp_star_def_config_text_construct_from_text (GType object_type,
                                                                                            const gchar* teksto);
VALA_EXTERN ProtocolBusUDPStarDefConfigText* protocol_bus_udp_star_def_config_text_new (void);
VALA_EXTERN ProtocolBusUDPStarDefConfigText* protocol_bus_udp_star_def_config_text_construct (GType object_type);
VALA_EXTERN GType protocol_bus_end_point_def_text_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusEndPointDefText, g_object_unref)
VALA_EXTERN ProtocolBusEndPointDefText* protocol_bus_end_point_def_text_new_from_text (const gchar* teksto);
VALA_EXTERN ProtocolBusEndPointDefText* protocol_bus_end_point_def_text_construct_from_text (GType object_type,
                                                                                 const gchar* teksto);
VALA_EXTERN ProtocolBusEndPointDefText* protocol_bus_end_point_def_text_new (void);
VALA_EXTERN ProtocolBusEndPointDefText* protocol_bus_end_point_def_text_construct (GType object_type);
VALA_EXTERN GType protocol_bus_cross_connector_def_text_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusCrossConnectorDefText, g_object_unref)
VALA_EXTERN ProtocolBusCrossConnectorDefText* protocol_bus_cross_connector_def_text_new_from_text (const gchar* teksto);
VALA_EXTERN ProtocolBusCrossConnectorDefText* protocol_bus_cross_connector_def_text_construct_from_text (GType object_type,
                                                                                             const gchar* teksto);
VALA_EXTERN ProtocolBusCrossConnectorDefText* protocol_bus_cross_connector_def_text_new (void);
VALA_EXTERN ProtocolBusCrossConnectorDefText* protocol_bus_cross_connector_def_text_construct (GType object_type);
VALA_EXTERN GType protocol_bus_wait_handle_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusWaitHandle, g_object_unref)
VALA_EXTERN GType protocol_bus_ilogger_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusILogger, g_object_unref)
VALA_EXTERN GType protocol_bus_app_sync_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusAppSync, g_object_unref)
VALA_EXTERN ProtocolBusAppSync* protocol_bus_wait_handle_theSync;
VALA_EXTERN void protocol_bus_wait_handle_Wait (ProtocolBusWaitHandle* self);
VALA_EXTERN gboolean protocol_bus_wait_handle_WaitTime (ProtocolBusWaitHandle* self,
                                            gint msec);
VALA_EXTERN gboolean protocol_bus_wait_handle_IsSignaled (ProtocolBusWaitHandle* self);
VALA_EXTERN guint protocol_bus_wait_handle_WaitAny (ProtocolBusWaitHandle** whs,
                                        gint whs_length1);
VALA_EXTERN GType protocol_bus_manual_reset_event_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusManualResetEvent, g_object_unref)
VALA_EXTERN ProtocolBusManualResetEvent* protocol_bus_manual_reset_event_new (void);
VALA_EXTERN ProtocolBusManualResetEvent* protocol_bus_manual_reset_event_construct (GType object_type);
VALA_EXTERN void protocol_bus_manual_reset_event_Set (ProtocolBusManualResetEvent* self);
VALA_EXTERN void protocol_bus_manual_reset_event_Reset (ProtocolBusManualResetEvent* self);
VALA_EXTERN void protocol_bus_manual_reset_event_Kill (ProtocolBusManualResetEvent* self);
VALA_EXTERN ProtocolBusAppSync* protocol_bus_app_sync_GetInstance (void);
VALA_EXTERN ProtocolBusManualResetEvent* protocol_bus_app_sync_GetFinishedWH (ProtocolBusAppSync* self);
VALA_EXTERN void protocol_bus_app_sync_FinishApp (ProtocolBusAppSync* self);
VALA_EXTERN gboolean protocol_bus_app_sync_IsFinished (ProtocolBusAppSync* self);
VALA_EXTERN void protocol_bus_app_sync_RegisterThread (ProtocolBusAppSync* self,
                                           GThread* t);
VALA_EXTERN ProtocolBusAppSync* protocol_bus_app_sync_new (void);
VALA_EXTERN ProtocolBusAppSync* protocol_bus_app_sync_construct (GType object_type);
VALA_EXTERN gpointer protocol_bus_ciphering_ref (gpointer instance);
VALA_EXTERN void protocol_bus_ciphering_unref (gpointer instance);
VALA_EXTERN GParamSpec* protocol_bus_param_spec_ciphering (const gchar* name,
                                               const gchar* nick,
                                               const gchar* blurb,
                                               GType object_type,
                                               GParamFlags flags);
VALA_EXTERN void protocol_bus_value_set_ciphering (GValue* value,
                                       gpointer v_object);
VALA_EXTERN void protocol_bus_value_take_ciphering (GValue* value,
                                        gpointer v_object);
VALA_EXTERN gpointer protocol_bus_value_get_ciphering (const GValue* value);
VALA_EXTERN GType protocol_bus_ciphering_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusCiphering, protocol_bus_ciphering_unref)
VALA_EXTERN ProtocolBusCiphering* protocol_bus_ciphering_new (guchar* key,
                                                  gint key_length1,
                                                  guchar* iv,
                                                  gint iv_length1);
VALA_EXTERN ProtocolBusCiphering* protocol_bus_ciphering_construct (GType object_type,
                                                        guchar* key,
                                                        gint key_length1,
                                                        guchar* iv,
                                                        gint iv_length1);
VALA_EXTERN GBytes* protocol_bus_ciphering_Encrypt (ProtocolBusCiphering* self,
                                        GBytes* RedBytes);
VALA_EXTERN GBytes* protocol_bus_ciphering_Decrypt (ProtocolBusCiphering* self,
                                        GBytes* BlackBytes);
VALA_EXTERN gulong protocol_bus_ciphering_GetHash64 (const gchar* text);
VALA_EXTERN GType protocol_bus_dictionary_entry_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusDictionaryEntry, g_object_unref)
VALA_EXTERN GType protocol_bus_queue_mgr_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusQueueMgr, g_object_unref)
VALA_EXTERN ProtocolBusDictionaryEntry* protocol_bus_dictionary_entry_new (const gchar* k,
                                                               ProtocolBusQueueMgr* q);
VALA_EXTERN ProtocolBusDictionaryEntry* protocol_bus_dictionary_entry_construct (GType object_type,
                                                                     const gchar* k,
                                                                     ProtocolBusQueueMgr* q);
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusDomain, g_object_unref)
VALA_EXTERN ProtocolBusDomain* protocol_bus_domain_new (gint domain);
VALA_EXTERN ProtocolBusDomain* protocol_bus_domain_construct (GType object_type,
                                                  gint domain);
VALA_EXTERN ProtocolBusDomain* protocol_bus_domain_new_Batch (gint domain,
                                                  gint bwt);
VALA_EXTERN ProtocolBusDomain* protocol_bus_domain_construct_Batch (GType object_type,
                                                        gint domain,
                                                        gint bwt);
VALA_EXTERN gint protocol_bus_domain_GetDomainId (ProtocolBusDomain* self);
VALA_EXTERN GType protocol_bus_transport_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusTransport, g_object_unref)
VALA_EXTERN GeeArrayList* protocol_bus_domain_GetTransports (ProtocolBusDomain* self);
VALA_EXTERN GeeArrayList* protocol_bus_domain_GetRegistry (ProtocolBusDomain* self);
VALA_EXTERN void protocol_bus_domain_RegisterSubscriber (ProtocolBusDomain* self,
                                             ProtocolBusQueueMgr* qm,
                                             const gchar* channel);
VALA_EXTERN void protocol_bus_domain_UnregisterSuscriber (ProtocolBusDomain* self,
                                              ProtocolBusQueueMgr* qm,
                                              const gchar* channel);
VALA_EXTERN GType protocol_bus_msg_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusMsg, g_object_unref)
VALA_EXTERN void protocol_bus_domain_OnMsgReceived (ProtocolBusDomain* self,
                                        GeeArrayList* msgList);
VALA_EXTERN gboolean protocol_bus_domain_SendMsg (ProtocolBusDomain* self,
                                      ProtocolBusMsg* myMsg);
VALA_EXTERN void protocol_bus_domain_Close (ProtocolBusDomain* self);
VALA_EXTERN GBytes* protocol_bus_domain_Encrypt (ProtocolBusDomain* self,
                                     GBytes* RedBytes);
VALA_EXTERN GBytes* protocol_bus_domain_Decrypt (ProtocolBusDomain* self,
                                     GBytes* BlackBytes);
VALA_EXTERN gboolean protocol_bus_domain_get_HasCipheringKey (ProtocolBusDomain* self);
VALA_EXTERN void protocol_bus_domain_set_HasCipheringKey (ProtocolBusDomain* self,
                                              gboolean value);
VALA_EXTERN GType protocol_bus_gsub_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusGSub, g_object_unref)
VALA_EXTERN ProtocolBusGSub* protocol_bus_gsub_new (GType thetype_type,
                                        GBoxedCopyFunc thetype_dup_func,
                                        GDestroyNotify thetype_destroy_func,
                                        ProtocolBusDomain* theDomain,
                                        const gchar* theChannel,
                                        GHFunc fnDataReceive,
                                        gpointer fnDataReceive_target,
                                        gboolean started);
VALA_EXTERN ProtocolBusGSub* protocol_bus_gsub_construct (GType object_type,
                                              GType thetype_type,
                                              GBoxedCopyFunc thetype_dup_func,
                                              GDestroyNotify thetype_destroy_func,
                                              ProtocolBusDomain* theDomain,
                                              const gchar* theChannel,
                                              GHFunc fnDataReceive,
                                              gpointer fnDataReceive_target,
                                              gboolean started);
VALA_EXTERN gchar* protocol_bus_gsub_GetChannel (ProtocolBusGSub* self);
VALA_EXTERN void protocol_bus_gsub_OnDataReceived (ProtocolBusGSub* self,
                                       gconstpointer myObj);
VALA_EXTERN gpointer protocol_bus_gpub_ref (gpointer instance);
VALA_EXTERN void protocol_bus_gpub_unref (gpointer instance);
VALA_EXTERN GParamSpec* protocol_bus_param_spec_gpub (const gchar* name,
                                          const gchar* nick,
                                          const gchar* blurb,
                                          GType object_type,
                                          GParamFlags flags);
VALA_EXTERN void protocol_bus_value_set_gpub (GValue* value,
                                  gpointer v_object);
VALA_EXTERN void protocol_bus_value_take_gpub (GValue* value,
                                   gpointer v_object);
VALA_EXTERN gpointer protocol_bus_value_get_gpub (const GValue* value);
VALA_EXTERN GType protocol_bus_gpub_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusGPub, protocol_bus_gpub_unref)
VALA_EXTERN ProtocolBusGPub* protocol_bus_gpub_new (GType thetype_type,
                                        GBoxedCopyFunc thetype_dup_func,
                                        GDestroyNotify thetype_destroy_func,
                                        ProtocolBusDomain* theDomain);
VALA_EXTERN ProtocolBusGPub* protocol_bus_gpub_construct (GType object_type,
                                              GType thetype_type,
                                              GBoxedCopyFunc thetype_dup_func,
                                              GDestroyNotify thetype_destroy_func,
                                              ProtocolBusDomain* theDomain);
VALA_EXTERN void protocol_bus_gpub_SendMsgToChannels (ProtocolBusGPub* self,
                                          gchar** channels,
                                          gint channels_length1,
                                          gconstpointer myObj);
VALA_EXTERN void protocol_bus_gpub_SendMsg (ProtocolBusGPub* self,
                                const gchar* channel,
                                gconstpointer myObj);
VALA_EXTERN GType protocol_bus_trace_level_get_type (void) G_GNUC_CONST ;
VALA_EXTERN gpointer protocol_bus_pair_ref (gpointer instance);
VALA_EXTERN void protocol_bus_pair_unref (gpointer instance);
VALA_EXTERN GParamSpec* protocol_bus_param_spec_pair (const gchar* name,
                                          const gchar* nick,
                                          const gchar* blurb,
                                          GType object_type,
                                          GParamFlags flags);
VALA_EXTERN void protocol_bus_value_set_pair (GValue* value,
                                  gpointer v_object);
VALA_EXTERN void protocol_bus_value_take_pair (GValue* value,
                                   gpointer v_object);
VALA_EXTERN gpointer protocol_bus_value_get_pair (const GValue* value);
VALA_EXTERN GType protocol_bus_pair_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusPair, protocol_bus_pair_unref)
VALA_EXTERN ProtocolBusPair* protocol_bus_pair_new (ProtocolBusTraceLevel atl,
                                        const gchar* atrace);
VALA_EXTERN ProtocolBusPair* protocol_bus_pair_construct (GType object_type,
                                              ProtocolBusTraceLevel atl,
                                              const gchar* atrace);
VALA_EXTERN void protocol_bus_ilogger_LoggerTrace (ProtocolBusILogger* self,
                                       ProtocolBusTraceLevel tl,
                                       const gchar* trace);
VALA_EXTERN void protocol_bus_ilogger_LoggerTraceWithErr (ProtocolBusILogger* self,
                                              ProtocolBusTraceLevel tl,
                                              const gchar* trace,
                                              GError* ex);
VALA_EXTERN void protocol_bus_ilogger_LoggerTraceOn (ProtocolBusTraceLevel tl);
VALA_EXTERN void protocol_bus_ilogger_FinishLog (void);
VALA_EXTERN ProtocolBusILogger* protocol_bus_ilogger_construct (GType object_type);
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusLogger, g_object_unref)
VALA_EXTERN GType protocol_bus_batch_mode_get_type (void) G_GNUC_CONST ;
VALA_EXTERN ProtocolBusQueueMgr* protocol_bus_queue_mgr_construct (GType object_type,
                                                       const gchar* nomo);
VALA_EXTERN ProtocolBusQueueMgr* protocol_bus_queue_mgr_construct_Extd (GType object_type,
                                                            ProtocolBusBatchMode bm,
                                                            gint bwt,
                                                            const gchar* nomo);
VALA_EXTERN ProtocolBusQueueMgr* protocol_bus_queue_mgr_construct_Started (GType object_type,
                                                               gboolean bBeginStarted,
                                                               const gchar* nomo);
VALA_EXTERN ProtocolBusQueueMgr* protocol_bus_queue_mgr_construct_Full (GType object_type,
                                                            gboolean bBeginStarted,
                                                            ProtocolBusBatchMode bm,
                                                            gint bwt,
                                                            const gchar* nomo);
VALA_EXTERN void protocol_bus_queue_mgr_InitializeQueue (ProtocolBusQueueMgr* self,
                                             const gchar* nomo);
VALA_EXTERN void protocol_bus_queue_mgr_StartMainLoop (ProtocolBusQueueMgr* self);
VALA_EXTERN void protocol_bus_queue_mgr_Enqueue (ProtocolBusQueueMgr* self,
                                     ProtocolBusMsg* myMsg);
VALA_EXTERN void protocol_bus_queue_mgr_EnqueueMult (ProtocolBusQueueMgr* self,
                                         GeeArrayList* msgList);
VALA_EXTERN void protocol_bus_queue_mgr_DispatchMsg (ProtocolBusQueueMgr* self,
                                         GeeArrayList* msgList);
VALA_EXTERN GType protocol_bus_stream_mode_get_type (void) G_GNUC_CONST ;
VALA_EXTERN ProtocolBusTransport* protocol_bus_transport_construct (GType object_type,
                                                        ProtocolBusDomain* domain,
                                                        const gchar* name);
VALA_EXTERN void protocol_bus_transport_StartMainLoop (ProtocolBusTransport* self);
VALA_EXTERN gboolean protocol_bus_transport_ParseAndEnqueue (ProtocolBusTransport* self,
                                                 GBytes* data);
VALA_EXTERN GType protocol_bus_packet_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusPacket, g_object_unref)
VALA_EXTERN gboolean protocol_bus_transport_SendPck (ProtocolBusTransport* self,
                                         ProtocolBusPacket* myPck);
VALA_EXTERN void protocol_bus_transport_CrossConnect (ProtocolBusTransport* self,
                                          ProtocolBusTransport* t);
VALA_EXTERN gboolean protocol_bus_transport_SendBytes (ProtocolBusTransport* self,
                                           GBytes* data);
VALA_EXTERN void protocol_bus_transport_MainLoop (ProtocolBusTransport* self);
VALA_EXTERN gboolean protocol_bus_transport_is4NumericAddress (ProtocolBusTransport* self,
                                                   const gchar* texto);
VALA_EXTERN GInetAddress* protocol_bus_transport_GetLocalAddress (ProtocolBusTransport* self,
                                                      const gchar* localaddres);
VALA_EXTERN gboolean protocol_bus_transport_get_IsStarted (ProtocolBusTransport* self);
VALA_EXTERN void protocol_bus_transport_set_IsStarted (ProtocolBusTransport* self,
                                           gboolean value);
VALA_EXTERN const gchar* protocol_bus_transport_get_Name (ProtocolBusTransport* self);
VALA_EXTERN void protocol_bus_transport_set_Name (ProtocolBusTransport* self,
                                      const gchar* value);
VALA_EXTERN gsize protobuf_message_encode (ProtobufMessage* self,
                               ProtobufEncodeBuffer* buffer);
VALA_EXTERN gboolean protobuf_message_decode (ProtobufMessage* self,
                                  ProtobufDecodeBuffer* buffer,
                                  gssize data_length);
VALA_EXTERN gchar* protobuf_message_to_string (ProtobufMessage* self,
                                   const gchar* indent);
VALA_EXTERN ProtobufMessage* protobuf_message_construct (GType object_type);
VALA_EXTERN ProtobufUnknownField* protobuf_unknown_field_new (void);
VALA_EXTERN ProtobufUnknownField* protobuf_unknown_field_construct (GType object_type);
VALA_EXTERN ProtobufDecodeBuffer* protobuf_decode_buffer_new (guint8* buffer,
                                                  gint buffer_length1,
                                                  gsize offset,
                                                  gssize length);
VALA_EXTERN ProtobufDecodeBuffer* protobuf_decode_buffer_construct (GType object_type,
                                                        guint8* buffer,
                                                        gint buffer_length1,
                                                        gsize offset,
                                                        gssize length);
VALA_EXTERN ProtobufDecodeBuffer* protobuf_decode_buffer_new_sized (gsize size);
VALA_EXTERN ProtobufDecodeBuffer* protobuf_decode_buffer_construct_sized (GType object_type,
                                                              gsize size);
VALA_EXTERN void protobuf_decode_buffer_reset (ProtobufDecodeBuffer* self);
VALA_EXTERN guint64 protobuf_decode_buffer_decode_varint (ProtobufDecodeBuffer* self);
VALA_EXTERN gdouble protobuf_decode_buffer_decode_double (ProtobufDecodeBuffer* self);
VALA_EXTERN gfloat protobuf_decode_buffer_decode_float (ProtobufDecodeBuffer* self);
VALA_EXTERN gint64 protobuf_decode_buffer_decode_int64 (ProtobufDecodeBuffer* self);
VALA_EXTERN guint64 protobuf_decode_buffer_decode_uint64 (ProtobufDecodeBuffer* self);
VALA_EXTERN gint32 protobuf_decode_buffer_decode_int32 (ProtobufDecodeBuffer* self);
VALA_EXTERN guint64 protobuf_decode_buffer_decode_fixed64 (ProtobufDecodeBuffer* self);
VALA_EXTERN guint32 protobuf_decode_buffer_decode_fixed32 (ProtobufDecodeBuffer* self);
VALA_EXTERN gboolean protobuf_decode_buffer_decode_bool (ProtobufDecodeBuffer* self);
VALA_EXTERN gchar* protobuf_decode_buffer_decode_string (ProtobufDecodeBuffer* self,
                                             gsize length);
VALA_EXTERN GByteArray* protobuf_decode_buffer_decode_bytes (ProtobufDecodeBuffer* self,
                                                 gsize length);
VALA_EXTERN guint32 protobuf_decode_buffer_decode_uint32 (ProtobufDecodeBuffer* self);
VALA_EXTERN gint32 protobuf_decode_buffer_decode_sfixed32 (ProtobufDecodeBuffer* self);
VALA_EXTERN gint64 protobuf_decode_buffer_decode_sfixed64 (ProtobufDecodeBuffer* self);
VALA_EXTERN gint32 protobuf_decode_buffer_decode_sint32 (ProtobufDecodeBuffer* self);
VALA_EXTERN gint64 protobuf_decode_buffer_decode_sint64 (ProtobufDecodeBuffer* self);
VALA_EXTERN ProtobufUnknownField* protobuf_decode_buffer_decode_unknown_field (ProtobufDecodeBuffer* self,
                                                                   guint64 key);
VALA_EXTERN ProtobufEncodeBuffer* protobuf_encode_buffer_new (gsize size);
VALA_EXTERN ProtobufEncodeBuffer* protobuf_encode_buffer_construct (GType object_type,
                                                        gsize size);
VALA_EXTERN void protobuf_encode_buffer_reset (ProtobufEncodeBuffer* self);
VALA_EXTERN gsize protobuf_encode_buffer_encode_varint (ProtobufEncodeBuffer* self,
                                            guint64 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_double (ProtobufEncodeBuffer* self,
                                            gdouble value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_float (ProtobufEncodeBuffer* self,
                                           gfloat value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_int64 (ProtobufEncodeBuffer* self,
                                           gint64 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_uint64 (ProtobufEncodeBuffer* self,
                                            guint64 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_int32 (ProtobufEncodeBuffer* self,
                                           gint32 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_fixed64 (ProtobufEncodeBuffer* self,
                                             guint64 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_fixed32 (ProtobufEncodeBuffer* self,
                                             guint32 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_bool (ProtobufEncodeBuffer* self,
                                          gboolean value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_string (ProtobufEncodeBuffer* self,
                                            const gchar* value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_bytes (ProtobufEncodeBuffer* self,
                                           GByteArray* value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_uint32 (ProtobufEncodeBuffer* self,
                                            guint32 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_sfixed32 (ProtobufEncodeBuffer* self,
                                              gint32 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_sfixed64 (ProtobufEncodeBuffer* self,
                                              gint64 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_sint32 (ProtobufEncodeBuffer* self,
                                            gint32 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_sint64 (ProtobufEncodeBuffer* self,
                                            gint64 value);
VALA_EXTERN gsize protobuf_encode_buffer_encode_unknown_field (ProtobufEncodeBuffer* self,
                                                   ProtobufUnknownField* value);
VALA_EXTERN guint8* protobuf_encode_buffer_get_data (ProtobufEncodeBuffer* self,
                                         gint* result_length1);
VALA_EXTERN gchar* protobuf_bytes_to_string (GByteArray* value);
VALA_EXTERN gchar* protobuf_string_to_string (const gchar* value);
VALA_EXTERN ProtocolBusAppConfig* protocol_bus_app_config_new (void);
VALA_EXTERN ProtocolBusAppConfig* protocol_bus_app_config_construct (GType object_type);
VALA_EXTERN ProtocolBusAppConfig* protocol_bus_app_config_new_from_data (ProtobufDecodeBuffer* buffer,
                                                             gssize data_length);
VALA_EXTERN ProtocolBusAppConfig* protocol_bus_app_config_construct_from_data (GType object_type,
                                                                   ProtobufDecodeBuffer* buffer,
                                                                   gssize data_length);
VALA_EXTERN ProtocolBusDomainCfg* protocol_bus_domain_cfg_new (void);
VALA_EXTERN ProtocolBusDomainCfg* protocol_bus_domain_cfg_construct (GType object_type);
VALA_EXTERN ProtocolBusDomainCfg* protocol_bus_domain_cfg_new_from_data (ProtobufDecodeBuffer* buffer,
                                                             gssize data_length);
VALA_EXTERN ProtocolBusDomainCfg* protocol_bus_domain_cfg_construct_from_data (GType object_type,
                                                                   ProtobufDecodeBuffer* buffer,
                                                                   gssize data_length);
VALA_EXTERN ProtocolBusTransportDef* protocol_bus_transport_def_new (void);
VALA_EXTERN ProtocolBusTransportDef* protocol_bus_transport_def_construct (GType object_type);
VALA_EXTERN ProtocolBusTransportDef* protocol_bus_transport_def_new_from_data (ProtobufDecodeBuffer* buffer,
                                                                   gssize data_length);
VALA_EXTERN ProtocolBusTransportDef* protocol_bus_transport_def_construct_from_data (GType object_type,
                                                                         ProtobufDecodeBuffer* buffer,
                                                                         gssize data_length);
VALA_EXTERN ProtocolBusMCastDefConfig* protocol_bus_mcast_def_config_new (void);
VALA_EXTERN ProtocolBusMCastDefConfig* protocol_bus_mcast_def_config_construct (GType object_type);
VALA_EXTERN ProtocolBusMCastDefConfig* protocol_bus_mcast_def_config_new_from_data (ProtobufDecodeBuffer* buffer,
                                                                        gssize data_length);
VALA_EXTERN ProtocolBusMCastDefConfig* protocol_bus_mcast_def_config_construct_from_data (GType object_type,
                                                                              ProtobufDecodeBuffer* buffer,
                                                                              gssize data_length);
VALA_EXTERN ProtocolBusBCastDefConfig* protocol_bus_bcast_def_config_new (void);
VALA_EXTERN ProtocolBusBCastDefConfig* protocol_bus_bcast_def_config_construct (GType object_type);
VALA_EXTERN ProtocolBusBCastDefConfig* protocol_bus_bcast_def_config_new_from_data (ProtobufDecodeBuffer* buffer,
                                                                        gssize data_length);
VALA_EXTERN ProtocolBusBCastDefConfig* protocol_bus_bcast_def_config_construct_from_data (GType object_type,
                                                                              ProtobufDecodeBuffer* buffer,
                                                                              gssize data_length);
VALA_EXTERN ProtocolBusUDPStarDefConfig* protocol_bus_udp_star_def_config_new (void);
VALA_EXTERN ProtocolBusUDPStarDefConfig* protocol_bus_udp_star_def_config_construct (GType object_type);
VALA_EXTERN ProtocolBusUDPStarDefConfig* protocol_bus_udp_star_def_config_new_from_data (ProtobufDecodeBuffer* buffer,
                                                                             gssize data_length);
VALA_EXTERN ProtocolBusUDPStarDefConfig* protocol_bus_udp_star_def_config_construct_from_data (GType object_type,
                                                                                   ProtobufDecodeBuffer* buffer,
                                                                                   gssize data_length);
VALA_EXTERN ProtocolBusEndPointDef* protocol_bus_end_point_def_new (void);
VALA_EXTERN ProtocolBusEndPointDef* protocol_bus_end_point_def_construct (GType object_type);
VALA_EXTERN ProtocolBusEndPointDef* protocol_bus_end_point_def_new_from_data (ProtobufDecodeBuffer* buffer,
                                                                  gssize data_length);
VALA_EXTERN ProtocolBusEndPointDef* protocol_bus_end_point_def_construct_from_data (GType object_type,
                                                                        ProtobufDecodeBuffer* buffer,
                                                                        gssize data_length);
VALA_EXTERN ProtocolBusCrossConnectorDef* protocol_bus_cross_connector_def_new (void);
VALA_EXTERN ProtocolBusCrossConnectorDef* protocol_bus_cross_connector_def_construct (GType object_type);
VALA_EXTERN ProtocolBusCrossConnectorDef* protocol_bus_cross_connector_def_new_from_data (ProtobufDecodeBuffer* buffer,
                                                                              gssize data_length);
VALA_EXTERN ProtocolBusCrossConnectorDef* protocol_bus_cross_connector_def_construct_from_data (GType object_type,
                                                                                    ProtobufDecodeBuffer* buffer,
                                                                                    gssize data_length);
VALA_EXTERN ProtocolBusMsg* protocol_bus_msg_new (void);
VALA_EXTERN ProtocolBusMsg* protocol_bus_msg_construct (GType object_type);
VALA_EXTERN ProtocolBusMsg* protocol_bus_msg_new_from_data (ProtobufDecodeBuffer* buffer,
                                                gssize data_length);
VALA_EXTERN ProtocolBusMsg* protocol_bus_msg_construct_from_data (GType object_type,
                                                      ProtobufDecodeBuffer* buffer,
                                                      gssize data_length);
VALA_EXTERN ProtocolBusPacket* protocol_bus_packet_new (void);
VALA_EXTERN ProtocolBusPacket* protocol_bus_packet_construct (GType object_type);
VALA_EXTERN ProtocolBusPacket* protocol_bus_packet_new_from_data (ProtobufDecodeBuffer* buffer,
                                                      gssize data_length);
VALA_EXTERN ProtocolBusPacket* protocol_bus_packet_construct_from_data (GType object_type,
                                                            ProtobufDecodeBuffer* buffer,
                                                            gssize data_length);
VALA_EXTERN GType protocol_bus_key_registry_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ProtocolBusKeyRegistry, g_object_unref)
VALA_EXTERN ProtocolBusKeyRegistry* protocol_bus_key_registry_new (void);
VALA_EXTERN ProtocolBusKeyRegistry* protocol_bus_key_registry_construct (GType object_type);
VALA_EXTERN ProtocolBusKeyRegistry* protocol_bus_key_registry_new_from_data (ProtobufDecodeBuffer* buffer,
                                                                 gssize data_length);
VALA_EXTERN ProtocolBusKeyRegistry* protocol_bus_key_registry_construct_from_data (GType object_type,
                                                                       ProtobufDecodeBuffer* buffer,
                                                                       gssize data_length);

G_END_DECLS

#endif
