// Generated by protoc-gen-vala 0.1.0 from CentralServer.proto, do not edit

public class XMPPDefConfig : Protobuf.Message
{
    public string SendingUser;
    public string SendingPssw;
    public string TopicUser;
    public string TopicPssw;
    public string Server;
    public string ConnectServer;
    public ProxyDefConfig? Proxy;

    public XMPPDefConfig ()
    {
        this.SendingUser = "";
        this.SendingPssw = "";
        this.TopicUser = "";
        this.TopicPssw = "";
        this.Server = "gmail.com";
        this.ConnectServer = "talk.google.com";
        this.Proxy = null;
    }

    public XMPPDefConfig.from_data (Protobuf.DecodeBuffer buffer, ssize_t data_length = -1)
    {
        decode (buffer, data_length);
    }

    public override bool decode (Protobuf.DecodeBuffer buffer, ssize_t data_length = -1)
    {
        size_t end;
        if (data_length < 0)
            end = buffer.buffer.length;
        else
            end = buffer.read_index + data_length;
        var have_SendingUser = false;
        var have_SendingPssw = false;
        var have_TopicUser = false;
        var have_TopicPssw = false;

        this.SendingUser = "";
        this.SendingPssw = "";
        this.TopicUser = "";
        this.TopicPssw = "";
        this.Server = "gmail.com";
        this.ConnectServer = "talk.google.com";
        this.Proxy = null;
        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
            {
                this.SendingUser = buffer.decode_string ((size_t) buffer.decode_varint ());
                have_SendingUser = true;
            }
            else if (field_number == 2 && wire_type == 2)
            {
                this.SendingPssw = buffer.decode_string ((size_t) buffer.decode_varint ());
                have_SendingPssw = true;
            }
            else if (field_number == 3 && wire_type == 2)
            {
                this.TopicUser = buffer.decode_string ((size_t) buffer.decode_varint ());
                have_TopicUser = true;
            }
            else if (field_number == 4 && wire_type == 2)
            {
                this.TopicPssw = buffer.decode_string ((size_t) buffer.decode_varint ());
                have_TopicPssw = true;
            }
            else if (field_number == 5 && wire_type == 2)
                this.Server = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 6 && wire_type == 2)
                this.ConnectServer = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 7 && wire_type == 2)
                this.Proxy = new ProxyDefConfig.from_data (buffer, (ssize_t) buffer.decode_varint ());
            else
                this.unknown_fields.prepend (buffer.decode_unknown_field (key));
        }

        if (buffer.read_index != end)
            buffer.error = true;
        else if (!have_SendingUser || !have_SendingPssw || !have_TopicUser || !have_TopicPssw)
            buffer.error = true;

        return !buffer.error;
    }

    public override size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        foreach (var f in this.unknown_fields)
            n_written += buffer.encode_unknown_field (f);
        if (this.Proxy != null)
        {
            var Proxy_length = this.Proxy.encode (buffer);
            n_written += Proxy_length;
            n_written += buffer.encode_varint (Proxy_length);
            n_written += buffer.encode_varint (58);
        }
        if (this.ConnectServer != "talk.google.com")
        {
            var ConnectServer_length = buffer.encode_string (this.ConnectServer);
            n_written += ConnectServer_length;
            n_written += buffer.encode_varint (ConnectServer_length);
            n_written += buffer.encode_varint (50);
        }
        if (this.Server != "gmail.com")
        {
            var Server_length = buffer.encode_string (this.Server);
            n_written += Server_length;
            n_written += buffer.encode_varint (Server_length);
            n_written += buffer.encode_varint (42);
        }
        var TopicPssw_length = buffer.encode_string (this.TopicPssw);
        n_written += TopicPssw_length;
        n_written += buffer.encode_varint (TopicPssw_length);
        n_written += buffer.encode_varint (34);
        var TopicUser_length = buffer.encode_string (this.TopicUser);
        n_written += TopicUser_length;
        n_written += buffer.encode_varint (TopicUser_length);
        n_written += buffer.encode_varint (26);
        var SendingPssw_length = buffer.encode_string (this.SendingPssw);
        n_written += SendingPssw_length;
        n_written += buffer.encode_varint (SendingPssw_length);
        n_written += buffer.encode_varint (18);
        var SendingUser_length = buffer.encode_string (this.SendingUser);
        n_written += SendingUser_length;
        n_written += buffer.encode_varint (SendingUser_length);
        n_written += buffer.encode_varint (10);

        return n_written;
    }

    public override string to_string (string indent = "")
    {
        var text = "";

        text += indent + "SendingUser: %s\n".printf (Protobuf.string_to_string (this.SendingUser));
        text += indent + "SendingPssw: %s\n".printf (Protobuf.string_to_string (this.SendingPssw));
        text += indent + "TopicUser: %s\n".printf (Protobuf.string_to_string (this.TopicUser));
        text += indent + "TopicPssw: %s\n".printf (Protobuf.string_to_string (this.TopicPssw));
        text += indent + "Server: %s\n".printf (Protobuf.string_to_string (this.Server));
        text += indent + "ConnectServer: %s\n".printf (Protobuf.string_to_string (this.ConnectServer));
        if (Proxy != null)
        {
            text += indent + "Proxy {\n";
            text += "%s".printf (this.Proxy.to_string (indent + "  "));
            text += indent + "}\n";
        }

        return text;
    }
}

public class K6ServerDefConfig : Protobuf.Message
{
    public EndPointDef K6Server;
    public string Service;
    public string Password;
    public ProxyDefConfig? Proxy;

    public K6ServerDefConfig ()
    {
        this.K6Server = new EndPointDef ();
        this.Service = "";
        this.Password = "";
        this.Proxy = null;
    }

    public K6ServerDefConfig.from_data (Protobuf.DecodeBuffer buffer, ssize_t data_length = -1)
    {
        decode (buffer, data_length);
    }

    public override bool decode (Protobuf.DecodeBuffer buffer, ssize_t data_length = -1)
    {
        size_t end;
        if (data_length < 0)
            end = buffer.buffer.length;
        else
            end = buffer.read_index + data_length;
        var have_K6Server = false;
        var have_Service = false;
        var have_Password = false;

        this.K6Server = new EndPointDef ();
        this.Service = "";
        this.Password = "";
        this.Proxy = null;
        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
            {
                this.K6Server = new EndPointDef.from_data (buffer, (ssize_t) buffer.decode_varint ());
                have_K6Server = true;
            }
            else if (field_number == 2 && wire_type == 2)
            {
                this.Service = buffer.decode_string ((size_t) buffer.decode_varint ());
                have_Service = true;
            }
            else if (field_number == 3 && wire_type == 2)
            {
                this.Password = buffer.decode_string ((size_t) buffer.decode_varint ());
                have_Password = true;
            }
            else if (field_number == 4 && wire_type == 2)
                this.Proxy = new ProxyDefConfig.from_data (buffer, (ssize_t) buffer.decode_varint ());
            else
                this.unknown_fields.prepend (buffer.decode_unknown_field (key));
        }

        if (buffer.read_index != end)
            buffer.error = true;
        else if (!have_K6Server || !have_Service || !have_Password)
            buffer.error = true;

        return !buffer.error;
    }

    public override size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        foreach (var f in this.unknown_fields)
            n_written += buffer.encode_unknown_field (f);
        if (this.Proxy != null)
        {
            var Proxy_length = this.Proxy.encode (buffer);
            n_written += Proxy_length;
            n_written += buffer.encode_varint (Proxy_length);
            n_written += buffer.encode_varint (34);
        }
        var Password_length = buffer.encode_string (this.Password);
        n_written += Password_length;
        n_written += buffer.encode_varint (Password_length);
        n_written += buffer.encode_varint (26);
        var Service_length = buffer.encode_string (this.Service);
        n_written += Service_length;
        n_written += buffer.encode_varint (Service_length);
        n_written += buffer.encode_varint (18);
        var K6Server_length = this.K6Server.encode (buffer);
        n_written += K6Server_length;
        n_written += buffer.encode_varint (K6Server_length);
        n_written += buffer.encode_varint (10);

        return n_written;
    }

    public override string to_string (string indent = "")
    {
        var text = "";

        if (K6Server != null)
        {
            text += indent + "K6Server {\n";
            text += "%s".printf (this.K6Server.to_string (indent + "  "));
            text += indent + "}\n";
        }
        text += indent + "Service: %s\n".printf (Protobuf.string_to_string (this.Service));
        text += indent + "Password: %s\n".printf (Protobuf.string_to_string (this.Password));
        if (Proxy != null)
        {
            text += indent + "Proxy {\n";
            text += "%s".printf (this.Proxy.to_string (indent + "  "));
            text += indent + "}\n";
        }

        return text;
    }
}

public class ProxyDefConfig : Protobuf.Message
{
    public EndPointDef Server;
    public string User;
    public string Password;

    public ProxyDefConfig ()
    {
        this.Server = new EndPointDef ();
        this.User = "";
        this.Password = "";
    }

    public ProxyDefConfig.from_data (Protobuf.DecodeBuffer buffer, ssize_t data_length = -1)
    {
        decode (buffer, data_length);
    }

    public override bool decode (Protobuf.DecodeBuffer buffer, ssize_t data_length = -1)
    {
        size_t end;
        if (data_length < 0)
            end = buffer.buffer.length;
        else
            end = buffer.read_index + data_length;
        var have_Server = false;

        this.Server = new EndPointDef ();
        this.User = "";
        this.Password = "";
        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
            {
                this.Server = new EndPointDef.from_data (buffer, (ssize_t) buffer.decode_varint ());
                have_Server = true;
            }
            else if (field_number == 2 && wire_type == 2)
                this.User = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 3 && wire_type == 2)
                this.Password = buffer.decode_string ((size_t) buffer.decode_varint ());
            else
                this.unknown_fields.prepend (buffer.decode_unknown_field (key));
        }

        if (buffer.read_index != end)
            buffer.error = true;
        else if (!have_Server)
            buffer.error = true;

        return !buffer.error;
    }

    public override size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        foreach (var f in this.unknown_fields)
            n_written += buffer.encode_unknown_field (f);
        if (this.Password != "")
        {
            var Password_length = buffer.encode_string (this.Password);
            n_written += Password_length;
            n_written += buffer.encode_varint (Password_length);
            n_written += buffer.encode_varint (26);
        }
        if (this.User != "")
        {
            var User_length = buffer.encode_string (this.User);
            n_written += User_length;
            n_written += buffer.encode_varint (User_length);
            n_written += buffer.encode_varint (18);
        }
        var Server_length = this.Server.encode (buffer);
        n_written += Server_length;
        n_written += buffer.encode_varint (Server_length);
        n_written += buffer.encode_varint (10);

        return n_written;
    }

    public override string to_string (string indent = "")
    {
        var text = "";

        if (Server != null)
        {
            text += indent + "Server {\n";
            text += "%s".printf (this.Server.to_string (indent + "  "));
            text += indent + "}\n";
        }
        text += indent + "User: %s\n".printf (Protobuf.string_to_string (this.User));
        text += indent + "Password: %s\n".printf (Protobuf.string_to_string (this.Password));

        return text;
    }
}
