/* DP_aux.c generated by valac 0.56.0, the Vala compiler
 * generated from DP_aux.vala, do not modify */

#include <protocolbus.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <stdio.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_DP_SUB (dp_sub_get_type ())
#define DP_SUB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DP_SUB, DPSub))
#define DP_SUB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DP_SUB, DPSubClass))
#define IS_DP_SUB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DP_SUB))
#define IS_DP_SUB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DP_SUB))
#define DP_SUB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DP_SUB, DPSubClass))

typedef struct _DPSub DPSub;
typedef struct _DPSubClass DPSubClass;
typedef struct _DPSubPrivate DPSubPrivate;
enum  {
	DP_SUB_0_PROPERTY,
	DP_SUB_NUM_PROPERTIES
};
static GParamSpec* dp_sub_properties[DP_SUB_NUM_PROPERTIES];

#define TYPE_DATA_PCK (data_pck_get_type ())
#define DATA_PCK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DATA_PCK, DataPck))
#define DATA_PCK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DATA_PCK, DataPckClass))
#define IS_DATA_PCK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DATA_PCK))
#define IS_DATA_PCK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DATA_PCK))
#define DATA_PCK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DATA_PCK, DataPckClass))

typedef struct _DataPck DataPck;
typedef struct _DataPckClass DataPckClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _DPSub {
	ProtocolBusGSub parent_instance;
	DPSubPrivate * priv;
};

struct _DPSubClass {
	ProtocolBusGSubClass parent_class;
};

static gpointer dp_sub_parent_class = NULL;

VALA_EXTERN GType dp_sub_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DPSub, g_object_unref)
VALA_EXTERN DPSub* dp_sub_new (ProtocolBusDomain* domain,
                   const gchar* theChannel);
VALA_EXTERN DPSub* dp_sub_construct (GType object_type,
                         ProtocolBusDomain* domain,
                         const gchar* theChannel);
static void __lambda4__gh_func (gconstpointer key,
                         gconstpointer value,
                         gpointer self);
VALA_EXTERN GType data_pck_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DataPck, g_object_unref)
static void dp_sub_real_OnDataReceived (ProtocolBusGSub* base,
                                 DataPck* myObj);
static GType dp_sub_get_type_once (void);
VALA_EXTERN void OnDataReceivedDP (DataPck* myObj,
                       const gchar* ch);

static void
_lambda4_ (ProtocolBusGSub* self)
{
}

static void
__lambda4__gh_func (gconstpointer key,
                    gconstpointer value,
                    gpointer self)
{
	_lambda4_ ((ProtocolBusGSub*) self);
}

DPSub*
dp_sub_construct (GType object_type,
                  ProtocolBusDomain* domain,
                  const gchar* theChannel)
{
	DPSub * self = NULL;
	g_return_val_if_fail (domain != NULL, NULL);
	g_return_val_if_fail (theChannel != NULL, NULL);
	self = (DPSub*) protocol_bus_gsub_construct (object_type, TYPE_DATA_PCK, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, domain, theChannel, __lambda4__gh_func, self, TRUE);
	return self;
}

DPSub*
dp_sub_new (ProtocolBusDomain* domain,
            const gchar* theChannel)
{
	return dp_sub_construct (TYPE_DP_SUB, domain, theChannel);
}

static void
dp_sub_real_OnDataReceived (ProtocolBusGSub* base,
                            DataPck* myObj)
{
	DPSub * self;
	FILE* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	self = (DPSub*) base;
	g_return_if_fail (myObj != NULL);
	_tmp0_ = stdout;
	_tmp1_ = protocol_bus_gsub_GetChannel ((ProtocolBusGSub*) self);
	_tmp2_ = _tmp1_;
	_tmp3_ = protobuf_message_to_string ((ProtobufMessage*) myObj, "    ");
	_tmp4_ = _tmp3_;
	fprintf (_tmp0_, "\t\t\tDP Sub by override %s: Msg received:\n{\n%s}\n", _tmp2_, _tmp4_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
}

static void
dp_sub_class_init (DPSubClass * klass,
                   gpointer klass_data)
{
	dp_sub_parent_class = g_type_class_peek_parent (klass);
	((ProtocolBusGSubClass *) klass)->OnDataReceived = (void (*) (ProtocolBusGSub*, gconstpointer)) dp_sub_real_OnDataReceived;
}

static void
dp_sub_instance_init (DPSub * self,
                      gpointer klass)
{
}

static GType
dp_sub_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DPSubClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dp_sub_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DPSub), 0, (GInstanceInitFunc) dp_sub_instance_init, NULL };
	GType dp_sub_type_id;
	dp_sub_type_id = g_type_register_static (PROTOCOL_BUS_TYPE_GSUB, "DPSub", &g_define_type_info, 0);
	return dp_sub_type_id;
}

GType
dp_sub_get_type (void)
{
	static volatile gsize dp_sub_type_id__once = 0;
	if (g_once_init_enter (&dp_sub_type_id__once)) {
		GType dp_sub_type_id;
		dp_sub_type_id = dp_sub_get_type_once ();
		g_once_init_leave (&dp_sub_type_id__once, dp_sub_type_id);
	}
	return dp_sub_type_id__once;
}

void
OnDataReceivedDP (DataPck* myObj,
                  const gchar* ch)
{
	FILE* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (myObj != NULL);
	g_return_if_fail (ch != NULL);
	_tmp0_ = stdout;
	_tmp1_ = protobuf_message_to_string ((ProtobufMessage*) myObj, "    ");
	_tmp2_ = _tmp1_;
	fprintf (_tmp0_, "\t\t\tDP Sub by callback %s: Msg received:\n{\n%s}\n", ch, _tmp2_);
	_g_free0 (_tmp2_);
}

