/* EPDef_aux.c generated by valac 0.56.0, the Vala compiler
 * generated from EPDef_aux.vala, do not modify */

#include <protocolbus.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <stdio.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_EP_SUB (ep_sub_get_type ())
#define EP_SUB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_EP_SUB, EPSub))
#define EP_SUB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_EP_SUB, EPSubClass))
#define IS_EP_SUB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_EP_SUB))
#define IS_EP_SUB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_EP_SUB))
#define EP_SUB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_EP_SUB, EPSubClass))

typedef struct _EPSub EPSub;
typedef struct _EPSubClass EPSubClass;
typedef struct _EPSubPrivate EPSubPrivate;
enum  {
	EP_SUB_0_PROPERTY,
	EP_SUB_NUM_PROPERTIES
};
static GParamSpec* ep_sub_properties[EP_SUB_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

struct _EPSub {
	ProtocolBusGSub parent_instance;
	EPSubPrivate * priv;
};

struct _EPSubClass {
	ProtocolBusGSubClass parent_class;
};

static gpointer ep_sub_parent_class = NULL;

VALA_EXTERN GType ep_sub_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EPSub, g_object_unref)
VALA_EXTERN EPSub* ep_sub_new (ProtocolBusDomain* domain,
                   const gchar* theChannel);
VALA_EXTERN EPSub* ep_sub_construct (GType object_type,
                         ProtocolBusDomain* domain,
                         const gchar* theChannel);
static void __lambda4__gh_func (gconstpointer key,
                         gconstpointer value,
                         gpointer self);
static void ep_sub_real_OnDataReceived (ProtocolBusGSub* base,
                                 ProtocolBusEndPointDef* myObj);
static GType ep_sub_get_type_once (void);
VALA_EXTERN void OnDataReceivedEP (ProtocolBusEndPointDef* myObj,
                       const gchar* ch);

static void
_lambda4_ (ProtocolBusGSub* self)
{
}

static void
__lambda4__gh_func (gconstpointer key,
                    gconstpointer value,
                    gpointer self)
{
	_lambda4_ ((ProtocolBusGSub*) self);
}

EPSub*
ep_sub_construct (GType object_type,
                  ProtocolBusDomain* domain,
                  const gchar* theChannel)
{
	EPSub * self = NULL;
	g_return_val_if_fail (domain != NULL, NULL);
	g_return_val_if_fail (theChannel != NULL, NULL);
	self = (EPSub*) protocol_bus_gsub_construct (object_type, PROTOCOL_BUS_TYPE_END_POINT_DEF, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, domain, theChannel, __lambda4__gh_func, self, TRUE);
	return self;
}

EPSub*
ep_sub_new (ProtocolBusDomain* domain,
            const gchar* theChannel)
{
	return ep_sub_construct (TYPE_EP_SUB, domain, theChannel);
}

static void
ep_sub_real_OnDataReceived (ProtocolBusGSub* base,
                            ProtocolBusEndPointDef* myObj)
{
	EPSub * self;
	FILE* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	self = (EPSub*) base;
	g_return_if_fail (myObj != NULL);
	_tmp0_ = stdout;
	_tmp1_ = protocol_bus_gsub_GetChannel ((ProtocolBusGSub*) self);
	_tmp2_ = _tmp1_;
	_tmp3_ = protobuf_message_to_string ((ProtobufMessage*) myObj, "    ");
	_tmp4_ = _tmp3_;
	fprintf (_tmp0_, "\t\t\tEP Sub by override %s: Msg received:\n{\n%s}\n", _tmp2_, _tmp4_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
}

static void
ep_sub_class_init (EPSubClass * klass,
                   gpointer klass_data)
{
	ep_sub_parent_class = g_type_class_peek_parent (klass);
	((ProtocolBusGSubClass *) klass)->OnDataReceived = (void (*) (ProtocolBusGSub*, gconstpointer)) ep_sub_real_OnDataReceived;
}

static void
ep_sub_instance_init (EPSub * self,
                      gpointer klass)
{
}

static GType
ep_sub_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (EPSubClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ep_sub_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EPSub), 0, (GInstanceInitFunc) ep_sub_instance_init, NULL };
	GType ep_sub_type_id;
	ep_sub_type_id = g_type_register_static (PROTOCOL_BUS_TYPE_GSUB, "EPSub", &g_define_type_info, 0);
	return ep_sub_type_id;
}

GType
ep_sub_get_type (void)
{
	static volatile gsize ep_sub_type_id__once = 0;
	if (g_once_init_enter (&ep_sub_type_id__once)) {
		GType ep_sub_type_id;
		ep_sub_type_id = ep_sub_get_type_once ();
		g_once_init_leave (&ep_sub_type_id__once, ep_sub_type_id);
	}
	return ep_sub_type_id__once;
}

void
OnDataReceivedEP (ProtocolBusEndPointDef* myObj,
                  const gchar* ch)
{
	FILE* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (myObj != NULL);
	g_return_if_fail (ch != NULL);
	_tmp0_ = stdout;
	_tmp1_ = protobuf_message_to_string ((ProtobufMessage*) myObj, "    ");
	_tmp2_ = _tmp1_;
	fprintf (_tmp0_, "\t\t\tEP Sub by callback %s: Msg received:\n{\n%s}\n", ch, _tmp2_);
	_g_free0 (_tmp2_);
}

