/* main.c generated by valac 0.56.0, the Vala compiler
 * generated from main.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <protocolbus.h>
#include <glib-object.h>
#include <stdio.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_DATA_PCK (data_pck_get_type ())
#define DATA_PCK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DATA_PCK, DataPck))
#define DATA_PCK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DATA_PCK, DataPckClass))
#define IS_DATA_PCK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DATA_PCK))
#define IS_DATA_PCK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DATA_PCK))
#define DATA_PCK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DATA_PCK, DataPckClass))

typedef struct _DataPck DataPck;
typedef struct _DataPckClass DataPckClass;
typedef struct _DataPckPrivate DataPckPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_DP_SUB (dp_sub_get_type ())
#define DP_SUB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DP_SUB, DPSub))
#define DP_SUB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DP_SUB, DPSubClass))
#define IS_DP_SUB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DP_SUB))
#define IS_DP_SUB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DP_SUB))
#define DP_SUB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DP_SUB, DPSubClass))

typedef struct _DPSub DPSub;
typedef struct _DPSubClass DPSubClass;

#define TYPE_EP_SUB (ep_sub_get_type ())
#define EP_SUB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_EP_SUB, EPSub))
#define EP_SUB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_EP_SUB, EPSubClass))
#define IS_EP_SUB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_EP_SUB))
#define IS_EP_SUB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_EP_SUB))
#define EP_SUB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_EP_SUB, EPSubClass))

typedef struct _EPSub EPSub;
typedef struct _EPSubClass EPSubClass;
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_byte_array_unref0(var) ((var == NULL) ? NULL : (var = (g_byte_array_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _protocol_bus_gpub_unref0(var) ((var == NULL) ? NULL : (var = (protocol_bus_gpub_unref (var), NULL)))

struct _DataPck {
	ProtobufMessage parent_instance;
	DataPckPrivate * priv;
	gchar* a;
	GByteArray* Data;
};

struct _DataPckClass {
	ProtobufMessageClass parent_class;
};

static gint _vala_main (gchar** args,
                 gint args_length1);
VALA_EXTERN GType data_pck_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DataPck, g_object_unref)
VALA_EXTERN DataPck* data_pck_new (void);
VALA_EXTERN DataPck* data_pck_construct (GType object_type);
VALA_EXTERN GType dp_sub_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DPSub, g_object_unref)
VALA_EXTERN DPSub* dp_sub_new (ProtocolBusDomain* domain,
                   const gchar* theChannel);
VALA_EXTERN DPSub* dp_sub_construct (GType object_type,
                         ProtocolBusDomain* domain,
                         const gchar* theChannel);
VALA_EXTERN GType ep_sub_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EPSub, g_object_unref)
VALA_EXTERN EPSub* ep_sub_new (ProtocolBusDomain* domain,
                   const gchar* theChannel);
VALA_EXTERN EPSub* ep_sub_construct (GType object_type,
                         ProtocolBusDomain* domain,
                         const gchar* theChannel);
VALA_EXTERN void OnDataReceivedDP (DataPck* myObj,
                       const gchar* ch);
static void _OnDataReceivedDP_gh_func (gconstpointer key,
                                gconstpointer value,
                                gpointer self);
VALA_EXTERN void OnDataReceivedEP (ProtocolBusEndPointDef* myObj,
                       const gchar* ch);
static void _OnDataReceivedEP_gh_func (gconstpointer key,
                                gconstpointer value,
                                gpointer self);
static guint8* _vala_array_dup1 (guint8* self,
                          gssize length);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

static void
_OnDataReceivedDP_gh_func (gconstpointer key,
                           gconstpointer value,
                           gpointer self)
{
	OnDataReceivedDP ((DataPck*) key, (const gchar*) value);
}

static void
_OnDataReceivedEP_gh_func (gconstpointer key,
                           gconstpointer value,
                           gpointer self)
{
	OnDataReceivedEP ((ProtocolBusEndPointDef*) key, (const gchar*) value);
}

static gchar*
g_file_stream_read_line (FILE* self)
{
	gint c = 0;
	GString* ret = NULL;
	GString* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	ret = NULL;
	while (TRUE) {
		GString* _tmp0_;
		GString* _tmp2_;
		c = fgetc (self);
		if (!(c != EOF)) {
			break;
		}
		_tmp0_ = ret;
		if (_tmp0_ == NULL) {
			GString* _tmp1_;
			_tmp1_ = g_string_new ("");
			_g_string_free0 (ret);
			ret = _tmp1_;
		}
		if (c == ((gint) '\n')) {
			break;
		}
		_tmp2_ = ret;
		g_string_append_c ((GString*) _tmp2_, (gchar) c);
	}
	_tmp3_ = ret;
	if (_tmp3_ == NULL) {
		result = NULL;
		_g_string_free0 (ret);
		return result;
	} else {
		GString* _tmp4_;
		const gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp4_ = ret;
		_tmp5_ = ((GString*) _tmp4_)->str;
		_tmp6_ = g_strdup (_tmp5_);
		result = _tmp6_;
		_g_string_free0 (ret);
		return result;
	}
}

static guint8*
_vala_array_dup1 (guint8* self,
                  gssize length)
{
	if (length > 0) {
		return _vala_memdup2 (self, length * sizeof (guint8));
	}
	return NULL;
}

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	ProtocolBusDomain* miaDom = NULL;
	ProtocolBusDomain* _tmp0_;
	DataPck* miaData1 = NULL;
	DataPck* _tmp1_;
	DataPck* _tmp2_;
	gchar* _tmp3_;
	ProtocolBusEndPointDef* miaData2 = NULL;
	ProtocolBusEndPointDef* _tmp4_;
	ProtocolBusEndPointDef* _tmp5_;
	gchar* _tmp6_;
	ProtocolBusEndPointDef* _tmp7_;
	ProtocolBusGPub* miaDataPkgPub = NULL;
	ProtocolBusDomain* _tmp8_;
	ProtocolBusGPub* _tmp9_;
	ProtocolBusGPub* miaEndPointPub = NULL;
	ProtocolBusDomain* _tmp10_;
	ProtocolBusGPub* _tmp11_;
	DPSub* miaDPSubDerv = NULL;
	ProtocolBusDomain* _tmp12_;
	DPSub* _tmp13_;
	EPSub* miaEPSubDerv = NULL;
	ProtocolBusDomain* _tmp14_;
	EPSub* _tmp15_;
	ProtocolBusGSub* miaDPSubCbck = NULL;
	ProtocolBusDomain* _tmp16_;
	ProtocolBusGSub* _tmp17_;
	ProtocolBusGSub* miaEPSubCbck = NULL;
	ProtocolBusDomain* _tmp18_;
	ProtocolBusGSub* _tmp19_;
	gchar* aux = NULL;
	gchar* _tmp20_;
	gint i = 0;
	ProtocolBusDomain* _tmp45_;
	FILE* _tmp46_;
	gint result;
	_tmp0_ = protocol_bus_domain_new (0);
	miaDom = _tmp0_;
	_tmp1_ = data_pck_new ();
	miaData1 = _tmp1_;
	_tmp2_ = miaData1;
	_tmp3_ = g_strdup ("_.::._");
	_g_free0 (_tmp2_->a);
	_tmp2_->a = _tmp3_;
	_tmp4_ = protocol_bus_end_point_def_new ();
	miaData2 = _tmp4_;
	_tmp5_ = miaData2;
	_tmp6_ = g_strdup ("__localhost__");
	_g_free0 (_tmp5_->Host);
	_tmp5_->Host = _tmp6_;
	_tmp7_ = miaData2;
	_tmp7_->Port = (gint32) 31;
	_tmp8_ = miaDom;
	_tmp9_ = protocol_bus_gpub_new (TYPE_DATA_PCK, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, _tmp8_);
	miaDataPkgPub = _tmp9_;
	_tmp10_ = miaDom;
	_tmp11_ = protocol_bus_gpub_new (PROTOCOL_BUS_TYPE_END_POINT_DEF, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, _tmp10_);
	miaEndPointPub = _tmp11_;
	_tmp12_ = miaDom;
	_tmp13_ = dp_sub_new (_tmp12_, "hola1");
	miaDPSubDerv = _tmp13_;
	_tmp14_ = miaDom;
	_tmp15_ = ep_sub_new (_tmp14_, "hola1");
	miaEPSubDerv = _tmp15_;
	_tmp16_ = miaDom;
	_tmp17_ = protocol_bus_gsub_new (TYPE_DATA_PCK, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, _tmp16_, "hola2", _OnDataReceivedDP_gh_func, NULL, TRUE);
	miaDPSubCbck = _tmp17_;
	_tmp18_ = miaDom;
	_tmp19_ = protocol_bus_gsub_new (PROTOCOL_BUS_TYPE_END_POINT_DEF, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, _tmp18_, "hola2", _OnDataReceivedEP_gh_func, NULL, TRUE);
	miaEPSubCbck = _tmp19_;
	_tmp20_ = g_strdup ("");
	aux = _tmp20_;
	i = 0;
	while (TRUE) {
		FILE* _tmp21_;
		gchar* _tmp22_;
		const gchar* _tmp23_;
		const gchar* _tmp24_;
		_tmp21_ = stdin;
		_tmp22_ = g_file_stream_read_line (_tmp21_);
		_g_free0 (aux);
		aux = _tmp22_;
		_tmp23_ = aux;
		if (!(g_strcmp0 (_tmp23_, "q") != 0)) {
			break;
		}
		_tmp24_ = aux;
		if (g_strcmp0 (_tmp24_, "m") == 0) {
			guint8* datoj1 = NULL;
			gint _tmp25_;
			guint8* _tmp26_;
			gint datoj1_length1;
			gint _datoj1_size_;
			DataPck* _tmp27_;
			guint8* _tmp28_;
			gint _tmp28__length1;
			guint8* _tmp29_;
			gint _tmp29__length1;
			GByteArray* _tmp30_;
			ProtocolBusGPub* _tmp31_;
			gchar* _tmp32_;
			gchar* _tmp33_;
			gchar** _tmp34_;
			gchar** _tmp35_;
			gint _tmp35__length1;
			DataPck* _tmp36_;
			ProtocolBusEndPointDef* _tmp37_;
			gint32 _tmp38_;
			ProtocolBusGPub* _tmp39_;
			gchar* _tmp40_;
			gchar* _tmp41_;
			gchar** _tmp42_;
			gchar** _tmp43_;
			gint _tmp43__length1;
			ProtocolBusEndPointDef* _tmp44_;
			_tmp25_ = i;
			i = _tmp25_ + 1;
			_tmp26_ = g_new0 (guint8, 5);
			_tmp26_[0] = (guint8) _tmp25_;
			_tmp26_[1] = (guint8) 2;
			_tmp26_[2] = (guint8) 3;
			_tmp26_[3] = (guint8) 4;
			_tmp26_[4] = (guint8) 5;
			datoj1 = _tmp26_;
			datoj1_length1 = 5;
			_datoj1_size_ = datoj1_length1;
			_tmp27_ = miaData1;
			_tmp28_ = datoj1;
			_tmp28__length1 = datoj1_length1;
			_tmp29_ = (_tmp28_ != NULL) ? _vala_array_dup1 (_tmp28_, _tmp28__length1) : _tmp28_;
			_tmp29__length1 = _tmp28__length1;
			_tmp30_ = g_byte_array_new_take (_tmp29_, _tmp29__length1);
			_g_byte_array_unref0 (_tmp27_->Data);
			_tmp27_->Data = _tmp30_;
			_tmp31_ = miaDataPkgPub;
			_tmp32_ = g_strdup ("hola1");
			_tmp33_ = g_strdup ("hola2");
			_tmp34_ = g_new0 (gchar*, 2 + 1);
			_tmp34_[0] = _tmp32_;
			_tmp34_[1] = _tmp33_;
			_tmp35_ = _tmp34_;
			_tmp35__length1 = 2;
			_tmp36_ = miaData1;
			protocol_bus_gpub_SendMsgToChannels (_tmp31_, _tmp35_, (gint) 2, _tmp36_);
			_tmp35_ = (_vala_array_free (_tmp35_, _tmp35__length1, (GDestroyNotify) g_free), NULL);
			_tmp37_ = miaData2;
			_tmp38_ = _tmp37_->Port;
			_tmp37_->Port = _tmp38_ + 1;
			_tmp39_ = miaEndPointPub;
			_tmp40_ = g_strdup ("hola1");
			_tmp41_ = g_strdup ("hola2");
			_tmp42_ = g_new0 (gchar*, 2 + 1);
			_tmp42_[0] = _tmp40_;
			_tmp42_[1] = _tmp41_;
			_tmp43_ = _tmp42_;
			_tmp43__length1 = 2;
			_tmp44_ = miaData2;
			protocol_bus_gpub_SendMsgToChannels (_tmp39_, _tmp43_, (gint) 2, _tmp44_);
			_tmp43_ = (_vala_array_free (_tmp43_, _tmp43__length1, (GDestroyNotify) g_free), NULL);
			datoj1 = (g_free (datoj1), NULL);
		}
	}
	_tmp45_ = miaDom;
	protocol_bus_domain_Close (_tmp45_);
	_tmp46_ = stdout;
	fprintf (_tmp46_, "fin...\n");
	result = 0;
	_g_free0 (aux);
	_g_object_unref0 (miaEPSubCbck);
	_g_object_unref0 (miaDPSubCbck);
	_g_object_unref0 (miaEPSubDerv);
	_g_object_unref0 (miaDPSubDerv);
	_protocol_bus_gpub_unref0 (miaEndPointPub);
	_protocol_bus_gpub_unref0 (miaDataPkgPub);
	_g_object_unref0 (miaData2);
	_g_object_unref0 (miaData1);
	_g_object_unref0 (miaDom);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
	if (mem && byte_size != 0) {
		new_mem = g_malloc (byte_size);
		memcpy (new_mem, mem, byte_size);
	} else {
		new_mem = NULL;
	}
	return new_mem;
}

