/* Ciphering.c generated by valac 0.56.0, the Vala compiler
 * generated from Ciphering.vala, do not modify */

#include "protocolbus.h"
#include <gcrypt.h>
#include <glib.h>
#include <string.h>
#include <stdlib.h>
#include <gobject/gvaluecollector.h>

#define _gcry_cipher_close0(var) ((var == NULL) ? NULL : (var = (gcry_cipher_close (var), NULL)))
#define _g_bytes_unref0(var) ((var == NULL) ? NULL : (var = (g_bytes_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ProtocolBusParamSpecCiphering ProtocolBusParamSpecCiphering;

struct _ProtocolBusCipheringPrivate {
	struct gcry_cipher_handle* cipher;
	GRecMutex __lock_cipher;
	guchar* blackbytes;
	gint blackbytes_length1;
	gint _blackbytes_size_;
	guchar* redbytes;
	gint redbytes_length1;
	gint _redbytes_size_;
};

struct _ProtocolBusParamSpecCiphering {
	GParamSpec parent_instance;
};

static gint ProtocolBusCiphering_private_offset;
static gpointer protocol_bus_ciphering_parent_class = NULL;

static guint8* _vala_array_dup1 (guint8* self,
                          gssize length);
static guint8* _vala_array_dup2 (guint8* self,
                          gssize length);
static guint32 protocol_bus_ciphering_GetFNV1aHashCode (const gchar* str);
static void protocol_bus_ciphering_finalize (ProtocolBusCiphering * obj);
static GType protocol_bus_ciphering_get_type_once (void);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

static inline gpointer
protocol_bus_ciphering_get_instance_private (ProtocolBusCiphering* self)
{
	return G_STRUCT_MEMBER_P (self, ProtocolBusCiphering_private_offset);
}

ProtocolBusCiphering*
protocol_bus_ciphering_construct (GType object_type,
                                  guchar* key,
                                  gint key_length1,
                                  guchar* iv,
                                  gint iv_length1)
{
	ProtocolBusCiphering* self = NULL;
	gcry_error_t err = 0U;
	struct gcry_cipher_handle* _tmp0_ = NULL;
	gcry_error_t _tmp1_;
	struct gcry_cipher_handle* _tmp2_;
	struct gcry_cipher_handle* _tmp3_;
	guchar* _tmp4_;
	guchar* _tmp5_;
#line 11 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self = (ProtocolBusCiphering*) g_type_create_instance (object_type);
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_tmp1_ = gcry_cipher_open (&_tmp0_, GCRY_CIPHER_AES256, GCRY_CIPHER_MODE_CBC, GCRY_CIPHER_SECURE);
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_gcry_cipher_close0 (self->priv->cipher);
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->cipher = _tmp0_;
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	err = _tmp1_;
#line 13 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_tmp2_ = self->priv->cipher;
#line 13 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	gcry_cipher_setkey (_tmp2_, key, (gint) key_length1);
#line 14 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_tmp3_ = self->priv->cipher;
#line 14 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	gcry_cipher_setiv (_tmp3_, iv, (gint) iv_length1);
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_tmp4_ = g_new0 (guchar, 64000);
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->blackbytes = (g_free (self->priv->blackbytes), NULL);
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->blackbytes = _tmp4_;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->blackbytes_length1 = 64000;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->_blackbytes_size_ = self->priv->blackbytes_length1;
#line 16 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_tmp5_ = g_new0 (guchar, 64000);
#line 16 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->redbytes = (g_free (self->priv->redbytes), NULL);
#line 16 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->redbytes = _tmp5_;
#line 16 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->redbytes_length1 = 64000;
#line 16 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->_redbytes_size_ = self->priv->redbytes_length1;
#line 11 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return self;
#line 106 "Ciphering.c"
}

ProtocolBusCiphering*
protocol_bus_ciphering_new (guchar* key,
                            gint key_length1,
                            guchar* iv,
                            gint iv_length1)
{
#line 11 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return protocol_bus_ciphering_construct (PROTOCOL_BUS_TYPE_CIPHERING, key, key_length1, iv, iv_length1);
#line 117 "Ciphering.c"
}

static gint
_vala_g_bytes_get_length (GBytes* self)
{
	gint result;
#line 5832 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 5834 "glib-2.0.vapi"
	result = (gint) g_bytes_get_size (self);
#line 5834 "glib-2.0.vapi"
	return result;
#line 130 "Ciphering.c"
}

static guint8*
_vala_array_dup1 (guint8* self,
                  gssize length)
{
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (length > 0) {
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 141 "Ciphering.c"
	}
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return NULL;
#line 145 "Ciphering.c"
}

GBytes*
protocol_bus_ciphering_Encrypt (ProtocolBusCiphering* self,
                                GBytes* RedBytes)
{
	GBytes* aux = NULL;
	GError* _inner_error0_ = NULL;
	GBytes* result;
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_return_val_if_fail (RedBytes != NULL, NULL);
#line 159 "Ciphering.c"
	{
		struct gcry_cipher_handle* _tmp0_;
#line 26 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		_tmp0_ = self->priv->cipher;
#line 26 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		g_rec_mutex_lock (&self->priv->__lock_cipher);
#line 166 "Ciphering.c"
		{
			gint out_length = 0;
			gint _tmp1_;
			gint _tmp2_;
			guchar* _tmp3_;
			gint _tmp3__length1;
			gsize _tmp4_ = 0;
			guint8* _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			guchar* _tmp8_;
			gint _tmp8__length1;
			gint _tmp9_;
			gint _tmp10_;
			gint _tmp11_;
			gint _tmp12_;
			gcry_error_t e = 0U;
			struct gcry_cipher_handle* _tmp13_;
			guchar* _tmp14_;
			gint _tmp14__length1;
			gsize _tmp15_ = 0;
			guint8* _tmp16_;
			guchar* _tmp17_;
			gint _tmp17__length1;
			guint8* _tmp18_;
			gint _tmp18__length1;
			GBytes* _tmp19_;
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp1_ = _vala_g_bytes_get_length (RedBytes);
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp2_ = _tmp1_;
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			out_length = ((_tmp2_ / 16) + 1) * 16;
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp3_ = self->priv->redbytes;
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp3__length1 = self->priv->redbytes_length1;
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp5_ = g_bytes_get_data (RedBytes, &_tmp4_);
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp6_ = _vala_g_bytes_get_length (RedBytes);
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp7_ = _tmp6_;
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			memcpy (_tmp3_, _tmp5_, (gsize) _tmp7_);
#line 29 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp8_ = self->priv->redbytes;
#line 29 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp8__length1 = self->priv->redbytes_length1;
#line 29 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp9_ = _vala_g_bytes_get_length (RedBytes);
#line 29 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp10_ = _tmp9_;
#line 29 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp11_ = _vala_g_bytes_get_length (RedBytes);
#line 29 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp12_ = _tmp11_;
#line 29 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			memset ((guchar*) (&_tmp8_[_tmp10_]), 0, (gsize) (out_length - _tmp12_));
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp13_ = self->priv->cipher;
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp14_ = self->priv->blackbytes;
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp14__length1 = self->priv->blackbytes_length1;
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp16_ = g_bytes_get_data (RedBytes, &_tmp15_);
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			e = gcry_cipher_encrypt (_tmp13_, _tmp14_, (gint) _tmp14__length1, _tmp16_, (gint) _tmp15_);
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp17_ = self->priv->blackbytes;
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp17__length1 = self->priv->blackbytes_length1;
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp18_ = (_tmp17_ != NULL) ? _vala_array_dup1 (_tmp17_ + 0, (out_length - 1) - 0) : _tmp17_;
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp18__length1 = (out_length - 1) - 0;
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp19_ = g_bytes_new_take (_tmp18_, _tmp18__length1);
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_g_bytes_unref0 (aux);
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			aux = _tmp19_;
#line 250 "Ciphering.c"
		}
		__finally0:
		{
			struct gcry_cipher_handle* _tmp20_;
#line 26 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp20_ = self->priv->cipher;
#line 26 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			g_rec_mutex_unlock (&self->priv->__lock_cipher);
#line 259 "Ciphering.c"
		}
#line 26 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 26 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_g_bytes_unref0 (aux);
#line 26 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 26 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			g_clear_error (&_inner_error0_);
#line 26 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			return NULL;
#line 271 "Ciphering.c"
		}
	}
#line 36 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	result = aux;
#line 36 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return result;
#line 278 "Ciphering.c"
}

static guint8*
_vala_array_dup2 (guint8* self,
                  gssize length)
{
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (length > 0) {
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 289 "Ciphering.c"
	}
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return NULL;
#line 293 "Ciphering.c"
}

GBytes*
protocol_bus_ciphering_Decrypt (ProtocolBusCiphering* self,
                                GBytes* BlackBytes)
{
	GBytes* aux = NULL;
	GError* _inner_error0_ = NULL;
	GBytes* result;
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_return_val_if_fail (BlackBytes != NULL, NULL);
#line 307 "Ciphering.c"
	{
		struct gcry_cipher_handle* _tmp0_;
#line 41 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		_tmp0_ = self->priv->cipher;
#line 41 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		g_rec_mutex_lock (&self->priv->__lock_cipher);
#line 314 "Ciphering.c"
		{
			gint len = 0;
			gint _tmp1_;
			gint _tmp2_;
			gcry_error_t e = 0U;
			struct gcry_cipher_handle* _tmp3_;
			guchar* _tmp4_;
			gint _tmp4__length1;
			gsize _tmp5_ = 0;
			guint8* _tmp6_;
			guchar* _tmp7_;
			gint _tmp7__length1;
			guint8* _tmp8_;
			gint _tmp8__length1;
			GBytes* _tmp9_;
#line 42 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp1_ = _vala_g_bytes_get_length (BlackBytes);
#line 42 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp2_ = _tmp1_;
#line 42 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			len = ((_tmp2_ / 16) + 1) * 16;
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp3_ = self->priv->cipher;
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp4_ = self->priv->redbytes;
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp4__length1 = self->priv->redbytes_length1;
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp6_ = g_bytes_get_data (BlackBytes, &_tmp5_);
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			e = gcry_cipher_decrypt (_tmp3_, _tmp4_, (gint) _tmp4__length1, _tmp6_, (gint) _tmp5_);
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp7_ = self->priv->redbytes;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp7__length1 = self->priv->redbytes_length1;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp8_ = (_tmp7_ != NULL) ? _vala_array_dup2 (_tmp7_ + 0, (len - 1) - 0) : _tmp7_;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp8__length1 = (len - 1) - 0;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp9_ = g_bytes_new_take (_tmp8_, _tmp8__length1);
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_g_bytes_unref0 (aux);
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			aux = _tmp9_;
#line 360 "Ciphering.c"
		}
		__finally0:
		{
			struct gcry_cipher_handle* _tmp10_;
#line 41 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp10_ = self->priv->cipher;
#line 41 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			g_rec_mutex_unlock (&self->priv->__lock_cipher);
#line 369 "Ciphering.c"
		}
#line 41 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 41 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_g_bytes_unref0 (aux);
#line 41 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 41 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			g_clear_error (&_inner_error0_);
#line 41 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			return NULL;
#line 381 "Ciphering.c"
		}
	}
#line 47 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	result = aux;
#line 47 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return result;
#line 388 "Ciphering.c"
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
#line 1447 "glib-2.0.vapi"
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
#line 1447 "glib-2.0.vapi"
	end = _tmp0_;
#line 1448 "glib-2.0.vapi"
	_tmp1_ = end;
#line 1448 "glib-2.0.vapi"
	if (_tmp1_ == NULL) {
#line 1449 "glib-2.0.vapi"
		result = maxlen;
#line 1449 "glib-2.0.vapi"
		return result;
#line 411 "Ciphering.c"
	} else {
		gchar* _tmp2_;
#line 1451 "glib-2.0.vapi"
		_tmp2_ = end;
#line 1451 "glib-2.0.vapi"
		result = (glong) (_tmp2_ - str);
#line 1451 "glib-2.0.vapi"
		return result;
#line 420 "Ciphering.c"
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
#line 1458 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1460 "glib-2.0.vapi"
	if (offset >= ((glong) 0)) {
#line 1460 "glib-2.0.vapi"
		_tmp0_ = len >= ((glong) 0);
#line 439 "Ciphering.c"
	} else {
#line 1460 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 443 "Ciphering.c"
	}
#line 1460 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1462 "glib-2.0.vapi"
		string_length = string_strnlen ((gchar*) self, offset + len);
#line 449 "Ciphering.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 1464 "glib-2.0.vapi"
		_tmp1_ = strlen (self);
#line 1464 "glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1464 "glib-2.0.vapi"
		string_length = (glong) _tmp2_;
#line 459 "Ciphering.c"
	}
#line 1467 "glib-2.0.vapi"
	if (offset < ((glong) 0)) {
#line 1468 "glib-2.0.vapi"
		offset = string_length + offset;
#line 1469 "glib-2.0.vapi"
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
#line 467 "Ciphering.c"
	} else {
#line 1471 "glib-2.0.vapi"
		g_return_val_if_fail (offset <= string_length, NULL);
#line 471 "Ciphering.c"
	}
#line 1473 "glib-2.0.vapi"
	if (len < ((glong) 0)) {
#line 1474 "glib-2.0.vapi"
		len = string_length - offset;
#line 477 "Ciphering.c"
	}
#line 1476 "glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
#line 1477 "glib-2.0.vapi"
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
#line 1477 "glib-2.0.vapi"
	result = _tmp3_;
#line 1477 "glib-2.0.vapi"
	return result;
#line 487 "Ciphering.c"
}

gulong
protocol_bus_ciphering_GetHash64 (const gchar* text)
{
	gulong hash = 0UL;
	gint size = 0;
	gint _tmp0_;
	gint _tmp1_;
	gulong result;
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_return_val_if_fail (text != NULL, 0UL);
#line 51 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	hash = (gulong) 0;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_tmp0_ = strlen (text);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_tmp1_ = _tmp0_;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	size = _tmp1_;
#line 54 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	switch (size) {
#line 54 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		case 0:
#line 512 "Ciphering.c"
		{
#line 56 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			hash = (gulong) 0;
#line 57 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			break;
#line 518 "Ciphering.c"
		}
#line 54 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		case 1:
#line 522 "Ciphering.c"
		{
#line 59 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			hash = (gulong) (g_str_hash (text) & 0x00000000FFFFFFFFLL);
#line 60 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			break;
#line 528 "Ciphering.c"
		}
		default:
		{
			gchar* s1 = NULL;
			gint _tmp2_;
			gint _tmp3_;
			gchar* _tmp4_;
			gchar* s2 = NULL;
			gint _tmp5_;
			gint _tmp6_;
			gchar* _tmp7_;
			guint32 _ms4b = 0U;
			const gchar* _tmp8_;
			guint8* ms4b = NULL;
			guint32 _ls4b = 0U;
			const gchar* _tmp9_;
			guint8* ls4b = NULL;
			guint8* _tmp10_;
			guint8 _tmp11_;
			guint8* _tmp12_;
			guint8 _tmp13_;
			guint8* _tmp14_;
			guint8 _tmp15_;
			guint8* _tmp16_;
			guint8 _tmp17_;
			guint8* _tmp18_;
			guint8 _tmp19_;
			guint8* _tmp20_;
			guint8 _tmp21_;
			guint8* _tmp22_;
			guint8 _tmp23_;
			guint8* _tmp24_;
			guint8 _tmp25_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp2_ = strlen (text);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp3_ = _tmp2_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp4_ = string_substring (text, (glong) 0, (glong) (_tmp3_ / 2));
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			s1 = _tmp4_;
#line 63 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp5_ = strlen (text);
#line 63 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp6_ = _tmp5_;
#line 63 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp7_ = string_substring (text, (glong) (_tmp6_ / 2), (glong) -1);
#line 63 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			s2 = _tmp7_;
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp8_ = s1;
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_ms4b = protocol_bus_ciphering_GetFNV1aHashCode (_tmp8_);
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			ms4b = (guint8*) (&_ms4b);
#line 66 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp9_ = s2;
#line 66 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_ls4b = protocol_bus_ciphering_GetFNV1aHashCode (_tmp9_);
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			ls4b = (guint8*) (&_ls4b);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp10_ = ms4b;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp11_ = _tmp10_[0];
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp12_ = ms4b;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp13_ = _tmp12_[1];
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp14_ = ms4b;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp15_ = _tmp14_[2];
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp16_ = ms4b;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp17_ = _tmp16_[3];
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp18_ = ls4b;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp19_ = _tmp18_[0];
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp20_ = ls4b;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp21_ = _tmp20_[1];
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp22_ = ls4b;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp23_ = _tmp22_[2];
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp24_ = ls4b;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp25_ = _tmp24_[3];
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			hash = (((((((((gulong) _tmp11_) << 56) | (((gulong) _tmp13_) << 48)) | (((gulong) _tmp15_) << 40)) | (((gulong) _tmp17_) << 32)) | (((gulong) _tmp19_) << 24)) | (((gulong) _tmp21_) << 16)) | (((gulong) _tmp23_) << 8)) | ((gulong) _tmp25_);
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_g_free0 (s2);
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_g_free0 (s1);
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			break;
#line 630 "Ciphering.c"
		}
	}
#line 75 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	result = hash;
#line 75 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return result;
#line 637 "Ciphering.c"
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
#line 1232 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, '\0');
#line 1233 "glib-2.0.vapi"
	_tmp0_ = ((gchar*) self)[index];
#line 1233 "glib-2.0.vapi"
	result = _tmp0_;
#line 1233 "glib-2.0.vapi"
	return result;
#line 654 "Ciphering.c"
}

static guint32
protocol_bus_ciphering_GetFNV1aHashCode (const gchar* str)
{
	gint length = 0;
	gint _tmp0_;
	gint _tmp1_;
	guint32 hash = 0U;
	guint32 result;
#line 78 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_return_val_if_fail (str != NULL, 0U);
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (str == NULL) {
#line 80 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		result = (guint32) 0;
#line 80 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		return result;
#line 673 "Ciphering.c"
	}
#line 82 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_tmp0_ = strlen (str);
#line 82 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_tmp1_ = _tmp0_;
#line 82 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	length = _tmp1_;
#line 83 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	hash = (guint32) 2166136261LL;
#line 683 "Ciphering.c"
	{
		gint i = 0;
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		i = 0;
#line 688 "Ciphering.c"
		{
			gboolean _tmp2_ = FALSE;
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			_tmp2_ = TRUE;
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			while (TRUE) {
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
				if (!_tmp2_) {
#line 697 "Ciphering.c"
					gint _tmp3_;
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
					_tmp3_ = i;
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
					i = _tmp3_ + 1;
#line 703 "Ciphering.c"
				}
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
				_tmp2_ = FALSE;
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
				if (!(i < length)) {
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
					break;
#line 711 "Ciphering.c"
				}
#line 86 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
				hash = (hash ^ string_get (str, (glong) i)) * 16777619;
#line 715 "Ciphering.c"
			}
		}
	}
#line 88 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	result = hash;
#line 88 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return result;
#line 723 "Ciphering.c"
}

static void
protocol_bus_value_ciphering_init (GValue* value)
{
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	value->data[0].v_pointer = NULL;
#line 731 "Ciphering.c"
}

static void
protocol_bus_value_ciphering_free_value (GValue* value)
{
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (value->data[0].v_pointer) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		protocol_bus_ciphering_unref (value->data[0].v_pointer);
#line 741 "Ciphering.c"
	}
}

static void
protocol_bus_value_ciphering_copy_value (const GValue* src_value,
                                         GValue* dest_value)
{
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (src_value->data[0].v_pointer) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		dest_value->data[0].v_pointer = protocol_bus_ciphering_ref (src_value->data[0].v_pointer);
#line 753 "Ciphering.c"
	} else {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		dest_value->data[0].v_pointer = NULL;
#line 757 "Ciphering.c"
	}
}

static gpointer
protocol_bus_value_ciphering_peek_pointer (const GValue* value)
{
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return value->data[0].v_pointer;
#line 766 "Ciphering.c"
}

static gchar*
protocol_bus_value_ciphering_collect_value (GValue* value,
                                            guint n_collect_values,
                                            GTypeCValue* collect_values,
                                            guint collect_flags)
{
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (collect_values[0].v_pointer) {
#line 777 "Ciphering.c"
		ProtocolBusCiphering * object;
		object = collect_values[0].v_pointer;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		if (object->parent_instance.g_class == NULL) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 784 "Ciphering.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 788 "Ciphering.c"
		}
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		value->data[0].v_pointer = protocol_bus_ciphering_ref (object);
#line 792 "Ciphering.c"
	} else {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		value->data[0].v_pointer = NULL;
#line 796 "Ciphering.c"
	}
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return NULL;
#line 800 "Ciphering.c"
}

static gchar*
protocol_bus_value_ciphering_lcopy_value (const GValue* value,
                                          guint n_collect_values,
                                          GTypeCValue* collect_values,
                                          guint collect_flags)
{
	ProtocolBusCiphering ** object_p;
	object_p = collect_values[0].v_pointer;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (!object_p) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 815 "Ciphering.c"
	}
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (!value->data[0].v_pointer) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		*object_p = NULL;
#line 821 "Ciphering.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		*object_p = value->data[0].v_pointer;
#line 825 "Ciphering.c"
	} else {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		*object_p = protocol_bus_ciphering_ref (value->data[0].v_pointer);
#line 829 "Ciphering.c"
	}
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return NULL;
#line 833 "Ciphering.c"
}

GParamSpec*
protocol_bus_param_spec_ciphering (const gchar* name,
                                   const gchar* nick,
                                   const gchar* blurb,
                                   GType object_type,
                                   GParamFlags flags)
{
	ProtocolBusParamSpecCiphering* spec;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_return_val_if_fail (g_type_is_a (object_type, PROTOCOL_BUS_TYPE_CIPHERING), NULL);
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return G_PARAM_SPEC (spec);
#line 852 "Ciphering.c"
}

gpointer
protocol_bus_value_get_ciphering (const GValue* value)
{
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PROTOCOL_BUS_TYPE_CIPHERING), NULL);
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return value->data[0].v_pointer;
#line 862 "Ciphering.c"
}

void
protocol_bus_value_set_ciphering (GValue* value,
                                  gpointer v_object)
{
	ProtocolBusCiphering * old;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PROTOCOL_BUS_TYPE_CIPHERING));
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	old = value->data[0].v_pointer;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (v_object) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PROTOCOL_BUS_TYPE_CIPHERING));
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		value->data[0].v_pointer = v_object;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		protocol_bus_ciphering_ref (value->data[0].v_pointer);
#line 884 "Ciphering.c"
	} else {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		value->data[0].v_pointer = NULL;
#line 888 "Ciphering.c"
	}
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (old) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		protocol_bus_ciphering_unref (old);
#line 894 "Ciphering.c"
	}
}

void
protocol_bus_value_take_ciphering (GValue* value,
                                   gpointer v_object)
{
	ProtocolBusCiphering * old;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PROTOCOL_BUS_TYPE_CIPHERING));
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	old = value->data[0].v_pointer;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (v_object) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PROTOCOL_BUS_TYPE_CIPHERING));
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		value->data[0].v_pointer = v_object;
#line 915 "Ciphering.c"
	} else {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		value->data[0].v_pointer = NULL;
#line 919 "Ciphering.c"
	}
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (old) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		protocol_bus_ciphering_unref (old);
#line 925 "Ciphering.c"
	}
}

static void
protocol_bus_ciphering_class_init (ProtocolBusCipheringClass * klass,
                                   gpointer klass_data)
{
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	protocol_bus_ciphering_parent_class = g_type_class_peek_parent (klass);
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	((ProtocolBusCipheringClass *) klass)->finalize = protocol_bus_ciphering_finalize;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_type_class_adjust_private_offset (klass, &ProtocolBusCiphering_private_offset);
#line 939 "Ciphering.c"
}

static void
protocol_bus_ciphering_instance_init (ProtocolBusCiphering * self,
                                      gpointer klass)
{
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv = protocol_bus_ciphering_get_instance_private (self);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_rec_mutex_init (&self->priv->__lock_cipher);
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->ref_count = 1;
#line 952 "Ciphering.c"
}

static void
protocol_bus_ciphering_finalize (ProtocolBusCiphering * obj)
{
	ProtocolBusCiphering * self;
	struct gcry_cipher_handle* _tmp0_;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PROTOCOL_BUS_TYPE_CIPHERING, ProtocolBusCiphering);
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_signal_handlers_destroy (self);
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_tmp0_ = self->priv->cipher;
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	gcry_cipher_close (_tmp0_);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_rec_mutex_clear (&self->priv->__lock_cipher);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	_gcry_cipher_close0 (self->priv->cipher);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->blackbytes = (g_free (self->priv->blackbytes), NULL);
#line 9 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	self->priv->redbytes = (g_free (self->priv->redbytes), NULL);
#line 976 "Ciphering.c"
}

static GType
protocol_bus_ciphering_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { protocol_bus_value_ciphering_init, protocol_bus_value_ciphering_free_value, protocol_bus_value_ciphering_copy_value, protocol_bus_value_ciphering_peek_pointer, "p", protocol_bus_value_ciphering_collect_value, "p", protocol_bus_value_ciphering_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (ProtocolBusCipheringClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) protocol_bus_ciphering_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ProtocolBusCiphering), 0, (GInstanceInitFunc) protocol_bus_ciphering_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType protocol_bus_ciphering_type_id;
	protocol_bus_ciphering_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ProtocolBusCiphering", &g_define_type_info, &g_define_type_fundamental_info, 0);
	ProtocolBusCiphering_private_offset = g_type_add_instance_private (protocol_bus_ciphering_type_id, sizeof (ProtocolBusCipheringPrivate));
	return protocol_bus_ciphering_type_id;
}

GType
protocol_bus_ciphering_get_type (void)
{
	static volatile gsize protocol_bus_ciphering_type_id__once = 0;
	if (g_once_init_enter (&protocol_bus_ciphering_type_id__once)) {
		GType protocol_bus_ciphering_type_id;
		protocol_bus_ciphering_type_id = protocol_bus_ciphering_get_type_once ();
		g_once_init_leave (&protocol_bus_ciphering_type_id__once, protocol_bus_ciphering_type_id);
	}
	return protocol_bus_ciphering_type_id__once;
}

gpointer
protocol_bus_ciphering_ref (gpointer instance)
{
	ProtocolBusCiphering * self;
	self = instance;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	g_atomic_int_inc (&self->ref_count);
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	return instance;
#line 1012 "Ciphering.c"
}

void
protocol_bus_ciphering_unref (gpointer instance)
{
	ProtocolBusCiphering * self;
	self = instance;
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		PROTOCOL_BUS_CIPHERING_GET_CLASS (self)->finalize (self);
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/Ciphering.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1026 "Ciphering.c"
	}
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
	if (mem && byte_size != 0) {
		new_mem = g_malloc (byte_size);
		memcpy (new_mem, mem, byte_size);
	} else {
		new_mem = NULL;
	}
	return new_mem;
}

