/* GenericsPubSub.c generated by valac 0.56.0, the Vala compiler
 * generated from GenericsPubSub.vala, do not modify */

#include "protocolbus.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <gobject/gvaluecollector.h>

#define PROTOCOL_BUS_TYPE_DOMAIN (protocol_bus_domain_get_type ())
#define PROTOCOL_BUS_DOMAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_DOMAIN, ProtocolBusDomain))
#define PROTOCOL_BUS_DOMAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_DOMAIN, ProtocolBusDomainClass))
#define PROTOCOL_BUS_IS_DOMAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_DOMAIN))
#define PROTOCOL_BUS_IS_DOMAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_DOMAIN))
#define PROTOCOL_BUS_DOMAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_DOMAIN, ProtocolBusDomainClass))

typedef struct _ProtocolBusDomain ProtocolBusDomain;
typedef struct _ProtocolBusDomainClass ProtocolBusDomainClass;
enum  {
	PROTOCOL_BUS_GSUB_0_PROPERTY,
	PROTOCOL_BUS_GSUB_THETYPE_TYPE,
	PROTOCOL_BUS_GSUB_THETYPE_DUP_FUNC,
	PROTOCOL_BUS_GSUB_THETYPE_DESTROY_FUNC,
	PROTOCOL_BUS_GSUB_NUM_PROPERTIES
};
static GParamSpec* protocol_bus_gsub_properties[PROTOCOL_BUS_GSUB_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _protobuf_decode_buffer_unref0(var) ((var == NULL) ? NULL : (var = (protobuf_decode_buffer_unref (var), NULL)))
#define _g_byte_array_unref0(var) ((var == NULL) ? NULL : (var = (g_byte_array_unref (var), NULL)))
#define _protobuf_encode_buffer_unref0(var) ((var == NULL) ? NULL : (var = (protobuf_encode_buffer_unref (var), NULL)))
typedef struct _ProtocolBusParamSpecGPub ProtocolBusParamSpecGPub;

struct _ProtocolBusGSubPrivate {
	GType thetype_type;
	GBoxedCopyFunc thetype_dup_func;
	GDestroyNotify thetype_destroy_func;
	gchar* myChannel;
	guint64 myTypeName;
	ProtocolBusDomain* myDomain;
	GHFunc theCallback;
	gpointer theCallback_target;
	GDestroyNotify theCallback_target_destroy_notify;
};

struct _ProtocolBusGPubPrivate {
	GType thetype_type;
	GBoxedCopyFunc thetype_dup_func;
	GDestroyNotify thetype_destroy_func;
	ProtocolBusDomain* myDomain;
};

struct _ProtocolBusParamSpecGPub {
	GParamSpec parent_instance;
};

static gint ProtocolBusGSub_private_offset;
static gpointer protocol_bus_gsub_parent_class = NULL;
static gint protocol_bus_gsub_n;
static gint protocol_bus_gsub_n = 0;
static gint ProtocolBusGPub_private_offset;
static gpointer protocol_bus_gpub_parent_class = NULL;

VALA_EXTERN GType protocol_bus_domain_get_type (void) G_GNUC_CONST ;
static void protocol_bus_gsub_real_DispatchMsg (ProtocolBusQueueMgr* base,
                                         GeeArrayList* msgList);
static void protocol_bus_gsub_real_OnDataReceived (ProtocolBusGSub* self,
                                            gconstpointer myObj);
static void protocol_bus_gsub_finalize (GObject * obj);
static GType protocol_bus_gsub_get_type_once (void);
static void _vala_protocol_bus_gsub_get_property (GObject * object,
                                           guint property_id,
                                           GValue * value,
                                           GParamSpec * pspec);
static void _vala_protocol_bus_gsub_set_property (GObject * object,
                                           guint property_id,
                                           const GValue * value,
                                           GParamSpec * pspec);
static guint8* _vala_array_dup3 (guint8* self,
                          gssize length);
static void protocol_bus_gpub_finalize (ProtocolBusGPub * obj);
static GType protocol_bus_gpub_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

static inline gpointer
protocol_bus_gsub_get_instance_private (ProtocolBusGSub* self)
{
	return G_STRUCT_MEMBER_P (self, ProtocolBusGSub_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return self ? g_object_ref (self) : NULL;
#line 106 "GenericsPubSub.c"
}

ProtocolBusGSub*
protocol_bus_gsub_construct (GType object_type,
                             GType thetype_type,
                             GBoxedCopyFunc thetype_dup_func,
                             GDestroyNotify thetype_destroy_func,
                             ProtocolBusDomain* theDomain,
                             const gchar* theChannel,
                             GHFunc fnDataReceive,
                             gpointer fnDataReceive_target,
                             gboolean started)
{
	ProtocolBusGSub * self = NULL;
	gboolean _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gint _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	ProtocolBusDomain* _tmp9_;
	gchar* _tmp10_;
	ProtocolBusDomain* _tmp11_;
	const gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	const gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
#line 16 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_val_if_fail (theDomain != NULL, NULL);
#line 16 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_val_if_fail (theChannel != NULL, NULL);
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp0_ = started;
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp1_ = g_type_name (thetype_type);
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp2_ = g_strconcat (_tmp1_, "_S", NULL);
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp3_ = _tmp2_;
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp4_ = protocol_bus_gsub_n;
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	protocol_bus_gsub_n = _tmp4_ + 1;
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp5_ = g_strdup_printf ("%i", _tmp4_);
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp6_ = _tmp5_;
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp7_ = g_strconcat (_tmp3_, _tmp6_, NULL);
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp8_ = _tmp7_;
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self = (ProtocolBusGSub*) protocol_bus_queue_mgr_construct_Started (object_type, _tmp0_, _tmp8_);
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->thetype_type = thetype_type;
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->thetype_dup_func = thetype_dup_func;
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->thetype_destroy_func = thetype_destroy_func;
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (_tmp8_);
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (_tmp6_);
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (_tmp3_);
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp9_ = _g_object_ref0 (theDomain);
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_object_unref0 (self->priv->myDomain);
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->myDomain = _tmp9_;
#line 21 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp10_ = g_strdup (theChannel);
#line 21 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (self->priv->myChannel);
#line 21 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->myChannel = _tmp10_;
#line 22 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp11_ = self->priv->myDomain;
#line 22 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp12_ = self->priv->myChannel;
#line 22 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	protocol_bus_domain_RegisterSubscriber (_tmp11_, (ProtocolBusQueueMgr*) self, _tmp12_);
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp13_ = g_strdup_printf ("%i", protocol_bus_domain_GetDomainId (theDomain));
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp14_ = _tmp13_;
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp15_ = g_strconcat (_tmp14_, "//", NULL);
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp16_ = _tmp15_;
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp17_ = g_type_name (thetype_type);
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp18_ = g_strconcat (_tmp16_, _tmp17_, NULL);
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp19_ = _tmp18_;
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->myTypeName = (guint64) protocol_bus_ciphering_GetHash64 (_tmp19_);
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (_tmp19_);
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (_tmp16_);
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (_tmp14_);
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	(self->priv->theCallback_target_destroy_notify == NULL) ? NULL : (self->priv->theCallback_target_destroy_notify (self->priv->theCallback_target), NULL);
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->theCallback = NULL;
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->theCallback_target = NULL;
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->theCallback_target_destroy_notify = NULL;
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->theCallback = fnDataReceive;
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->theCallback_target = fnDataReceive_target;
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->theCallback_target_destroy_notify = NULL;
#line 16 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return self;
#line 235 "GenericsPubSub.c"
}

ProtocolBusGSub*
protocol_bus_gsub_new (GType thetype_type,
                       GBoxedCopyFunc thetype_dup_func,
                       GDestroyNotify thetype_destroy_func,
                       ProtocolBusDomain* theDomain,
                       const gchar* theChannel,
                       GHFunc fnDataReceive,
                       gpointer fnDataReceive_target,
                       gboolean started)
{
#line 16 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return protocol_bus_gsub_construct (PROTOCOL_BUS_TYPE_GSUB, thetype_type, thetype_dup_func, thetype_destroy_func, theDomain, theChannel, fnDataReceive, fnDataReceive_target, started);
#line 250 "GenericsPubSub.c"
}

static void
protocol_bus_gsub_real_DispatchMsg (ProtocolBusQueueMgr* base,
                                    GeeArrayList* msgList)
{
	ProtocolBusGSub * self;
#line 30 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self = (ProtocolBusGSub*) base;
#line 30 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_if_fail (msgList != NULL);
#line 262 "GenericsPubSub.c"
	{
		GeeArrayList* _myMsg_list = NULL;
		gint _myMsg_size = 0;
		GeeArrayList* _tmp0_;
		gint _tmp1_;
		gint _tmp2_;
		gint _myMsg_index = 0;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		_myMsg_list = msgList;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		_tmp0_ = _myMsg_list;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		_tmp1_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp0_);
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		_tmp2_ = _tmp1_;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		_myMsg_size = _tmp2_;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		_myMsg_index = -1;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		while (TRUE) {
#line 284 "GenericsPubSub.c"
			gint _tmp3_;
			gint _tmp4_;
			ProtocolBusMsg* myMsg = NULL;
			GeeArrayList* _tmp5_;
			gpointer _tmp6_;
			ProtocolBusMsg* _tmp7_;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			_myMsg_index = _myMsg_index + 1;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			_tmp3_ = _myMsg_index;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			_tmp4_ = _myMsg_size;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			if (!(_tmp3_ < _tmp4_)) {
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				break;
#line 301 "GenericsPubSub.c"
			}
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			_tmp5_ = _myMsg_list;
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			_tmp6_ = gee_abstract_list_get ((GeeAbstractList*) _tmp5_, _myMsg_index);
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			myMsg = (ProtocolBusMsg*) _tmp6_;
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			_tmp7_ = myMsg;
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			if (_tmp7_->msgType == self->priv->myTypeName) {
#line 313 "GenericsPubSub.c"
				ProtobufDecodeBuffer* decBuffer = NULL;
				ProtocolBusMsg* _tmp8_;
				GByteArray* _tmp9_;
				guint8* _tmp10_;
				gint _tmp10__length1;
				ProtobufDecodeBuffer* _tmp11_;
				gpointer myDataObj = NULL;
				GObject* _tmp12_;
				GObject* _tmp13_;
				gconstpointer _tmp14_;
				ProtobufDecodeBuffer* _tmp15_;
				GHFunc _tmp16_;
				gpointer _tmp16__target;
				gconstpointer _tmp17_;
				gchar* _tmp18_;
				gchar* _tmp19_;
				gconstpointer _tmp20_;
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp8_ = myMsg;
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp9_ = _tmp8_->payLoad;
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp10_ = _tmp9_->data;
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp10__length1 = _tmp9_->len;
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp11_ = protobuf_decode_buffer_new (_tmp10_, _tmp10__length1, (gsize) 0, (gssize) -1);
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				decBuffer = _tmp11_;
#line 34 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp12_ = g_object_new (self->priv->thetype_type, NULL);
#line 34 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp13_ = G_IS_INITIALLY_UNOWNED (_tmp12_) ? g_object_ref_sink (_tmp12_) : _tmp12_;
#line 34 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				myDataObj = (gpointer) _tmp13_;
#line 35 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp14_ = myDataObj;
#line 35 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp15_ = decBuffer;
#line 35 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				protobuf_message_decode (PROTOBUF_IS_MESSAGE (_tmp14_) ? ((ProtobufMessage*) _tmp14_) : NULL, _tmp15_, (gssize) -1);
#line 38 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp16_ = self->priv->theCallback;
#line 38 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp16__target = self->priv->theCallback_target;
#line 38 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp17_ = myDataObj;
#line 38 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp18_ = protocol_bus_gsub_GetChannel (self);
#line 38 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp19_ = _tmp18_;
#line 38 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp16_ (_tmp17_, _tmp19_, _tmp16__target);
#line 38 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_g_free0 (_tmp19_);
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp20_ = myDataObj;
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				protocol_bus_gsub_OnDataReceived (self, _tmp20_);
#line 34 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				((myDataObj == NULL) || (self->priv->thetype_destroy_func == NULL)) ? NULL : (myDataObj = (self->priv->thetype_destroy_func (myDataObj), NULL));
#line 34 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_protobuf_decode_buffer_unref0 (decBuffer);
#line 377 "GenericsPubSub.c"
			}
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			_g_object_unref0 (myMsg);
#line 381 "GenericsPubSub.c"
		}
	}
#line 42 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return;
#line 386 "GenericsPubSub.c"
}

gchar*
protocol_bus_gsub_GetChannel (ProtocolBusGSub* self)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* result;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp0_ = self->priv->myChannel;
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	result = _tmp1_;
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return result;
#line 405 "GenericsPubSub.c"
}

static void
protocol_bus_gsub_real_OnDataReceived (ProtocolBusGSub* self,
                                       gconstpointer myObj)
{
}

void
protocol_bus_gsub_OnDataReceived (ProtocolBusGSub* self,
                                  gconstpointer myObj)
{
	ProtocolBusGSubClass* _klass_;
#line 49 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_if_fail (self != NULL);
#line 49 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_klass_ = PROTOCOL_BUS_GSUB_GET_CLASS (self);
#line 49 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (_klass_->OnDataReceived) {
#line 49 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		_klass_->OnDataReceived (self, myObj);
#line 427 "GenericsPubSub.c"
	}
}

static void
protocol_bus_gsub_class_init (ProtocolBusGSubClass * klass,
                              gpointer klass_data)
{
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	protocol_bus_gsub_parent_class = g_type_class_peek_parent (klass);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_type_class_adjust_private_offset (klass, &ProtocolBusGSub_private_offset);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	((ProtocolBusQueueMgrClass *) klass)->DispatchMsg = (void (*) (ProtocolBusQueueMgr*, GeeArrayList*)) protocol_bus_gsub_real_DispatchMsg;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	((ProtocolBusGSubClass *) klass)->OnDataReceived = (void (*) (ProtocolBusGSub*, gconstpointer)) protocol_bus_gsub_real_OnDataReceived;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_protocol_bus_gsub_get_property;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_protocol_bus_gsub_set_property;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	G_OBJECT_CLASS (klass)->finalize = protocol_bus_gsub_finalize;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), PROTOCOL_BUS_GSUB_THETYPE_TYPE, g_param_spec_gtype ("thetype-type", "type", "type", G_TYPE_NONE, G_PARAM_STATIC_STRINGS | G_PARAM_READWRITE | G_PARAM_CONSTRUCT_ONLY));
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), PROTOCOL_BUS_GSUB_THETYPE_DUP_FUNC, g_param_spec_pointer ("thetype-dup-func", "dup func", "dup func", G_PARAM_STATIC_STRINGS | G_PARAM_READWRITE | G_PARAM_CONSTRUCT_ONLY));
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), PROTOCOL_BUS_GSUB_THETYPE_DESTROY_FUNC, g_param_spec_pointer ("thetype-destroy-func", "destroy func", "destroy func", G_PARAM_STATIC_STRINGS | G_PARAM_READWRITE | G_PARAM_CONSTRUCT_ONLY));
#line 455 "GenericsPubSub.c"
}

static void
protocol_bus_gsub_instance_init (ProtocolBusGSub * self,
                                 gpointer klass)
{
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv = protocol_bus_gsub_get_instance_private (self);
#line 464 "GenericsPubSub.c"
}

static void
protocol_bus_gsub_finalize (GObject * obj)
{
	ProtocolBusGSub * self;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PROTOCOL_BUS_TYPE_GSUB, ProtocolBusGSub);
#line 10 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (self->priv->myChannel);
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_object_unref0 (self->priv->myDomain);
#line 14 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	(self->priv->theCallback_target_destroy_notify == NULL) ? NULL : (self->priv->theCallback_target_destroy_notify (self->priv->theCallback_target), NULL);
#line 14 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->theCallback = NULL;
#line 14 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->theCallback_target = NULL;
#line 14 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->theCallback_target_destroy_notify = NULL;
#line 30 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	G_OBJECT_CLASS (protocol_bus_gsub_parent_class)->finalize (obj);
#line 487 "GenericsPubSub.c"
}

static GType
protocol_bus_gsub_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ProtocolBusGSubClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) protocol_bus_gsub_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ProtocolBusGSub), 0, (GInstanceInitFunc) protocol_bus_gsub_instance_init, NULL };
	GType protocol_bus_gsub_type_id;
	protocol_bus_gsub_type_id = g_type_register_static (PROTOCOL_BUS_TYPE_QUEUE_MGR, "ProtocolBusGSub", &g_define_type_info, 0);
	ProtocolBusGSub_private_offset = g_type_add_instance_private (protocol_bus_gsub_type_id, sizeof (ProtocolBusGSubPrivate));
	return protocol_bus_gsub_type_id;
}

GType
protocol_bus_gsub_get_type (void)
{
	static volatile gsize protocol_bus_gsub_type_id__once = 0;
	if (g_once_init_enter (&protocol_bus_gsub_type_id__once)) {
		GType protocol_bus_gsub_type_id;
		protocol_bus_gsub_type_id = protocol_bus_gsub_get_type_once ();
		g_once_init_leave (&protocol_bus_gsub_type_id__once, protocol_bus_gsub_type_id);
	}
	return protocol_bus_gsub_type_id__once;
}

static void
_vala_protocol_bus_gsub_get_property (GObject * object,
                                      guint property_id,
                                      GValue * value,
                                      GParamSpec * pspec)
{
	ProtocolBusGSub * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, PROTOCOL_BUS_TYPE_GSUB, ProtocolBusGSub);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	switch (property_id) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		case PROTOCOL_BUS_GSUB_THETYPE_TYPE:
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		g_value_set_gtype (value, self->priv->thetype_type);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		break;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		case PROTOCOL_BUS_GSUB_THETYPE_DUP_FUNC:
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		g_value_set_pointer (value, self->priv->thetype_dup_func);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		break;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		case PROTOCOL_BUS_GSUB_THETYPE_DESTROY_FUNC:
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		g_value_set_pointer (value, self->priv->thetype_destroy_func);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		break;
#line 540 "GenericsPubSub.c"
		default:
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		break;
#line 546 "GenericsPubSub.c"
	}
}

static void
_vala_protocol_bus_gsub_set_property (GObject * object,
                                      guint property_id,
                                      const GValue * value,
                                      GParamSpec * pspec)
{
	ProtocolBusGSub * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, PROTOCOL_BUS_TYPE_GSUB, ProtocolBusGSub);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	switch (property_id) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		case PROTOCOL_BUS_GSUB_THETYPE_TYPE:
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		self->priv->thetype_type = g_value_get_gtype (value);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		break;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		case PROTOCOL_BUS_GSUB_THETYPE_DUP_FUNC:
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		self->priv->thetype_dup_func = g_value_get_pointer (value);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		break;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		case PROTOCOL_BUS_GSUB_THETYPE_DESTROY_FUNC:
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		self->priv->thetype_destroy_func = g_value_get_pointer (value);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		break;
#line 578 "GenericsPubSub.c"
		default:
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		break;
#line 584 "GenericsPubSub.c"
	}
}

static inline gpointer
protocol_bus_gpub_get_instance_private (ProtocolBusGPub* self)
{
	return G_STRUCT_MEMBER_P (self, ProtocolBusGPub_private_offset);
}

ProtocolBusGPub*
protocol_bus_gpub_construct (GType object_type,
                             GType thetype_type,
                             GBoxedCopyFunc thetype_dup_func,
                             GDestroyNotify thetype_destroy_func,
                             ProtocolBusDomain* theDomain)
{
	ProtocolBusGPub* self = NULL;
	ProtocolBusDomain* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
#line 56 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_val_if_fail (theDomain != NULL, NULL);
#line 56 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self = (ProtocolBusGPub*) g_type_create_instance (object_type);
#line 56 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->thetype_type = thetype_type;
#line 56 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->thetype_dup_func = thetype_dup_func;
#line 56 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->thetype_destroy_func = thetype_destroy_func;
#line 57 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp0_ = _g_object_ref0 (theDomain);
#line 57 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_object_unref0 (self->priv->myDomain);
#line 57 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv->myDomain = _tmp0_;
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp1_ = g_strdup_printf ("%i", protocol_bus_domain_GetDomainId (theDomain));
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp2_ = _tmp1_;
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp3_ = g_strconcat (_tmp2_, "//", NULL);
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp4_ = _tmp3_;
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp5_ = g_type_name (thetype_type);
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp6_ = g_strconcat (_tmp4_, _tmp5_, NULL);
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp7_ = _tmp6_;
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->myTypeName = (guint64) protocol_bus_ciphering_GetHash64 (_tmp7_);
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (_tmp7_);
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (_tmp4_);
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_free0 (_tmp2_);
#line 56 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return self;
#line 650 "GenericsPubSub.c"
}

ProtocolBusGPub*
protocol_bus_gpub_new (GType thetype_type,
                       GBoxedCopyFunc thetype_dup_func,
                       GDestroyNotify thetype_destroy_func,
                       ProtocolBusDomain* theDomain)
{
#line 56 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return protocol_bus_gpub_construct (PROTOCOL_BUS_TYPE_GPUB, thetype_type, thetype_dup_func, thetype_destroy_func, theDomain);
#line 661 "GenericsPubSub.c"
}

static guint8*
_vala_array_dup3 (guint8* self,
                  gssize length)
{
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (length > 0) {
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 672 "GenericsPubSub.c"
	}
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return NULL;
#line 676 "GenericsPubSub.c"
}

void
protocol_bus_gpub_SendMsgToChannels (ProtocolBusGPub* self,
                                     gchar** channels,
                                     gint channels_length1,
                                     gconstpointer myObj)
{
	ProtocolBusMsg* myMsg = NULL;
	ProtocolBusMsg* _tmp0_;
	ProtocolBusMsg* _tmp5_;
	ProtobufEncodeBuffer* encBuffer = NULL;
	ProtobufEncodeBuffer* _tmp6_;
	ProtobufMessage* aux = NULL;
	ProtobufMessage* _tmp7_;
	ProtocolBusMsg* _tmp8_;
	guint8* _tmp9_;
	gint _tmp9__length1;
	gint _tmp10_ = 0;
	guint8* _tmp11_;
	gint _tmp11__length1;
	guint8* _tmp12_;
	gint _tmp12__length1;
	GByteArray* _tmp13_;
	ProtocolBusDomain* _tmp14_;
	ProtocolBusMsg* _tmp15_;
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_if_fail (self != NULL);
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp0_ = protocol_bus_msg_new ();
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	myMsg = _tmp0_;
#line 709 "GenericsPubSub.c"
	{
		gchar** ch_collection = NULL;
		gint ch_collection_length1 = 0;
		gint _ch_collection_size_ = 0;
		gint ch_it = 0;
#line 66 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		ch_collection = channels;
#line 66 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		ch_collection_length1 = channels_length1;
#line 66 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		for (ch_it = 0; ch_it < ch_collection_length1; ch_it = ch_it + 1) {
#line 721 "GenericsPubSub.c"
			gchar* _tmp1_;
			gchar* ch = NULL;
#line 66 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			_tmp1_ = g_strdup (ch_collection[ch_it]);
#line 66 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			ch = _tmp1_;
#line 728 "GenericsPubSub.c"
			{
				ProtocolBusMsg* _tmp2_;
				const gchar* _tmp3_;
				gchar* _tmp4_;
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp2_ = myMsg;
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp3_ = ch;
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp4_ = g_strdup (_tmp3_);
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_tmp2_->channels = g_list_append (_tmp2_->channels, _tmp4_);
#line 66 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				_g_free0 (ch);
#line 743 "GenericsPubSub.c"
			}
		}
	}
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp5_ = myMsg;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp5_->msgType = self->myTypeName;
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp6_ = protobuf_encode_buffer_new ((gsize) 1024);
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	encBuffer = _tmp6_;
#line 70 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp7_ = _g_object_ref0 (PROTOBUF_IS_MESSAGE (myObj) ? ((ProtobufMessage*) myObj) : NULL);
#line 70 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	aux = _tmp7_;
#line 71 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	protobuf_message_encode (aux, encBuffer);
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp8_ = myMsg;
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp9_ = protobuf_encode_buffer_get_data (encBuffer, &_tmp10_);
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp9__length1 = _tmp10_;
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp11_ = _tmp9_;
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp11__length1 = _tmp9__length1;
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp12_ = (_tmp11_ != NULL) ? _vala_array_dup3 (_tmp11_, _tmp11__length1) : _tmp11_;
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp12__length1 = _tmp11__length1;
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp13_ = g_byte_array_new_take (_tmp12_, _tmp12__length1);
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_byte_array_unref0 (_tmp8_->payLoad);
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp8_->payLoad = _tmp13_;
#line 73 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp14_ = self->priv->myDomain;
#line 73 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp15_ = myMsg;
#line 73 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	protocol_bus_domain_SendMsg (_tmp14_, _tmp15_);
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_object_unref0 (aux);
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_protobuf_encode_buffer_unref0 (encBuffer);
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_object_unref0 (myMsg);
#line 793 "GenericsPubSub.c"
}

void
protocol_bus_gpub_SendMsg (ProtocolBusGPub* self,
                           const gchar* channel,
                           gconstpointer myObj)
{
	gchar** chs = NULL;
	gchar* _tmp0_;
	gchar** _tmp1_;
	gint chs_length1;
	gint _chs_size_;
#line 76 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_if_fail (self != NULL);
#line 76 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_if_fail (channel != NULL);
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp0_ = g_strdup (channel);
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp1_ = g_new0 (gchar*, 1 + 1);
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_tmp1_[0] = _tmp0_;
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	chs = _tmp1_;
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	chs_length1 = 1;
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_chs_size_ = chs_length1;
#line 78 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	protocol_bus_gpub_SendMsgToChannels (self, chs, (gint) chs_length1, myObj);
#line 76 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	chs = (_vala_array_free (chs, chs_length1, (GDestroyNotify) g_free), NULL);
#line 826 "GenericsPubSub.c"
}

static void
protocol_bus_value_gpub_init (GValue* value)
{
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	value->data[0].v_pointer = NULL;
#line 834 "GenericsPubSub.c"
}

static void
protocol_bus_value_gpub_free_value (GValue* value)
{
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (value->data[0].v_pointer) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		protocol_bus_gpub_unref (value->data[0].v_pointer);
#line 844 "GenericsPubSub.c"
	}
}

static void
protocol_bus_value_gpub_copy_value (const GValue* src_value,
                                    GValue* dest_value)
{
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (src_value->data[0].v_pointer) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		dest_value->data[0].v_pointer = protocol_bus_gpub_ref (src_value->data[0].v_pointer);
#line 856 "GenericsPubSub.c"
	} else {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		dest_value->data[0].v_pointer = NULL;
#line 860 "GenericsPubSub.c"
	}
}

static gpointer
protocol_bus_value_gpub_peek_pointer (const GValue* value)
{
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return value->data[0].v_pointer;
#line 869 "GenericsPubSub.c"
}

static gchar*
protocol_bus_value_gpub_collect_value (GValue* value,
                                       guint n_collect_values,
                                       GTypeCValue* collect_values,
                                       guint collect_flags)
{
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (collect_values[0].v_pointer) {
#line 880 "GenericsPubSub.c"
		ProtocolBusGPub * object;
		object = collect_values[0].v_pointer;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		if (object->parent_instance.g_class == NULL) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 887 "GenericsPubSub.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 891 "GenericsPubSub.c"
		}
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		value->data[0].v_pointer = protocol_bus_gpub_ref (object);
#line 895 "GenericsPubSub.c"
	} else {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		value->data[0].v_pointer = NULL;
#line 899 "GenericsPubSub.c"
	}
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return NULL;
#line 903 "GenericsPubSub.c"
}

static gchar*
protocol_bus_value_gpub_lcopy_value (const GValue* value,
                                     guint n_collect_values,
                                     GTypeCValue* collect_values,
                                     guint collect_flags)
{
	ProtocolBusGPub ** object_p;
	object_p = collect_values[0].v_pointer;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (!object_p) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 918 "GenericsPubSub.c"
	}
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (!value->data[0].v_pointer) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		*object_p = NULL;
#line 924 "GenericsPubSub.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		*object_p = value->data[0].v_pointer;
#line 928 "GenericsPubSub.c"
	} else {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		*object_p = protocol_bus_gpub_ref (value->data[0].v_pointer);
#line 932 "GenericsPubSub.c"
	}
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return NULL;
#line 936 "GenericsPubSub.c"
}

GParamSpec*
protocol_bus_param_spec_gpub (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags)
{
	ProtocolBusParamSpecGPub* spec;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_val_if_fail (g_type_is_a (object_type, PROTOCOL_BUS_TYPE_GPUB), NULL);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return G_PARAM_SPEC (spec);
#line 955 "GenericsPubSub.c"
}

gpointer
protocol_bus_value_get_gpub (const GValue* value)
{
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PROTOCOL_BUS_TYPE_GPUB), NULL);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return value->data[0].v_pointer;
#line 965 "GenericsPubSub.c"
}

void
protocol_bus_value_set_gpub (GValue* value,
                             gpointer v_object)
{
	ProtocolBusGPub * old;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PROTOCOL_BUS_TYPE_GPUB));
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	old = value->data[0].v_pointer;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (v_object) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PROTOCOL_BUS_TYPE_GPUB));
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		value->data[0].v_pointer = v_object;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		protocol_bus_gpub_ref (value->data[0].v_pointer);
#line 987 "GenericsPubSub.c"
	} else {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		value->data[0].v_pointer = NULL;
#line 991 "GenericsPubSub.c"
	}
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (old) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		protocol_bus_gpub_unref (old);
#line 997 "GenericsPubSub.c"
	}
}

void
protocol_bus_value_take_gpub (GValue* value,
                              gpointer v_object)
{
	ProtocolBusGPub * old;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PROTOCOL_BUS_TYPE_GPUB));
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	old = value->data[0].v_pointer;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (v_object) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PROTOCOL_BUS_TYPE_GPUB));
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		value->data[0].v_pointer = v_object;
#line 1018 "GenericsPubSub.c"
	} else {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		value->data[0].v_pointer = NULL;
#line 1022 "GenericsPubSub.c"
	}
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (old) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		protocol_bus_gpub_unref (old);
#line 1028 "GenericsPubSub.c"
	}
}

static void
protocol_bus_gpub_class_init (ProtocolBusGPubClass * klass,
                              gpointer klass_data)
{
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	protocol_bus_gpub_parent_class = g_type_class_peek_parent (klass);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	((ProtocolBusGPubClass *) klass)->finalize = protocol_bus_gpub_finalize;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_type_class_adjust_private_offset (klass, &ProtocolBusGPub_private_offset);
#line 1042 "GenericsPubSub.c"
}

static void
protocol_bus_gpub_instance_init (ProtocolBusGPub * self,
                                 gpointer klass)
{
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->priv = protocol_bus_gpub_get_instance_private (self);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self->ref_count = 1;
#line 1053 "GenericsPubSub.c"
}

static void
protocol_bus_gpub_finalize (ProtocolBusGPub * obj)
{
	ProtocolBusGPub * self;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PROTOCOL_BUS_TYPE_GPUB, ProtocolBusGPub);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_signal_handlers_destroy (self);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_g_object_unref0 (self->priv->myDomain);
#line 1066 "GenericsPubSub.c"
}

static GType
protocol_bus_gpub_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { protocol_bus_value_gpub_init, protocol_bus_value_gpub_free_value, protocol_bus_value_gpub_copy_value, protocol_bus_value_gpub_peek_pointer, "p", protocol_bus_value_gpub_collect_value, "p", protocol_bus_value_gpub_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (ProtocolBusGPubClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) protocol_bus_gpub_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ProtocolBusGPub), 0, (GInstanceInitFunc) protocol_bus_gpub_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType protocol_bus_gpub_type_id;
	protocol_bus_gpub_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ProtocolBusGPub", &g_define_type_info, &g_define_type_fundamental_info, 0);
	ProtocolBusGPub_private_offset = g_type_add_instance_private (protocol_bus_gpub_type_id, sizeof (ProtocolBusGPubPrivate));
	return protocol_bus_gpub_type_id;
}

GType
protocol_bus_gpub_get_type (void)
{
	static volatile gsize protocol_bus_gpub_type_id__once = 0;
	if (g_once_init_enter (&protocol_bus_gpub_type_id__once)) {
		GType protocol_bus_gpub_type_id;
		protocol_bus_gpub_type_id = protocol_bus_gpub_get_type_once ();
		g_once_init_leave (&protocol_bus_gpub_type_id__once, protocol_bus_gpub_type_id);
	}
	return protocol_bus_gpub_type_id__once;
}

gpointer
protocol_bus_gpub_ref (gpointer instance)
{
	ProtocolBusGPub * self;
	self = instance;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_atomic_int_inc (&self->ref_count);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return instance;
#line 1102 "GenericsPubSub.c"
}

void
protocol_bus_gpub_unref (gpointer instance)
{
	ProtocolBusGPub * self;
	self = instance;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		PROTOCOL_BUS_GPUB_GET_CLASS (self)->finalize (self);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1116 "GenericsPubSub.c"
	}
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if ((array != NULL) && (destroy_func != NULL)) {
#line 1127 "GenericsPubSub.c"
		gssize i;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		for (i = 0; i < array_length; i = i + 1) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			if (((gpointer*) array)[i] != NULL) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				destroy_func (((gpointer*) array)[i]);
#line 1135 "GenericsPubSub.c"
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_vala_array_destroy (array, array_length, destroy_func);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_free (array);
#line 1150 "GenericsPubSub.c"
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (mem && byte_size != 0) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		new_mem = g_malloc (byte_size);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		memcpy (new_mem, mem, byte_size);
#line 1164 "GenericsPubSub.c"
	} else {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		new_mem = NULL;
#line 1168 "GenericsPubSub.c"
	}
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return new_mem;
#line 1172 "GenericsPubSub.c"
}

