/* Logger.c generated by valac 0.56.0, the Vala compiler
 * generated from Logger.vala, do not modify */

#include "protocolbus.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gobject/gvaluecollector.h>
#include <glib-object.h>
#include <stdio.h>
#include <glib/gstdio.h>

#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ProtocolBusParamSpecPair ProtocolBusParamSpecPair;
enum  {
	PROTOCOL_BUS_ILOGGER_0_PROPERTY,
	PROTOCOL_BUS_ILOGGER_NUM_PROPERTIES
};
static GParamSpec* protocol_bus_ilogger_properties[PROTOCOL_BUS_ILOGGER_NUM_PROPERTIES];

#define PROTOCOL_BUS_TYPE_LOGGER (protocol_bus_logger_get_type ())
#define PROTOCOL_BUS_LOGGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_LOGGER, ProtocolBusLogger))
#define PROTOCOL_BUS_LOGGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_LOGGER, ProtocolBusLoggerClass))
#define PROTOCOL_BUS_IS_LOGGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_LOGGER))
#define PROTOCOL_BUS_IS_LOGGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_LOGGER))
#define PROTOCOL_BUS_LOGGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_LOGGER, ProtocolBusLoggerClass))

typedef struct _ProtocolBusLogger ProtocolBusLogger;
typedef struct _ProtocolBusLoggerClass ProtocolBusLoggerClass;
typedef struct _ProtocolBusLoggerPrivate ProtocolBusLoggerPrivate;
enum  {
	PROTOCOL_BUS_LOGGER_0_PROPERTY,
	PROTOCOL_BUS_LOGGER_NUM_PROPERTIES
};
static GParamSpec* protocol_bus_logger_properties[PROTOCOL_BUS_LOGGER_NUM_PROPERTIES];
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_async_queue_unref0(var) ((var == NULL) ? NULL : (var = (g_async_queue_unref (var), NULL)))
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
#define _g_thread_unref0(var) ((var == NULL) ? NULL : (var = (g_thread_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _protocol_bus_pair_unref0(var) ((var == NULL) ? NULL : (var = (protocol_bus_pair_unref (var), NULL)))

struct _ProtocolBusParamSpecPair {
	GParamSpec parent_instance;
};

struct _ProtocolBusLogger {
	GObject parent_instance;
	ProtocolBusLoggerPrivate * priv;
	ProtocolBusWaitHandle** ContinueWH;
	gint ContinueWH_length1;
	gint _ContinueWH_size_;
};

struct _ProtocolBusLoggerClass {
	GObjectClass parent_class;
};

struct _ProtocolBusLoggerPrivate {
	gchar* fileName;
	GAsyncQueue* myQueue;
	GRecMutex __lock_myQueue;
	FILE* arch;
	ProtocolBusTraceLevel theTL;
	gboolean isStarted;
	GThread* myThread;
	ProtocolBusManualResetEvent* theFinishedAppEvt;
	ProtocolBusManualResetEvent* elemsOnQueueEvt;
	gboolean isOwnTrace;
};

static gpointer protocol_bus_pair_parent_class = NULL;
static gpointer protocol_bus_ilogger_parent_class = NULL;
static gint ProtocolBusLogger_private_offset;
static gpointer protocol_bus_logger_parent_class = NULL;
static ProtocolBusLogger* protocol_bus_logger_instance;
static ProtocolBusLogger* protocol_bus_logger_instance = NULL;

static void protocol_bus_pair_finalize (ProtocolBusPair * obj);
static GType protocol_bus_pair_get_type_once (void);
static gchar* protocol_bus_ilogger_ProcessTrace (ProtocolBusILogger* self,
                                          const gchar* trace);
VALA_EXTERN void protocol_bus_logger_Trace (ProtocolBusTraceLevel tl,
                                const gchar* trace);
VALA_EXTERN void protocol_bus_logger_TraceWithErr (ProtocolBusTraceLevel tl,
                                       const gchar* trace,
                                       GError* ex);
VALA_EXTERN void protocol_bus_logger_TraceOn (ProtocolBusTraceLevel tl);
VALA_EXTERN void protocol_bus_logger_FinnishLog (void);
static GType protocol_bus_ilogger_get_type_once (void);
VALA_EXTERN GType protocol_bus_logger_get_type (void) G_GNUC_CONST ;
static void _protocol_bus_pair_unref0_ (gpointer var);
static ProtocolBusLogger* protocol_bus_logger_new (ProtocolBusTraceLevel tl);
static ProtocolBusLogger* protocol_bus_logger_construct (GType object_type,
                                                  ProtocolBusTraceLevel tl);
static void protocol_bus_logger_DoTrace (ProtocolBusLogger* self,
                                  ProtocolBusTraceLevel tl,
                                  const gchar* trace);
static gchar* protocol_bus_logger_PrepareTrace (ProtocolBusLogger* self,
                                         ProtocolBusTraceLevel tl,
                                         const gchar* trace);
static void protocol_bus_logger_MainLloop (ProtocolBusLogger* self);
static gpointer _protocol_bus_logger_MainLloop_gthread_func (gpointer self);
static gchar* protocol_bus_logger_PrepareTraceWithErr (ProtocolBusLogger* self,
                                                ProtocolBusTraceLevel tl,
                                                const gchar* trace,
                                                GError* ex);
static void protocol_bus_logger_finalize (GObject * obj);
static GType protocol_bus_logger_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

static GType
protocol_bus_trace_level_get_type_once (void)
{
	static const GEnumValue values[] = {{PROTOCOL_BUS_TRACE_LEVEL_ERROR, "PROTOCOL_BUS_TRACE_LEVEL_ERROR", "error"}, {PROTOCOL_BUS_TRACE_LEVEL_WARNING, "PROTOCOL_BUS_TRACE_LEVEL_WARNING", "warning"}, {PROTOCOL_BUS_TRACE_LEVEL_INFO, "PROTOCOL_BUS_TRACE_LEVEL_INFO", "info"}, {PROTOCOL_BUS_TRACE_LEVEL_TRACE, "PROTOCOL_BUS_TRACE_LEVEL_TRACE", "trace"}, {0, NULL, NULL}};
	GType protocol_bus_trace_level_type_id;
	protocol_bus_trace_level_type_id = g_enum_register_static ("ProtocolBusTraceLevel", values);
	return protocol_bus_trace_level_type_id;
}

GType
protocol_bus_trace_level_get_type (void)
{
	static volatile gsize protocol_bus_trace_level_type_id__once = 0;
	if (g_once_init_enter (&protocol_bus_trace_level_type_id__once)) {
		GType protocol_bus_trace_level_type_id;
		protocol_bus_trace_level_type_id = protocol_bus_trace_level_get_type_once ();
		g_once_init_leave (&protocol_bus_trace_level_type_id__once, protocol_bus_trace_level_type_id);
	}
	return protocol_bus_trace_level_type_id__once;
}

ProtocolBusPair*
protocol_bus_pair_construct (GType object_type,
                             ProtocolBusTraceLevel atl,
                             const gchar* atrace)
{
	ProtocolBusPair* self = NULL;
	gchar* _tmp0_;
#line 19 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_val_if_fail (atrace != NULL, NULL);
#line 19 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self = (ProtocolBusPair*) g_type_create_instance (object_type);
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->tl = atl;
#line 21 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = g_strdup (atrace);
#line 21 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (self->trace);
#line 21 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->trace = _tmp0_;
#line 19 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return self;
#line 163 "Logger.c"
}

ProtocolBusPair*
protocol_bus_pair_new (ProtocolBusTraceLevel atl,
                       const gchar* atrace)
{
#line 19 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return protocol_bus_pair_construct (PROTOCOL_BUS_TYPE_PAIR, atl, atrace);
#line 172 "Logger.c"
}

static void
protocol_bus_value_pair_init (GValue* value)
{
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	value->data[0].v_pointer = NULL;
#line 180 "Logger.c"
}

static void
protocol_bus_value_pair_free_value (GValue* value)
{
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (value->data[0].v_pointer) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		protocol_bus_pair_unref (value->data[0].v_pointer);
#line 190 "Logger.c"
	}
}

static void
protocol_bus_value_pair_copy_value (const GValue* src_value,
                                    GValue* dest_value)
{
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (src_value->data[0].v_pointer) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		dest_value->data[0].v_pointer = protocol_bus_pair_ref (src_value->data[0].v_pointer);
#line 202 "Logger.c"
	} else {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		dest_value->data[0].v_pointer = NULL;
#line 206 "Logger.c"
	}
}

static gpointer
protocol_bus_value_pair_peek_pointer (const GValue* value)
{
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return value->data[0].v_pointer;
#line 215 "Logger.c"
}

static gchar*
protocol_bus_value_pair_collect_value (GValue* value,
                                       guint n_collect_values,
                                       GTypeCValue* collect_values,
                                       guint collect_flags)
{
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (collect_values[0].v_pointer) {
#line 226 "Logger.c"
		ProtocolBusPair * object;
		object = collect_values[0].v_pointer;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		if (object->parent_instance.g_class == NULL) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 233 "Logger.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 237 "Logger.c"
		}
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		value->data[0].v_pointer = protocol_bus_pair_ref (object);
#line 241 "Logger.c"
	} else {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		value->data[0].v_pointer = NULL;
#line 245 "Logger.c"
	}
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return NULL;
#line 249 "Logger.c"
}

static gchar*
protocol_bus_value_pair_lcopy_value (const GValue* value,
                                     guint n_collect_values,
                                     GTypeCValue* collect_values,
                                     guint collect_flags)
{
	ProtocolBusPair ** object_p;
	object_p = collect_values[0].v_pointer;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (!object_p) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 264 "Logger.c"
	}
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (!value->data[0].v_pointer) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		*object_p = NULL;
#line 270 "Logger.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		*object_p = value->data[0].v_pointer;
#line 274 "Logger.c"
	} else {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		*object_p = protocol_bus_pair_ref (value->data[0].v_pointer);
#line 278 "Logger.c"
	}
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return NULL;
#line 282 "Logger.c"
}

GParamSpec*
protocol_bus_param_spec_pair (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags)
{
	ProtocolBusParamSpecPair* spec;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_val_if_fail (g_type_is_a (object_type, PROTOCOL_BUS_TYPE_PAIR), NULL);
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return G_PARAM_SPEC (spec);
#line 301 "Logger.c"
}

gpointer
protocol_bus_value_get_pair (const GValue* value)
{
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PROTOCOL_BUS_TYPE_PAIR), NULL);
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return value->data[0].v_pointer;
#line 311 "Logger.c"
}

void
protocol_bus_value_set_pair (GValue* value,
                             gpointer v_object)
{
	ProtocolBusPair * old;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PROTOCOL_BUS_TYPE_PAIR));
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	old = value->data[0].v_pointer;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (v_object) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PROTOCOL_BUS_TYPE_PAIR));
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		value->data[0].v_pointer = v_object;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		protocol_bus_pair_ref (value->data[0].v_pointer);
#line 333 "Logger.c"
	} else {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		value->data[0].v_pointer = NULL;
#line 337 "Logger.c"
	}
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (old) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		protocol_bus_pair_unref (old);
#line 343 "Logger.c"
	}
}

void
protocol_bus_value_take_pair (GValue* value,
                              gpointer v_object)
{
	ProtocolBusPair * old;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PROTOCOL_BUS_TYPE_PAIR));
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	old = value->data[0].v_pointer;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (v_object) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PROTOCOL_BUS_TYPE_PAIR));
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		value->data[0].v_pointer = v_object;
#line 364 "Logger.c"
	} else {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		value->data[0].v_pointer = NULL;
#line 368 "Logger.c"
	}
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (old) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		protocol_bus_pair_unref (old);
#line 374 "Logger.c"
	}
}

static void
protocol_bus_pair_class_init (ProtocolBusPairClass * klass,
                              gpointer klass_data)
{
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	protocol_bus_pair_parent_class = g_type_class_peek_parent (klass);
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	((ProtocolBusPairClass *) klass)->finalize = protocol_bus_pair_finalize;
#line 386 "Logger.c"
}

static void
protocol_bus_pair_instance_init (ProtocolBusPair * self,
                                 gpointer klass)
{
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->ref_count = 1;
#line 395 "Logger.c"
}

static void
protocol_bus_pair_finalize (ProtocolBusPair * obj)
{
	ProtocolBusPair * self;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PROTOCOL_BUS_TYPE_PAIR, ProtocolBusPair);
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_signal_handlers_destroy (self);
#line 17 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (self->trace);
#line 408 "Logger.c"
}

static GType
protocol_bus_pair_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { protocol_bus_value_pair_init, protocol_bus_value_pair_free_value, protocol_bus_value_pair_copy_value, protocol_bus_value_pair_peek_pointer, "p", protocol_bus_value_pair_collect_value, "p", protocol_bus_value_pair_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (ProtocolBusPairClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) protocol_bus_pair_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ProtocolBusPair), 0, (GInstanceInitFunc) protocol_bus_pair_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType protocol_bus_pair_type_id;
	protocol_bus_pair_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ProtocolBusPair", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return protocol_bus_pair_type_id;
}

GType
protocol_bus_pair_get_type (void)
{
	static volatile gsize protocol_bus_pair_type_id__once = 0;
	if (g_once_init_enter (&protocol_bus_pair_type_id__once)) {
		GType protocol_bus_pair_type_id;
		protocol_bus_pair_type_id = protocol_bus_pair_get_type_once ();
		g_once_init_leave (&protocol_bus_pair_type_id__once, protocol_bus_pair_type_id);
	}
	return protocol_bus_pair_type_id__once;
}

gpointer
protocol_bus_pair_ref (gpointer instance)
{
	ProtocolBusPair * self;
	self = instance;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_atomic_int_inc (&self->ref_count);
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return instance;
#line 443 "Logger.c"
}

void
protocol_bus_pair_unref (gpointer instance)
{
	ProtocolBusPair * self;
	self = instance;
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		PROTOCOL_BUS_PAIR_GET_CLASS (self)->finalize (self);
#line 15 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 457 "Logger.c"
	}
}

void
protocol_bus_ilogger_LoggerTrace (ProtocolBusILogger* self,
                                  ProtocolBusTraceLevel tl,
                                  const gchar* trace)
{
	gchar* aux_trace = NULL;
	gchar* _tmp0_;
#line 30 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (self != NULL);
#line 30 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (trace != NULL);
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = protocol_bus_ilogger_ProcessTrace (self, trace);
#line 31 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	aux_trace = _tmp0_;
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	protocol_bus_logger_Trace (tl, aux_trace);
#line 30 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (aux_trace);
#line 480 "Logger.c"
}

void
protocol_bus_ilogger_LoggerTraceWithErr (ProtocolBusILogger* self,
                                         ProtocolBusTraceLevel tl,
                                         const gchar* trace,
                                         GError* ex)
{
	gchar* aux_trace = NULL;
	gchar* _tmp0_;
#line 35 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (self != NULL);
#line 35 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (trace != NULL);
#line 35 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (ex != NULL);
#line 36 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = protocol_bus_ilogger_ProcessTrace (self, trace);
#line 36 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	aux_trace = _tmp0_;
#line 37 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	protocol_bus_logger_TraceWithErr (tl, aux_trace, ex);
#line 35 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (aux_trace);
#line 505 "Logger.c"
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gchar* _tmp0_;
	gboolean result;
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, FALSE);
#line 1531 "glib-2.0.vapi"
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
#line 1531 "glib-2.0.vapi"
	result = _tmp0_ != NULL;
#line 1531 "glib-2.0.vapi"
	return result;
#line 524 "Logger.c"
}

static gchar*
protocol_bus_ilogger_ProcessTrace (ProtocolBusILogger* self,
                                   const gchar* trace)
{
	gchar** aux = NULL;
	gint aux_length1 = 0;
	gint _aux_size_ = 0;
	gchar* aux_trace = NULL;
	gchar* _tmp0_;
	gchar* result;
#line 40 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 40 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_val_if_fail (trace != NULL, NULL);
#line 43 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = g_strdup ("");
#line 43 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	aux_trace = _tmp0_;
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (string_contains (trace, "-->")) {
#line 547 "Logger.c"
		gchar** _tmp1_;
		gchar** _tmp2_;
		gchar** _tmp3_;
		gint _tmp3__length1;
		const gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		gchar** _tmp7_;
		gint _tmp7__length1;
		const gchar* _tmp8_;
		gchar* _tmp9_;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp2_ = _tmp1_ = g_strsplit (trace, "-->", 0);
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		aux = (_vala_array_free (aux, aux_length1, (GDestroyNotify) g_free), NULL);
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		aux = _tmp2_;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		aux_length1 = _vala_array_length (_tmp1_);
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_aux_size_ = aux_length1;
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp3_ = aux;
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp3__length1 = aux_length1;
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp4_ = _tmp3_[0];
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp5_ = g_strconcat (_tmp4_, "\n\t", NULL);
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp6_ = _tmp5_;
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp7_ = aux;
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp7__length1 = aux_length1;
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp8_ = _tmp7_[1];
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp9_ = g_strconcat (_tmp6_, _tmp8_, NULL);
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (aux_trace);
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		aux_trace = _tmp9_;
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (_tmp6_);
#line 593 "Logger.c"
	} else {
		gchar* _tmp10_;
#line 48 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp10_ = g_strdup (trace);
#line 48 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (aux_trace);
#line 48 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		aux_trace = _tmp10_;
#line 602 "Logger.c"
	}
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	result = aux_trace;
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	aux = (_vala_array_free (aux, aux_length1, (GDestroyNotify) g_free), NULL);
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return result;
#line 610 "Logger.c"
}

void
protocol_bus_ilogger_LoggerTraceOn (ProtocolBusTraceLevel tl)
{
#line 54 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	protocol_bus_logger_TraceOn (tl);
#line 618 "Logger.c"
}

void
protocol_bus_ilogger_FinishLog (void)
{
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	protocol_bus_logger_FinnishLog ();
#line 59 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return;
#line 628 "Logger.c"
}

ProtocolBusILogger*
protocol_bus_ilogger_construct (GType object_type)
{
	ProtocolBusILogger * self = NULL;
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self = (ProtocolBusILogger*) g_object_new (object_type, NULL);
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return self;
#line 639 "Logger.c"
}

static void
protocol_bus_ilogger_class_init (ProtocolBusILoggerClass * klass,
                                 gpointer klass_data)
{
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	protocol_bus_ilogger_parent_class = g_type_class_peek_parent (klass);
#line 648 "Logger.c"
}

static void
protocol_bus_ilogger_instance_init (ProtocolBusILogger * self,
                                    gpointer klass)
{
}

static GType
protocol_bus_ilogger_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ProtocolBusILoggerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) protocol_bus_ilogger_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ProtocolBusILogger), 0, (GInstanceInitFunc) protocol_bus_ilogger_instance_init, NULL };
	GType protocol_bus_ilogger_type_id;
	protocol_bus_ilogger_type_id = g_type_register_static (G_TYPE_OBJECT, "ProtocolBusILogger", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
	return protocol_bus_ilogger_type_id;
}

GType
protocol_bus_ilogger_get_type (void)
{
	static volatile gsize protocol_bus_ilogger_type_id__once = 0;
	if (g_once_init_enter (&protocol_bus_ilogger_type_id__once)) {
		GType protocol_bus_ilogger_type_id;
		protocol_bus_ilogger_type_id = protocol_bus_ilogger_get_type_once ();
		g_once_init_leave (&protocol_bus_ilogger_type_id__once, protocol_bus_ilogger_type_id);
	}
	return protocol_bus_ilogger_type_id__once;
}

static inline gpointer
protocol_bus_logger_get_instance_private (ProtocolBusLogger* self)
{
	return G_STRUCT_MEMBER_P (self, ProtocolBusLogger_private_offset);
}

static void
_protocol_bus_pair_unref0_ (gpointer var)
{
#line 70 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	(var == NULL) ? NULL : (var = (protocol_bus_pair_unref (var), NULL));
#line 689 "Logger.c"
}

static gpointer
_protocol_bus_logger_MainLloop_gthread_func (gpointer self)
{
	gpointer result;
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	protocol_bus_logger_MainLloop ((ProtocolBusLogger*) self);
#line 698 "Logger.c"
	result = NULL;
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return result;
#line 702 "Logger.c"
}

void
protocol_bus_logger_TraceOn (ProtocolBusTraceLevel tl)
{
	ProtocolBusLogger* _tmp0_;
#line 84 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = protocol_bus_logger_instance;
#line 84 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (_tmp0_ == NULL) {
#line 713 "Logger.c"
		ProtocolBusLogger* _tmp1_;
		ProtocolBusLogger* _tmp2_;
		ProtocolBusLogger* _tmp3_;
		ProtocolBusLogger* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		gchar* _tmp16_;
		ProtocolBusLogger* _tmp17_;
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp1_ = protocol_bus_logger_new (tl);
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_object_unref0 (protocol_bus_logger_instance);
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		protocol_bus_logger_instance = _tmp1_;
#line 86 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp2_ = protocol_bus_logger_instance;
#line 86 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp2_->priv->isOwnTrace = TRUE;
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp3_ = protocol_bus_logger_instance;
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp4_ = protocol_bus_logger_instance;
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp5_ = g_strdup_printf ("%i", 87);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp6_ = _tmp5_;
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp7_ = g_strconcat ("Logger.vala" ", L-", _tmp6_, NULL);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp8_ = _tmp7_;
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp9_ = g_strconcat (_tmp8_, ": ", NULL);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp10_ = _tmp9_;
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp11_ = g_strconcat (_tmp10_, "ProtocolBus.Logger.TraceOn", NULL);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp12_ = _tmp11_;
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp13_ = g_strconcat (_tmp12_, "\n\tLogger started", NULL);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp14_ = _tmp13_;
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp15_ = protocol_bus_logger_PrepareTrace (_tmp4_, PROTOCOL_BUS_TRACE_LEVEL_TRACE, _tmp14_);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp16_ = _tmp15_;
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		protocol_bus_logger_DoTrace (_tmp3_, PROTOCOL_BUS_TRACE_LEVEL_INFO, _tmp16_);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (_tmp16_);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (_tmp14_);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (_tmp12_);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (_tmp10_);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (_tmp8_);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (_tmp6_);
#line 89 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp17_ = protocol_bus_logger_instance;
#line 89 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		if (!_tmp17_->priv->isStarted) {
#line 787 "Logger.c"
			ProtocolBusLogger* _tmp18_;
			ProtocolBusLogger* _tmp19_;
			GThread* _tmp20_;
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp18_ = protocol_bus_logger_instance;
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp19_ = protocol_bus_logger_instance;
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp20_ = g_thread_new ("ML_Logger", _protocol_bus_logger_MainLloop_gthread_func, g_object_ref (_tmp19_));
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_thread_unref0 (_tmp18_->priv->myThread);
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp18_->priv->myThread = _tmp20_;
#line 801 "Logger.c"
		}
	}
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return self ? g_object_ref (self) : NULL;
#line 811 "Logger.c"
}

static ProtocolBusLogger*
protocol_bus_logger_construct (GType object_type,
                               ProtocolBusTraceLevel tl)
{
	ProtocolBusLogger * self = NULL;
	const gchar* _tmp0_;
	FILE* _tmp1_;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	ProtocolBusManualResetEvent* _tmp5_;
	ProtocolBusWaitHandle* _tmp6_;
	ProtocolBusManualResetEvent* _tmp7_;
	ProtocolBusWaitHandle* _tmp8_;
	ProtocolBusWaitHandle** _tmp9_;
#line 98 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self = (ProtocolBusLogger*) g_object_new (object_type, NULL);
#line 99 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = self->priv->fileName;
#line 99 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp1_ = g_fopen (_tmp0_, "w");
#line 99 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_fclose0 (self->priv->arch);
#line 99 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->arch = _tmp1_;
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (tl != PROTOCOL_BUS_TRACE_LEVEL_TRACE) {
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp4_ = tl != PROTOCOL_BUS_TRACE_LEVEL_INFO;
#line 843 "Logger.c"
	} else {
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp4_ = FALSE;
#line 847 "Logger.c"
	}
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (_tmp4_) {
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp3_ = tl != PROTOCOL_BUS_TRACE_LEVEL_WARNING;
#line 853 "Logger.c"
	} else {
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp3_ = FALSE;
#line 857 "Logger.c"
	}
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (_tmp3_) {
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp2_ = tl != PROTOCOL_BUS_TRACE_LEVEL_ERROR;
#line 863 "Logger.c"
	} else {
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp2_ = FALSE;
#line 867 "Logger.c"
	}
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (_tmp2_) {
#line 115 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		self->priv->theTL = PROTOCOL_BUS_TRACE_LEVEL_ERROR;
#line 873 "Logger.c"
	} else {
#line 117 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		self->priv->theTL = tl;
#line 877 "Logger.c"
	}
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp5_ = self->priv->theFinishedAppEvt;
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp6_ = _g_object_ref0 ((ProtocolBusWaitHandle*) _tmp5_);
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp7_ = self->priv->elemsOnQueueEvt;
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp8_ = _g_object_ref0 ((ProtocolBusWaitHandle*) _tmp7_);
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp9_ = g_new0 (ProtocolBusWaitHandle*, 2 + 1);
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp9_[0] = _tmp6_;
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp9_[1] = _tmp8_;
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->ContinueWH = (_vala_array_free (self->ContinueWH, self->ContinueWH_length1, (GDestroyNotify) g_object_unref), NULL);
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->ContinueWH = _tmp9_;
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->ContinueWH_length1 = 2;
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->_ContinueWH_size_ = self->ContinueWH_length1;
#line 98 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return self;
#line 903 "Logger.c"
}

static ProtocolBusLogger*
protocol_bus_logger_new (ProtocolBusTraceLevel tl)
{
#line 98 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return protocol_bus_logger_construct (PROTOCOL_BUS_TYPE_LOGGER, tl);
#line 911 "Logger.c"
}

static void
protocol_bus_logger_MainLloop (ProtocolBusLogger* self)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	gchar* _tmp28_;
	gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	gchar* _tmp34_;
	gchar* _tmp35_;
	const gchar* _tmp36_;
	gchar* _tmp37_;
	gchar* _tmp38_;
	gchar* _tmp39_;
	gchar* _tmp40_;
	GError* _inner_error0_ = NULL;
#line 137 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (self != NULL);
#line 138 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->isStarted = TRUE;
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->isOwnTrace = TRUE;
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = g_strdup_printf ("%i", 140);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp1_ = _tmp0_;
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp2_ = g_strconcat ("Logger.vala" ", L-", _tmp1_, NULL);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp3_ = _tmp2_;
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp4_ = g_strconcat (_tmp3_, ": ", NULL);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp5_ = _tmp4_;
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp6_ = g_strconcat (_tmp5_, "ProtocolBus.Logger.MainLloop", NULL);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp7_ = _tmp6_;
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp8_ = g_strconcat (_tmp7_, "\n\tMainLoop started", NULL);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp9_ = _tmp8_;
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp10_ = protocol_bus_logger_PrepareTrace (self, PROTOCOL_BUS_TRACE_LEVEL_INFO, _tmp9_);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp11_ = _tmp10_;
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	protocol_bus_logger_DoTrace (self, PROTOCOL_BUS_TRACE_LEVEL_INFO, _tmp11_);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp11_);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp9_);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp7_);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp5_);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp3_);
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp1_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	while (TRUE) {
#line 991 "Logger.c"
		ProtocolBusWaitHandle** _tmp12_;
		gint _tmp12__length1;
		FILE* _tmp25_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp12_ = self->ContinueWH;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp12__length1 = self->ContinueWH_length1;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		if (!(protocol_bus_wait_handle_WaitAny (_tmp12_, (gint) _tmp12__length1) == ((guint) 1))) {
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1003 "Logger.c"
		}
		{
			GAsyncQueue* _tmp13_;
#line 144 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp13_ = self->priv->myQueue;
#line 144 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			g_rec_mutex_lock (&self->priv->__lock_myQueue);
#line 1011 "Logger.c"
			{
				gint len = 0;
				GAsyncQueue* _tmp14_;
#line 145 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp14_ = self->priv->myQueue;
#line 145 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				len = g_async_queue_length (_tmp14_);
#line 146 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				while (TRUE) {
#line 1021 "Logger.c"
					ProtocolBusPair* aux = NULL;
					GAsyncQueue* _tmp15_;
					gpointer _tmp16_;
					ProtocolBusPair* _tmp17_;
					ProtocolBusPair* _tmp18_;
					const gchar* _tmp19_;
					GAsyncQueue* _tmp20_;
					ProtocolBusPair* _tmp21_;
					GAsyncQueue* _tmp22_;
#line 146 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					if (!(len > 0)) {
#line 146 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
						break;
#line 1035 "Logger.c"
					}
#line 147 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					_tmp15_ = self->priv->myQueue;
#line 147 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					_tmp16_ = g_async_queue_pop (_tmp15_);
#line 147 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					aux = (ProtocolBusPair*) _tmp16_;
#line 148 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					_tmp17_ = aux;
#line 148 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					_tmp18_ = aux;
#line 148 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					_tmp19_ = _tmp18_->trace;
#line 148 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					protocol_bus_logger_DoTrace (self, _tmp17_->tl, _tmp19_);
#line 149 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					_tmp20_ = self->priv->myQueue;
#line 149 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					_tmp21_ = aux;
#line 149 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					g_async_queue_remove (_tmp20_, _tmp21_);
#line 150 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					_tmp22_ = self->priv->myQueue;
#line 150 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					len = g_async_queue_length (_tmp22_);
#line 146 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					_protocol_bus_pair_unref0 (aux);
#line 1063 "Logger.c"
				}
#line 152 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				if (len == 0) {
#line 1067 "Logger.c"
					ProtocolBusManualResetEvent* _tmp23_;
#line 152 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					_tmp23_ = self->priv->elemsOnQueueEvt;
#line 152 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
					protocol_bus_manual_reset_event_Reset (_tmp23_);
#line 1073 "Logger.c"
				}
			}
			__finally0:
			{
				GAsyncQueue* _tmp24_;
#line 144 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp24_ = self->priv->myQueue;
#line 144 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_rec_mutex_unlock (&self->priv->__lock_myQueue);
#line 1083 "Logger.c"
			}
#line 144 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 144 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 144 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_clear_error (&_inner_error0_);
#line 144 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				return;
#line 1093 "Logger.c"
			}
		}
#line 154 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp25_ = self->priv->arch;
#line 154 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		fflush (_tmp25_);
#line 1100 "Logger.c"
	}
#line 156 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->isStarted = FALSE;
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp26_ = g_strdup_printf ("%i", 158);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp27_ = _tmp26_;
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp28_ = g_strconcat ("Logger.vala" ", L-", _tmp27_, NULL);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp29_ = _tmp28_;
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp30_ = g_strconcat (_tmp29_, ": ", NULL);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp31_ = _tmp30_;
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp32_ = g_strconcat (_tmp31_, "ProtocolBus.Logger.MainLloop", NULL);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp33_ = _tmp32_;
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp34_ = g_strconcat (_tmp33_, "\n\tLogger: Thread finished - ", NULL);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp35_ = _tmp34_;
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp36_ = g_type_name (G_TYPE_FROM_INSTANCE ((GObject*) self));
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp37_ = g_strconcat (_tmp35_, _tmp36_, NULL);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp38_ = _tmp37_;
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp39_ = protocol_bus_logger_PrepareTrace (self, PROTOCOL_BUS_TRACE_LEVEL_INFO, _tmp38_);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp40_ = _tmp39_;
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	protocol_bus_logger_DoTrace (self, PROTOCOL_BUS_TRACE_LEVEL_INFO, _tmp40_);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp40_);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp38_);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp35_);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp33_);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp31_);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp29_);
#line 158 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp27_);
#line 1150 "Logger.c"
}

static gpointer
_protocol_bus_pair_ref0 (gpointer self)
{
#line 167 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return self ? protocol_bus_pair_ref (self) : NULL;
#line 1158 "Logger.c"
}

void
protocol_bus_logger_Trace (ProtocolBusTraceLevel tl,
                           const gchar* trace)
{
	ProtocolBusLogger* _tmp0_;
	GError* _inner_error0_ = NULL;
#line 162 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (trace != NULL);
#line 163 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = protocol_bus_logger_instance;
#line 163 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (_tmp0_ != NULL) {
#line 1173 "Logger.c"
		gchar* aux_trace = NULL;
		ProtocolBusLogger* _tmp1_;
		gchar* _tmp2_;
		ProtocolBusPair* p = NULL;
		const gchar* _tmp3_;
		ProtocolBusPair* _tmp4_;
		ProtocolBusLogger* _tmp13_;
		ProtocolBusManualResetEvent* _tmp14_;
#line 164 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp1_ = protocol_bus_logger_instance;
#line 164 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp2_ = protocol_bus_logger_PrepareTrace (_tmp1_, tl, trace);
#line 164 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		aux_trace = _tmp2_;
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp3_ = aux_trace;
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp4_ = protocol_bus_pair_new (tl, _tmp3_);
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		p = _tmp4_;
#line 1194 "Logger.c"
		{
			ProtocolBusLogger* _tmp5_;
			GAsyncQueue* _tmp6_;
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp5_ = protocol_bus_logger_instance;
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp6_ = _tmp5_->priv->myQueue;
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			g_rec_mutex_lock (&_tmp5_->priv->__lock_myQueue);
#line 1204 "Logger.c"
			{
				ProtocolBusLogger* _tmp7_;
				GAsyncQueue* _tmp8_;
				ProtocolBusPair* _tmp9_;
				ProtocolBusPair* _tmp10_;
#line 167 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp7_ = protocol_bus_logger_instance;
#line 167 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp8_ = _tmp7_->priv->myQueue;
#line 167 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp9_ = p;
#line 167 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp10_ = _protocol_bus_pair_ref0 (_tmp9_);
#line 167 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_async_queue_push (_tmp8_, _tmp10_);
#line 1220 "Logger.c"
			}
			__finally0:
			{
				ProtocolBusLogger* _tmp11_;
				GAsyncQueue* _tmp12_;
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp11_ = protocol_bus_logger_instance;
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp12_ = _tmp11_->priv->myQueue;
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_rec_mutex_unlock (&_tmp11_->priv->__lock_myQueue);
#line 1232 "Logger.c"
			}
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_protocol_bus_pair_unref0 (p);
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_g_free0 (aux_trace);
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_clear_error (&_inner_error0_);
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				return;
#line 1246 "Logger.c"
			}
		}
#line 169 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp13_ = protocol_bus_logger_instance;
#line 169 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp14_ = _tmp13_->priv->elemsOnQueueEvt;
#line 169 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		protocol_bus_manual_reset_event_Set (_tmp14_);
#line 163 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_protocol_bus_pair_unref0 (p);
#line 163 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (aux_trace);
#line 1259 "Logger.c"
	}
}

void
protocol_bus_logger_TraceWithErr (ProtocolBusTraceLevel tl,
                                  const gchar* trace,
                                  GError* ex)
{
	ProtocolBusLogger* _tmp0_;
	GError* _inner_error0_ = NULL;
#line 173 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (trace != NULL);
#line 173 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (ex != NULL);
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = protocol_bus_logger_instance;
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (_tmp0_ != NULL) {
#line 1278 "Logger.c"
		gchar* aux_trace = NULL;
		ProtocolBusLogger* _tmp1_;
		gchar* _tmp2_;
		ProtocolBusPair* p = NULL;
		const gchar* _tmp3_;
		ProtocolBusPair* _tmp4_;
		ProtocolBusLogger* _tmp13_;
		ProtocolBusManualResetEvent* _tmp14_;
#line 175 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp1_ = protocol_bus_logger_instance;
#line 175 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp2_ = protocol_bus_logger_PrepareTraceWithErr (_tmp1_, tl, trace, ex);
#line 175 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		aux_trace = _tmp2_;
#line 176 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp3_ = aux_trace;
#line 176 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp4_ = protocol_bus_pair_new (tl, _tmp3_);
#line 176 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		p = _tmp4_;
#line 1299 "Logger.c"
		{
			ProtocolBusLogger* _tmp5_;
			GAsyncQueue* _tmp6_;
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp5_ = protocol_bus_logger_instance;
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp6_ = _tmp5_->priv->myQueue;
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			g_rec_mutex_lock (&_tmp5_->priv->__lock_myQueue);
#line 1309 "Logger.c"
			{
				ProtocolBusLogger* _tmp7_;
				GAsyncQueue* _tmp8_;
				ProtocolBusPair* _tmp9_;
				ProtocolBusPair* _tmp10_;
#line 178 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp7_ = protocol_bus_logger_instance;
#line 178 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp8_ = _tmp7_->priv->myQueue;
#line 178 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp9_ = p;
#line 178 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp10_ = _protocol_bus_pair_ref0 (_tmp9_);
#line 178 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_async_queue_push (_tmp8_, _tmp10_);
#line 1325 "Logger.c"
			}
			__finally0:
			{
				ProtocolBusLogger* _tmp11_;
				GAsyncQueue* _tmp12_;
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp11_ = protocol_bus_logger_instance;
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp12_ = _tmp11_->priv->myQueue;
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_rec_mutex_unlock (&_tmp11_->priv->__lock_myQueue);
#line 1337 "Logger.c"
			}
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_protocol_bus_pair_unref0 (p);
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_g_free0 (aux_trace);
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				g_clear_error (&_inner_error0_);
#line 177 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				return;
#line 1351 "Logger.c"
			}
		}
#line 180 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp13_ = protocol_bus_logger_instance;
#line 180 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp14_ = _tmp13_->priv->elemsOnQueueEvt;
#line 180 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		protocol_bus_manual_reset_event_Set (_tmp14_);
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_protocol_bus_pair_unref0 (p);
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (aux_trace);
#line 1364 "Logger.c"
	}
}

static void
protocol_bus_logger_DoTrace (ProtocolBusLogger* self,
                             ProtocolBusTraceLevel tl,
                             const gchar* trace)
{
	FILE* _tmp20_;
#line 184 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (self != NULL);
#line 184 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_if_fail (trace != NULL);
#line 185 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	switch (tl) {
#line 185 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_TRACE:
#line 1382 "Logger.c"
		{
#line 187 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			if (PROTOCOL_BUS_TRACE_LEVEL_TRACE <= self->priv->theTL) {
#line 1386 "Logger.c"
				FILE* _tmp0_;
				gchar* _tmp1_;
				gchar* _tmp2_;
				gchar* _tmp3_;
				gchar* _tmp4_;
#line 188 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp0_ = self->priv->arch;
#line 188 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp1_ = g_strconcat ("TRACE:\t", trace, NULL);
#line 188 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp2_ = _tmp1_;
#line 188 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp3_ = g_strconcat (_tmp2_, "\n", NULL);
#line 188 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp4_ = _tmp3_;
#line 188 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				fputs (_tmp4_, _tmp0_);
#line 188 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_g_free0 (_tmp4_);
#line 188 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_g_free0 (_tmp2_);
#line 1408 "Logger.c"
			}
#line 190 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1412 "Logger.c"
		}
#line 185 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_INFO:
#line 1416 "Logger.c"
		{
#line 192 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			if (PROTOCOL_BUS_TRACE_LEVEL_INFO <= self->priv->theTL) {
#line 1420 "Logger.c"
				FILE* _tmp5_;
				gchar* _tmp6_;
				gchar* _tmp7_;
				gchar* _tmp8_;
				gchar* _tmp9_;
#line 193 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp5_ = self->priv->arch;
#line 193 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp6_ = g_strconcat ("INFO:\t", trace, NULL);
#line 193 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp7_ = _tmp6_;
#line 193 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp8_ = g_strconcat (_tmp7_, "\n", NULL);
#line 193 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp9_ = _tmp8_;
#line 193 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				fputs (_tmp9_, _tmp5_);
#line 193 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_g_free0 (_tmp9_);
#line 193 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_g_free0 (_tmp7_);
#line 1442 "Logger.c"
			}
#line 195 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1446 "Logger.c"
		}
#line 185 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_WARNING:
#line 1450 "Logger.c"
		{
#line 197 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			if (PROTOCOL_BUS_TRACE_LEVEL_WARNING <= self->priv->theTL) {
#line 1454 "Logger.c"
				FILE* _tmp10_;
				gchar* _tmp11_;
				gchar* _tmp12_;
				gchar* _tmp13_;
				gchar* _tmp14_;
#line 198 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp10_ = self->priv->arch;
#line 198 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp11_ = g_strconcat ("WARN:\t", trace, NULL);
#line 198 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp12_ = _tmp11_;
#line 198 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp13_ = g_strconcat (_tmp12_, "\n", NULL);
#line 198 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp14_ = _tmp13_;
#line 198 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				fputs (_tmp14_, _tmp10_);
#line 198 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_g_free0 (_tmp14_);
#line 198 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_g_free0 (_tmp12_);
#line 1476 "Logger.c"
			}
#line 200 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1480 "Logger.c"
		}
#line 185 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_ERROR:
#line 1484 "Logger.c"
		{
#line 202 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			if (PROTOCOL_BUS_TRACE_LEVEL_ERROR <= self->priv->theTL) {
#line 1488 "Logger.c"
				FILE* _tmp15_;
				gchar* _tmp16_;
				gchar* _tmp17_;
				gchar* _tmp18_;
				gchar* _tmp19_;
#line 203 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp15_ = self->priv->arch;
#line 203 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp16_ = g_strconcat ("ERROR:\t", trace, NULL);
#line 203 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp17_ = _tmp16_;
#line 203 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp18_ = g_strconcat (_tmp17_, "\n", NULL);
#line 203 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp19_ = _tmp18_;
#line 203 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				fputs (_tmp19_, _tmp15_);
#line 203 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_g_free0 (_tmp19_);
#line 203 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_g_free0 (_tmp17_);
#line 1510 "Logger.c"
			}
#line 205 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1514 "Logger.c"
		}
		default:
#line 185 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		break;
#line 1519 "Logger.c"
	}
#line 207 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp20_ = self->priv->arch;
#line 207 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	fflush (_tmp20_);
#line 1525 "Logger.c"
}

static gchar*
protocol_bus_logger_PrepareTrace (ProtocolBusLogger* self,
                                  ProtocolBusTraceLevel tl,
                                  const gchar* trace)
{
	gchar* the_trace = NULL;
	gchar* _tmp0_;
	gchar* log_timestamp = NULL;
	GDateTime* _tmp11_;
	GDateTime* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	const gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* result;
#line 210 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 210 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_val_if_fail (trace != NULL, NULL);
#line 216 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = g_strdup ("");
#line 216 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	the_trace = _tmp0_;
#line 218 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	switch (tl) {
#line 218 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_TRACE:
#line 1557 "Logger.c"
		{
			const gchar* _tmp1_;
			gchar* _tmp2_;
#line 221 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp1_ = the_trace;
#line 221 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp2_ = g_strconcat (_tmp1_, trace, NULL);
#line 221 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (the_trace);
#line 221 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			the_trace = _tmp2_;
#line 222 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1571 "Logger.c"
		}
#line 218 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_INFO:
#line 1575 "Logger.c"
		{
			const gchar* _tmp3_;
			gchar* _tmp4_;
#line 225 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp3_ = the_trace;
#line 225 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp4_ = g_strconcat (_tmp3_, trace, NULL);
#line 225 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (the_trace);
#line 225 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			the_trace = _tmp4_;
#line 226 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1589 "Logger.c"
		}
#line 218 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_WARNING:
#line 1593 "Logger.c"
		{
			const gchar* _tmp5_;
			gchar* _tmp6_;
#line 229 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp5_ = the_trace;
#line 229 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp6_ = g_strconcat (_tmp5_, trace, NULL);
#line 229 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (the_trace);
#line 229 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			the_trace = _tmp6_;
#line 230 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1607 "Logger.c"
		}
#line 218 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_ERROR:
#line 1611 "Logger.c"
		{
			const gchar* _tmp7_;
			gchar* _tmp8_;
			gchar* _tmp9_;
			gchar* _tmp10_;
#line 236 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp7_ = the_trace;
#line 236 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp8_ = g_strconcat (trace, "\n\n\t", NULL);
#line 236 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp9_ = _tmp8_;
#line 236 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp10_ = g_strconcat (_tmp7_, _tmp9_, NULL);
#line 236 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (the_trace);
#line 236 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			the_trace = _tmp10_;
#line 236 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp9_);
#line 237 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1633 "Logger.c"
		}
		default:
#line 218 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		break;
#line 1638 "Logger.c"
	}
#line 240 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp11_ = g_date_time_new_now_local ();
#line 240 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp12_ = _tmp11_;
#line 240 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp13_ = g_date_time_format (_tmp12_, "%Y-%m-%d T %H:%M:%S.%f");
#line 240 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp14_ = _tmp13_;
#line 240 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_date_time_unref0 (_tmp12_);
#line 240 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	log_timestamp = _tmp14_;
#line 241 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp15_ = g_strconcat (log_timestamp, "\n\t", NULL);
#line 241 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp16_ = _tmp15_;
#line 241 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp17_ = the_trace;
#line 241 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp18_ = g_strconcat (_tmp16_, _tmp17_, NULL);
#line 241 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (the_trace);
#line 241 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	the_trace = _tmp18_;
#line 241 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp16_);
#line 242 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	result = the_trace;
#line 242 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (log_timestamp);
#line 242 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return result;
#line 1672 "Logger.c"
}

static gchar*
protocol_bus_logger_PrepareTraceWithErr (ProtocolBusLogger* self,
                                         ProtocolBusTraceLevel tl,
                                         const gchar* trace,
                                         GError* ex)
{
	gchar* the_trace = NULL;
	gchar* _tmp0_;
	gchar* log_timestamp = NULL;
	GDateTime* _tmp35_;
	GDateTime* _tmp36_;
	gchar* _tmp37_;
	gchar* _tmp38_;
	const gchar* _tmp39_;
	gchar* _tmp40_;
	gchar* _tmp41_;
	const gchar* _tmp42_;
	gchar* _tmp43_;
	gchar* result;
#line 245 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 245 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_val_if_fail (trace != NULL, NULL);
#line 245 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_return_val_if_fail (ex != NULL, NULL);
#line 250 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = g_strdup ("");
#line 250 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	the_trace = _tmp0_;
#line 252 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (ex == NULL) {
#line 1706 "Logger.c"
		gchar* _tmp1_;
#line 253 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp1_ = protocol_bus_logger_PrepareTraceWithErr (self, tl, trace, ex);
#line 253 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		result = _tmp1_;
#line 253 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_g_free0 (the_trace);
#line 253 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		return result;
#line 1716 "Logger.c"
	}
#line 256 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	switch (tl) {
#line 256 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_TRACE:
#line 1722 "Logger.c"
		{
			const gchar* _tmp2_;
			gchar* _tmp3_;
			gchar* _tmp4_;
			const gchar* _tmp5_;
			gchar* _tmp6_;
			gchar* _tmp7_;
			gchar* _tmp8_;
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp2_ = the_trace;
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp3_ = g_strconcat (trace, "\n\n\t", NULL);
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp4_ = _tmp3_;
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp5_ = ex->message;
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp6_ = g_strconcat (_tmp4_, _tmp5_, NULL);
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp7_ = _tmp6_;
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp8_ = g_strconcat (_tmp2_, _tmp7_, NULL);
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (the_trace);
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			the_trace = _tmp8_;
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp7_);
#line 259 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp4_);
#line 260 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1755 "Logger.c"
		}
#line 256 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_INFO:
#line 1759 "Logger.c"
		{
			const gchar* _tmp9_;
			gchar* _tmp10_;
			gchar* _tmp11_;
			const gchar* _tmp12_;
			gchar* _tmp13_;
			gchar* _tmp14_;
			gchar* _tmp15_;
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp9_ = the_trace;
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp10_ = g_strconcat (trace, "\n\n\t", NULL);
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp11_ = _tmp10_;
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp12_ = ex->message;
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp13_ = g_strconcat (_tmp11_, _tmp12_, NULL);
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp14_ = _tmp13_;
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp15_ = g_strconcat (_tmp9_, _tmp14_, NULL);
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (the_trace);
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			the_trace = _tmp15_;
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp14_);
#line 263 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp11_);
#line 264 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1792 "Logger.c"
		}
#line 256 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_WARNING:
#line 1796 "Logger.c"
		{
			const gchar* _tmp16_;
			gchar* _tmp17_;
			gchar* _tmp18_;
			const gchar* _tmp19_;
			gchar* _tmp20_;
			gchar* _tmp21_;
			gchar* _tmp22_;
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp16_ = the_trace;
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp17_ = g_strconcat (trace, "\n\n\t", NULL);
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp18_ = _tmp17_;
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp19_ = ex->message;
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp20_ = g_strconcat (_tmp18_, _tmp19_, NULL);
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp21_ = _tmp20_;
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp22_ = g_strconcat (_tmp16_, _tmp21_, NULL);
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (the_trace);
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			the_trace = _tmp22_;
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp21_);
#line 267 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp18_);
#line 268 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1829 "Logger.c"
		}
#line 256 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		case PROTOCOL_BUS_TRACE_LEVEL_ERROR:
#line 1833 "Logger.c"
		{
			const gchar* _tmp23_;
			gchar* _tmp24_;
			gchar* _tmp25_;
			const gchar* _tmp26_;
			gchar* _tmp27_;
			gchar* _tmp28_;
			gchar* _tmp29_;
			gchar* _tmp30_;
			const gchar* _tmp31_;
			gchar* _tmp32_;
			gchar* _tmp33_;
			gchar* _tmp34_;
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp23_ = the_trace;
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp24_ = g_strconcat (trace, "\n\t", NULL);
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp25_ = _tmp24_;
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp26_ = ex->message;
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp27_ = g_strconcat (_tmp25_, _tmp26_, NULL);
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp28_ = _tmp27_;
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp29_ = g_strconcat (_tmp28_, "\n\t", NULL);
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp30_ = _tmp29_;
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp31_ = ex->message;
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp32_ = g_strconcat (_tmp30_, _tmp31_, NULL);
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp33_ = _tmp32_;
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp34_ = g_strconcat (_tmp23_, _tmp33_, NULL);
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (the_trace);
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			the_trace = _tmp34_;
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp33_);
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp30_);
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp28_);
#line 271 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_g_free0 (_tmp25_);
#line 272 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			break;
#line 1885 "Logger.c"
		}
		default:
#line 256 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		break;
#line 1890 "Logger.c"
	}
#line 275 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp35_ = g_date_time_new_now_local ();
#line 275 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp36_ = _tmp35_;
#line 275 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp37_ = g_date_time_format (_tmp36_, "%Y-%m-%d T %H:%M:%S.%f");
#line 275 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp38_ = _tmp37_;
#line 275 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_date_time_unref0 (_tmp36_);
#line 275 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	log_timestamp = _tmp38_;
#line 276 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp39_ = log_timestamp;
#line 276 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp40_ = g_strconcat (_tmp39_, "\n\t", NULL);
#line 276 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp41_ = _tmp40_;
#line 276 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp42_ = the_trace;
#line 276 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp43_ = g_strconcat (_tmp41_, _tmp42_, NULL);
#line 276 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (the_trace);
#line 276 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	the_trace = _tmp43_;
#line 276 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp41_);
#line 277 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	result = the_trace;
#line 277 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (log_timestamp);
#line 277 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return result;
#line 1926 "Logger.c"
}

void
protocol_bus_logger_FinnishLog (void)
{
	ProtocolBusLogger* _tmp0_;
#line 281 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = protocol_bus_logger_instance;
#line 281 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	if (_tmp0_ != NULL) {
#line 1937 "Logger.c"
		gint a = 0;
		ProtocolBusLogger* _tmp7_;
		ProtocolBusManualResetEvent* _tmp8_;
#line 282 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		a = 0;
#line 283 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		while (TRUE) {
#line 1945 "Logger.c"
			gboolean _tmp1_ = FALSE;
			ProtocolBusLogger* _tmp2_;
			GAsyncQueue* _tmp3_;
			ProtocolBusLogger* _tmp5_;
			ProtocolBusManualResetEvent* _tmp6_;
#line 283 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp2_ = protocol_bus_logger_instance;
#line 283 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp3_ = _tmp2_->priv->myQueue;
#line 283 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			if (g_async_queue_length (_tmp3_) > 0) {
#line 1957 "Logger.c"
				gint _tmp4_;
#line 283 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp4_ = a;
#line 283 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				a = _tmp4_ + 1;
#line 283 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp1_ = _tmp4_ < 50;
#line 1965 "Logger.c"
			} else {
#line 283 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				_tmp1_ = FALSE;
#line 1969 "Logger.c"
			}
#line 283 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			if (!_tmp1_) {
#line 283 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
				break;
#line 1975 "Logger.c"
			}
#line 284 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp5_ = protocol_bus_logger_instance;
#line 284 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			_tmp6_ = _tmp5_->priv->elemsOnQueueEvt;
#line 284 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			protocol_bus_manual_reset_event_Set (_tmp6_);
#line 285 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
			g_usleep ((gulong) 50000);
#line 1985 "Logger.c"
		}
#line 287 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp7_ = protocol_bus_logger_instance;
#line 287 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		_tmp8_ = _tmp7_->priv->theFinishedAppEvt;
#line 287 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		protocol_bus_manual_reset_event_Set (_tmp8_);
#line 288 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
		g_usleep ((gulong) 150000);
#line 1995 "Logger.c"
	}
#line 290 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	return;
#line 1999 "Logger.c"
}

static void
protocol_bus_logger_class_init (ProtocolBusLoggerClass * klass,
                                gpointer klass_data)
{
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	protocol_bus_logger_parent_class = g_type_class_peek_parent (klass);
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_type_class_adjust_private_offset (klass, &ProtocolBusLogger_private_offset);
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	G_OBJECT_CLASS (klass)->finalize = protocol_bus_logger_finalize;
#line 2012 "Logger.c"
}

static void
protocol_bus_logger_instance_init (ProtocolBusLogger * self,
                                   gpointer klass)
{
	GDateTime* _tmp0_;
	GDateTime* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	GAsyncQueue* _tmp5_;
	ProtocolBusManualResetEvent* _tmp6_;
	ProtocolBusManualResetEvent* _tmp7_;
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv = protocol_bus_logger_get_instance_private (self);
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp1_ = _tmp0_;
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp2_ = g_date_time_format (_tmp1_, "%Y-%m-%d_%H_%M_%S");
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp3_ = _tmp2_;
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp4_ = g_strconcat (_tmp3_, ".log", NULL);
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->fileName = _tmp4_;
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (_tmp3_);
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_date_time_unref0 (_tmp1_);
#line 70 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_rec_mutex_init (&self->priv->__lock_myQueue);
#line 70 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp5_ = g_async_queue_new_full (_protocol_bus_pair_unref0_);
#line 70 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->myQueue = _tmp5_;
#line 72 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->theTL = PROTOCOL_BUS_TRACE_LEVEL_ERROR;
#line 74 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->isStarted = FALSE;
#line 76 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp6_ = protocol_bus_manual_reset_event_new ();
#line 76 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->theFinishedAppEvt = _tmp6_;
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_tmp7_ = protocol_bus_manual_reset_event_new ();
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->elemsOnQueueEvt = _tmp7_;
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->priv->isOwnTrace = FALSE;
#line 2065 "Logger.c"
}

static void
protocol_bus_logger_finalize (GObject * obj)
{
	ProtocolBusLogger * self;
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PROTOCOL_BUS_TYPE_LOGGER, ProtocolBusLogger);
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_free0 (self->priv->fileName);
#line 70 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	g_rec_mutex_clear (&self->priv->__lock_myQueue);
#line 70 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_async_queue_unref0 (self->priv->myQueue);
#line 71 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_fclose0 (self->priv->arch);
#line 75 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_thread_unref0 (self->priv->myThread);
#line 76 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_object_unref0 (self->priv->theFinishedAppEvt);
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	_g_object_unref0 (self->priv->elemsOnQueueEvt);
#line 81 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	self->ContinueWH = (_vala_array_free (self->ContinueWH, self->ContinueWH_length1, (GDestroyNotify) g_object_unref), NULL);
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/Logger.vala"
	G_OBJECT_CLASS (protocol_bus_logger_parent_class)->finalize (obj);
#line 2092 "Logger.c"
}

static GType
protocol_bus_logger_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ProtocolBusLoggerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) protocol_bus_logger_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ProtocolBusLogger), 0, (GInstanceInitFunc) protocol_bus_logger_instance_init, NULL };
	GType protocol_bus_logger_type_id;
	protocol_bus_logger_type_id = g_type_register_static (G_TYPE_OBJECT, "ProtocolBusLogger", &g_define_type_info, 0);
	ProtocolBusLogger_private_offset = g_type_add_instance_private (protocol_bus_logger_type_id, sizeof (ProtocolBusLoggerPrivate));
	return protocol_bus_logger_type_id;
}

GType
protocol_bus_logger_get_type (void)
{
	static volatile gsize protocol_bus_logger_type_id__once = 0;
	if (g_once_init_enter (&protocol_bus_logger_type_id__once)) {
		GType protocol_bus_logger_type_id;
		protocol_bus_logger_type_id = protocol_bus_logger_get_type_once ();
		g_once_init_leave (&protocol_bus_logger_type_id__once, protocol_bus_logger_type_id);
	}
	return protocol_bus_logger_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if ((array != NULL) && (destroy_func != NULL)) {
#line 2124 "Logger.c"
		gssize i;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		for (i = 0; i < array_length; i = i + 1) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			if (((gpointer*) array)[i] != NULL) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
				destroy_func (((gpointer*) array)[i]);
#line 2132 "Logger.c"
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	_vala_array_destroy (array, array_length, destroy_func);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	g_free (array);
#line 2147 "Logger.c"
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (array) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		while (((gpointer*) array)[length]) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
			length++;
#line 2161 "Logger.c"
		}
	}
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return length;
#line 2166 "Logger.c"
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (mem && byte_size != 0) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		new_mem = g_malloc (byte_size);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		memcpy (new_mem, mem, byte_size);
#line 2180 "Logger.c"
	} else {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		new_mem = NULL;
#line 2184 "Logger.c"
	}
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return new_mem;
#line 2188 "Logger.c"
}

