/* MCastTransp.c generated by valac 0.56.0, the Vala compiler
 * generated from MCastTransp.vala, do not modify */

#include "protocolbus.h"
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <unistd.h>
#include <sys/socket.h>

#define PROTOCOL_BUS_TYPE_MCAST_TRANSP (protocol_bus_mcast_transp_get_type ())
#define PROTOCOL_BUS_MCAST_TRANSP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_MCAST_TRANSP, ProtocolBusMCastTransp))
#define PROTOCOL_BUS_MCAST_TRANSP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_MCAST_TRANSP, ProtocolBusMCastTranspClass))
#define PROTOCOL_BUS_IS_MCAST_TRANSP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_MCAST_TRANSP))
#define PROTOCOL_BUS_IS_MCAST_TRANSP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_MCAST_TRANSP))
#define PROTOCOL_BUS_MCAST_TRANSP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_MCAST_TRANSP, ProtocolBusMCastTranspClass))

typedef struct _ProtocolBusMCastTransp ProtocolBusMCastTransp;
typedef struct _ProtocolBusMCastTranspClass ProtocolBusMCastTranspClass;
typedef struct _ProtocolBusMCastTranspPrivate ProtocolBusMCastTranspPrivate;

#define PROTOCOL_BUS_TYPE_BCAST_TRANSP (protocol_bus_bcast_transp_get_type ())
#define PROTOCOL_BUS_BCAST_TRANSP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_BCAST_TRANSP, ProtocolBusBCastTransp))
#define PROTOCOL_BUS_BCAST_TRANSP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_BCAST_TRANSP, ProtocolBusBCastTranspClass))
#define PROTOCOL_BUS_IS_BCAST_TRANSP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_BCAST_TRANSP))
#define PROTOCOL_BUS_IS_BCAST_TRANSP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_BCAST_TRANSP))
#define PROTOCOL_BUS_BCAST_TRANSP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_BCAST_TRANSP, ProtocolBusBCastTranspClass))

typedef struct _ProtocolBusBCastTransp ProtocolBusBCastTransp;
typedef struct _ProtocolBusBCastTranspClass ProtocolBusBCastTranspClass;
typedef struct _ProtocolBusBCastTranspPrivate ProtocolBusBCastTranspPrivate;
enum  {
	PROTOCOL_BUS_BCAST_TRANSP_0_PROPERTY,
	PROTOCOL_BUS_BCAST_TRANSP_NUM_PROPERTIES
};
static GParamSpec* protocol_bus_bcast_transp_properties[PROTOCOL_BUS_BCAST_TRANSP_NUM_PROPERTIES];

#define PROTOCOL_BUS_TYPE_DOMAIN (protocol_bus_domain_get_type ())
#define PROTOCOL_BUS_DOMAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_DOMAIN, ProtocolBusDomain))
#define PROTOCOL_BUS_DOMAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_DOMAIN, ProtocolBusDomainClass))
#define PROTOCOL_BUS_IS_DOMAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_DOMAIN))
#define PROTOCOL_BUS_IS_DOMAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_DOMAIN))
#define PROTOCOL_BUS_DOMAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_DOMAIN, ProtocolBusDomainClass))

typedef struct _ProtocolBusDomain ProtocolBusDomain;
typedef struct _ProtocolBusDomainClass ProtocolBusDomainClass;
enum  {
	PROTOCOL_BUS_MCAST_TRANSP_0_PROPERTY,
	PROTOCOL_BUS_MCAST_TRANSP_NUM_PROPERTIES
};
static GParamSpec* protocol_bus_mcast_transp_properties[PROTOCOL_BUS_MCAST_TRANSP_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _Block2Data Block2Data;
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _g_source_unref0(var) ((var == NULL) ? NULL : (var = (g_source_unref (var), NULL)))
#define _g_thread_unref0(var) ((var == NULL) ? NULL : (var = (g_thread_unref (var), NULL)))
#define _g_main_context_unref0(var) ((var == NULL) ? NULL : (var = (g_main_context_unref (var), NULL)))
#define _g_bytes_unref0(var) ((var == NULL) ? NULL : (var = (g_bytes_unref (var), NULL)))

struct _ProtocolBusMCastTransp {
	ProtocolBusTransport parent_instance;
	ProtocolBusMCastTranspPrivate * priv;
};

struct _ProtocolBusMCastTranspClass {
	ProtocolBusTransportClass parent_class;
};

struct _ProtocolBusBCastTransp {
	ProtocolBusMCastTransp parent_instance;
	ProtocolBusBCastTranspPrivate * priv;
};

struct _ProtocolBusBCastTranspClass {
	ProtocolBusMCastTranspClass parent_class;
};

struct _ProtocolBusMCastTranspPrivate {
	GSocket* SendingSocket;
	GSocket* ListeningSocket;
	gint TTL;
	gint SendBuffer;
	gint ReceiveBuffer;
	gboolean isBroadcast;
	gchar* LocalStrAddr;
	GInetAddress* LocalAddr;
	GInetSocketAddress* LocalSoxAddr;
	gint LocalPort;
	gchar* MCastStrAddr;
	GInetAddress* MCastAddr;
	GInetSocketAddress* MCastSoxAddr;
	guint16 MCastPort;
};

struct _Block2Data {
	int _ref_count_;
	ProtocolBusMCastTransp* self;
	GCancellable* kancel;
	GMainLoop* loop;
};

static gpointer protocol_bus_bcast_transp_parent_class = NULL;
static gint ProtocolBusMCastTransp_private_offset;
static gpointer protocol_bus_mcast_transp_parent_class = NULL;

VALA_EXTERN GType protocol_bus_mcast_transp_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType protocol_bus_bcast_transp_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType protocol_bus_domain_get_type (void) G_GNUC_CONST ;
VALA_EXTERN ProtocolBusBCastTransp* protocol_bus_bcast_transp_new (ProtocolBusDomain* domain,
                                                       const gchar* name,
                                                       ProtocolBusBCastDefConfig* bcd,
                                                       gboolean rom);
VALA_EXTERN ProtocolBusBCastTransp* protocol_bus_bcast_transp_construct (GType object_type,
                                                             ProtocolBusDomain* domain,
                                                             const gchar* name,
                                                             ProtocolBusBCastDefConfig* bcd,
                                                             gboolean rom);
VALA_EXTERN ProtocolBusMCastTransp* protocol_bus_mcast_transp_new_Broadcast (ProtocolBusDomain* domain,
                                                                 const gchar* name,
                                                                 ProtocolBusBCastDefConfig* bcd,
                                                                 gboolean rom);
VALA_EXTERN ProtocolBusMCastTransp* protocol_bus_mcast_transp_construct_Broadcast (GType object_type,
                                                                       ProtocolBusDomain* domain,
                                                                       const gchar* name,
                                                                       ProtocolBusBCastDefConfig* bcd,
                                                                       gboolean rom);
static GType protocol_bus_bcast_transp_get_type_once (void);
VALA_EXTERN ProtocolBusMCastTransp* protocol_bus_mcast_transp_new (ProtocolBusDomain* domain,
                                                       const gchar* name);
VALA_EXTERN ProtocolBusMCastTransp* protocol_bus_mcast_transp_construct (GType object_type,
                                                             ProtocolBusDomain* domain,
                                                             const gchar* name);
VALA_EXTERN void protocol_bus_mcast_transp_Initialize (ProtocolBusMCastTransp* self);
VALA_EXTERN ProtocolBusMCastTransp* protocol_bus_mcast_transp_new_Extd (ProtocolBusDomain* domain,
                                                            const gchar* name,
                                                            ProtocolBusMCastDefConfig* mcd,
                                                            gboolean rom);
VALA_EXTERN ProtocolBusMCastTransp* protocol_bus_mcast_transp_construct_Extd (GType object_type,
                                                                  ProtocolBusDomain* domain,
                                                                  const gchar* name,
                                                                  ProtocolBusMCastDefConfig* mcd,
                                                                  gboolean rom);
VALA_EXTERN void protocol_bus_mcast_transp_InitializeSocket (ProtocolBusMCastTransp* self,
                                                 GSocket* theSocket,
                                                 gboolean IsSendingSocket);
static gboolean protocol_bus_mcast_transp_real_SendBytes (ProtocolBusTransport* base,
                                                   GBytes* data);
static void protocol_bus_mcast_transp_real_MainLoop (ProtocolBusTransport* base);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda7_ (Block2Data* _data2_);
static gpointer ___lambda7__gthread_func (gpointer self);
static gboolean __lambda8_ (Block2Data* _data2_,
                     GSocket* s,
                     GIOCondition cond);
static void protocol_bus_mcast_transp_Receive (ProtocolBusMCastTransp* self,
                                        GCancellable* k);
static gboolean ___lambda8__gsocket_source_func (GSocket* socket,
                                          GIOCondition condition,
                                          gpointer self);
static guint8* _vala_array_dup4 (guint8* self,
                          gssize length);
static void protocol_bus_mcast_transp_finalize (GObject * obj);
static GType protocol_bus_mcast_transp_get_type_once (void);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

ProtocolBusBCastTransp*
protocol_bus_bcast_transp_construct (GType object_type,
                                     ProtocolBusDomain* domain,
                                     const gchar* name,
                                     ProtocolBusBCastDefConfig* bcd,
                                     gboolean rom)
{
	ProtocolBusBCastTransp * self = NULL;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (domain != NULL, NULL);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (bcd != NULL, NULL);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self = (ProtocolBusBCastTransp*) protocol_bus_mcast_transp_construct_Broadcast (object_type, domain, name, bcd, rom);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return self;
#line 191 "MCastTransp.c"
}

ProtocolBusBCastTransp*
protocol_bus_bcast_transp_new (ProtocolBusDomain* domain,
                               const gchar* name,
                               ProtocolBusBCastDefConfig* bcd,
                               gboolean rom)
{
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return protocol_bus_bcast_transp_construct (PROTOCOL_BUS_TYPE_BCAST_TRANSP, domain, name, bcd, rom);
#line 202 "MCastTransp.c"
}

static void
protocol_bus_bcast_transp_class_init (ProtocolBusBCastTranspClass * klass,
                                      gpointer klass_data)
{
#line 6 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_bcast_transp_parent_class = g_type_class_peek_parent (klass);
#line 211 "MCastTransp.c"
}

static void
protocol_bus_bcast_transp_instance_init (ProtocolBusBCastTransp * self,
                                         gpointer klass)
{
}

static GType
protocol_bus_bcast_transp_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ProtocolBusBCastTranspClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) protocol_bus_bcast_transp_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ProtocolBusBCastTransp), 0, (GInstanceInitFunc) protocol_bus_bcast_transp_instance_init, NULL };
	GType protocol_bus_bcast_transp_type_id;
	protocol_bus_bcast_transp_type_id = g_type_register_static (PROTOCOL_BUS_TYPE_MCAST_TRANSP, "ProtocolBusBCastTransp", &g_define_type_info, 0);
	return protocol_bus_bcast_transp_type_id;
}

GType
protocol_bus_bcast_transp_get_type (void)
{
	static volatile gsize protocol_bus_bcast_transp_type_id__once = 0;
	if (g_once_init_enter (&protocol_bus_bcast_transp_type_id__once)) {
		GType protocol_bus_bcast_transp_type_id;
		protocol_bus_bcast_transp_type_id = protocol_bus_bcast_transp_get_type_once ();
		g_once_init_leave (&protocol_bus_bcast_transp_type_id__once, protocol_bus_bcast_transp_type_id);
	}
	return protocol_bus_bcast_transp_type_id__once;
}

static inline gpointer
protocol_bus_mcast_transp_get_instance_private (ProtocolBusMCastTransp* self)
{
	return G_STRUCT_MEMBER_P (self, ProtocolBusMCastTransp_private_offset);
}

ProtocolBusMCastTransp*
protocol_bus_mcast_transp_construct (GType object_type,
                                     ProtocolBusDomain* domain,
                                     const gchar* name)
{
	ProtocolBusMCastTransp * self = NULL;
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (domain != NULL, NULL);
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 33 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self = (ProtocolBusMCastTransp*) protocol_bus_transport_construct (object_type, domain, name);
#line 34 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_mcast_transp_Initialize (self);
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return self;
#line 263 "MCastTransp.c"
}

ProtocolBusMCastTransp*
protocol_bus_mcast_transp_new (ProtocolBusDomain* domain,
                               const gchar* name)
{
#line 32 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return protocol_bus_mcast_transp_construct (PROTOCOL_BUS_TYPE_MCAST_TRANSP, domain, name);
#line 272 "MCastTransp.c"
}

ProtocolBusMCastTransp*
protocol_bus_mcast_transp_construct_Extd (GType object_type,
                                          ProtocolBusDomain* domain,
                                          const gchar* name,
                                          ProtocolBusMCastDefConfig* mcd,
                                          gboolean rom)
{
	ProtocolBusMCastTransp * self = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
#line 37 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (domain != NULL, NULL);
#line 37 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 37 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (mcd != NULL, NULL);
#line 38 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self = (ProtocolBusMCastTransp*) protocol_bus_transport_construct (object_type, domain, name);
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp0_ = mcd->MCastAddress;
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (self->priv->MCastStrAddr);
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->MCastStrAddr = _tmp1_;
#line 40 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->MCastPort = (guint16) mcd->Port;
#line 41 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->SendBuffer = (gint) mcd->SendBuffer;
#line 42 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->ReceiveBuffer = (gint) mcd->ReceiveBuffer;
#line 43 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->TTL = (gint) mcd->TTL;
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp2_ = mcd->LocalAddress;
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (self->priv->LocalStrAddr);
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->LocalStrAddr = _tmp3_;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	((ProtocolBusTransport*) self)->ReceiveOwnMessages = rom;
#line 47 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_mcast_transp_Initialize (self);
#line 37 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return self;
#line 325 "MCastTransp.c"
}

ProtocolBusMCastTransp*
protocol_bus_mcast_transp_new_Extd (ProtocolBusDomain* domain,
                                    const gchar* name,
                                    ProtocolBusMCastDefConfig* mcd,
                                    gboolean rom)
{
#line 37 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return protocol_bus_mcast_transp_construct_Extd (PROTOCOL_BUS_TYPE_MCAST_TRANSP, domain, name, mcd, rom);
#line 336 "MCastTransp.c"
}

ProtocolBusMCastTransp*
protocol_bus_mcast_transp_construct_Broadcast (GType object_type,
                                               ProtocolBusDomain* domain,
                                               const gchar* name,
                                               ProtocolBusBCastDefConfig* bcd,
                                               gboolean rom)
{
	ProtocolBusMCastTransp * self = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (domain != NULL, NULL);
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (bcd != NULL, NULL);
#line 51 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self = (ProtocolBusMCastTransp*) protocol_bus_transport_construct (object_type, domain, name);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp0_ = bcd->BCastAddress;
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (self->priv->MCastStrAddr);
#line 52 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->MCastStrAddr = _tmp1_;
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->MCastPort = (guint16) bcd->Port;
#line 54 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->SendBuffer = (gint) bcd->SendBuffer;
#line 55 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->ReceiveBuffer = (gint) bcd->ReceiveBuffer;
#line 56 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->isBroadcast = TRUE;
#line 57 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp2_ = bcd->LocalAddress;
#line 57 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 57 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (self->priv->LocalStrAddr);
#line 57 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->LocalStrAddr = _tmp3_;
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	((ProtocolBusTransport*) self)->ReceiveOwnMessages = rom;
#line 60 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_mcast_transp_Initialize (self);
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return self;
#line 389 "MCastTransp.c"
}

ProtocolBusMCastTransp*
protocol_bus_mcast_transp_new_Broadcast (ProtocolBusDomain* domain,
                                         const gchar* name,
                                         ProtocolBusBCastDefConfig* bcd,
                                         gboolean rom)
{
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return protocol_bus_mcast_transp_construct_Broadcast (PROTOCOL_BUS_TYPE_MCAST_TRANSP, domain, name, bcd, rom);
#line 400 "MCastTransp.c"
}

void
protocol_bus_mcast_transp_Initialize (ProtocolBusMCastTransp* self)
{
	GSocket* _tmp0_ = NULL;
	GSocket* _tmp1_;
	GSocket* _tmp2_;
	GSocket* _tmp3_ = NULL;
	GSocket* _tmp4_;
	GSocket* _tmp5_;
	GSocket* _tmp6_;
	GSocket* _tmp7_;
	GError* _inner_error0_ = NULL;
#line 63 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_if_fail (self != NULL);
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp1_ = g_socket_new (G_SOCKET_FAMILY_IPV4, G_SOCKET_TYPE_DATAGRAM, G_SOCKET_PROTOCOL_UDP, &_inner_error0_);
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp0_ = _tmp1_;
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_clear_error (&_inner_error0_);
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		return;
#line 429 "MCastTransp.c"
	}
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp2_ = _tmp0_;
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp0_ = NULL;
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (self->priv->SendingSocket);
#line 64 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->SendingSocket = _tmp2_;
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp4_ = g_socket_new (G_SOCKET_FAMILY_IPV4, G_SOCKET_TYPE_DATAGRAM, G_SOCKET_PROTOCOL_UDP, &_inner_error0_);
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp3_ = _tmp4_;
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_object_unref0 (_tmp0_);
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_clear_error (&_inner_error0_);
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		return;
#line 453 "MCastTransp.c"
	}
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp5_ = _tmp3_;
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp3_ = NULL;
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (self->priv->ListeningSocket);
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->ListeningSocket = _tmp5_;
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp6_ = self->priv->SendingSocket;
#line 67 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_mcast_transp_InitializeSocket (self, _tmp6_, TRUE);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp7_ = self->priv->ListeningSocket;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_mcast_transp_InitializeSocket (self, _tmp7_, FALSE);
#line 70 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_transport_StartMainLoop ((ProtocolBusTransport*) self);
#line 63 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (_tmp3_);
#line 63 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (_tmp0_);
#line 477 "MCastTransp.c"
}

void
protocol_bus_mcast_transp_InitializeSocket (ProtocolBusMCastTransp* self,
                                            GSocket* theSocket,
                                            gboolean IsSendingSocket)
{
	GError* _inner_error0_ = NULL;
#line 73 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_if_fail (self != NULL);
#line 73 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_if_fail (theSocket != NULL);
#line 490 "MCastTransp.c"
	{
		guint16 localport = 0U;
		const gchar* _tmp0_;
		GInetAddress* _tmp1_;
		const gchar* _tmp4_;
		GInetAddress* _tmp5_;
		GInetAddress* _tmp6_;
		GInetSocketAddress* _tmp7_;
		GInetSocketAddress* _tmp8_;
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp0_ = self->priv->MCastStrAddr;
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp1_ = g_inet_address_new_from_string (_tmp0_);
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_object_unref0 (self->priv->MCastAddr);
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		self->priv->MCastAddr = _tmp1_;
#line 78 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		if (IsSendingSocket) {
#line 510 "MCastTransp.c"
			GInetAddress* _tmp2_;
			GInetSocketAddress* _tmp3_;
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			localport = (guint16) (50000 + (getpid () % 14000));
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			self->priv->LocalPort = (gint) localport;
#line 80 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			_tmp2_ = self->priv->MCastAddr;
#line 80 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			_tmp3_ = (GInetSocketAddress*) g_inet_socket_address_new (_tmp2_, self->priv->MCastPort);
#line 80 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			_g_object_unref0 (self->priv->MCastSoxAddr);
#line 80 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			self->priv->MCastSoxAddr = _tmp3_;
#line 525 "MCastTransp.c"
		} else {
#line 83 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			localport = self->priv->MCastPort;
#line 529 "MCastTransp.c"
		}
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp4_ = self->priv->LocalStrAddr;
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp5_ = protocol_bus_transport_GetLocalAddress ((ProtocolBusTransport*) self, _tmp4_);
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_object_unref0 (self->priv->LocalAddr);
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		self->priv->LocalAddr = _tmp5_;
#line 86 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp6_ = self->priv->LocalAddr;
#line 86 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp7_ = (GInetSocketAddress*) g_inet_socket_address_new (_tmp6_, localport);
#line 86 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_object_unref0 (self->priv->LocalSoxAddr);
#line 86 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		self->priv->LocalSoxAddr = _tmp7_;
#line 88 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_socket_set_option (theSocket, SOL_SOCKET, SO_RCVBUF, self->priv->ReceiveBuffer, &_inner_error0_);
#line 88 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 551 "MCastTransp.c"
			goto __catch0_g_error;
		}
#line 89 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_socket_set_option (theSocket, SOL_SOCKET, SO_SNDBUF, self->priv->SendBuffer, &_inner_error0_);
#line 89 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 558 "MCastTransp.c"
			goto __catch0_g_error;
		}
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_socket_set_option (theSocket, SOL_SOCKET, SO_REUSEADDR, 1, &_inner_error0_);
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 565 "MCastTransp.c"
			goto __catch0_g_error;
		}
#line 92 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp8_ = self->priv->LocalSoxAddr;
#line 92 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_socket_bind (theSocket, (GSocketAddress*) _tmp8_, TRUE, &_inner_error0_);
#line 92 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 574 "MCastTransp.c"
			goto __catch0_g_error;
		}
#line 95 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		if (!self->priv->isBroadcast) {
#line 579 "MCastTransp.c"
			GInetAddress* _tmp9_;
#line 96 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			g_socket_set_multicast_loopback (theSocket, TRUE);
#line 101 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			g_socket_set_multicast_ttl (theSocket, (guint) self->priv->TTL);
#line 104 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			_tmp9_ = self->priv->MCastAddr;
#line 104 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			g_socket_join_multicast_group (theSocket, _tmp9_, FALSE, NULL, &_inner_error0_);
#line 104 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 591 "MCastTransp.c"
				goto __catch0_g_error;
			}
		} else {
#line 107 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			g_socket_set_broadcast (theSocket, TRUE);
#line 597 "MCastTransp.c"
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* ex = NULL;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		gchar* _tmp16_;
		gchar* _tmp17_;
		gchar* _tmp18_;
		gchar* _tmp19_;
		const gchar* _tmp20_;
		const gchar* _tmp21_;
		gchar* _tmp22_;
		gchar* _tmp23_;
		gchar* _tmp24_;
		gchar* _tmp25_;
		gchar* _tmp26_;
		gchar* _tmp27_;
		GError* _tmp28_;
#line 74 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		ex = _inner_error0_;
#line 74 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_inner_error0_ = NULL;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp10_ = g_strdup_printf ("%i", 110);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp11_ = _tmp10_;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp12_ = g_strconcat ("MCastTransp.vala" ", L-", _tmp11_, NULL);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp13_ = _tmp12_;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp14_ = g_strconcat (_tmp13_, ": ", NULL);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp15_ = _tmp14_;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp16_ = g_strconcat (_tmp15_, "ProtocolBus.MCastTransp.InitializeSocket", NULL);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp17_ = _tmp16_;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp18_ = g_strconcat (_tmp17_, "-->", NULL);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp19_ = _tmp18_;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp20_ = protocol_bus_transport_get_Name ((ProtocolBusTransport*) self);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp21_ = _tmp20_;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp22_ = g_strconcat (_tmp19_, _tmp21_, NULL);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp23_ = _tmp22_;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp24_ = g_strconcat (_tmp23_, ": ", NULL);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp25_ = _tmp24_;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp26_ = g_strconcat (_tmp25_, "no catch comment", NULL);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp27_ = _tmp26_;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp28_ = ex;
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		protocol_bus_ilogger_LoggerTraceWithErr ((ProtocolBusILogger*) self, PROTOCOL_BUS_TRACE_LEVEL_ERROR, _tmp27_, _tmp28_);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp27_);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp25_);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp23_);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp19_);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp17_);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp15_);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp13_);
#line 110 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp11_);
#line 74 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_error_free0 (ex);
#line 685 "MCastTransp.c"
	}
	__finally0:
#line 74 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 74 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 74 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_clear_error (&_inner_error0_);
#line 74 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		return;
#line 696 "MCastTransp.c"
	}
}

static gint
_vala_g_bytes_get_length (GBytes* self)
{
	gint result;
#line 5832 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 5834 "glib-2.0.vapi"
	result = (gint) g_bytes_get_size (self);
#line 5834 "glib-2.0.vapi"
	return result;
#line 710 "MCastTransp.c"
}

static gboolean
protocol_bus_mcast_transp_real_SendBytes (ProtocolBusTransport* base,
                                          GBytes* data)
{
	ProtocolBusMCastTransp * self;
	gint _tmp0_;
	gint _tmp1_;
	GError* _inner_error0_ = NULL;
	gboolean result;
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self = (ProtocolBusMCastTransp*) base;
#line 114 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (data != NULL, FALSE);
#line 115 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp0_ = _vala_g_bytes_get_length (data);
#line 115 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp1_ = _tmp0_;
#line 115 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	if (_tmp1_ > 64000) {
#line 116 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		protocol_bus_ilogger_LoggerTrace ((ProtocolBusILogger*) self, PROTOCOL_BUS_TRACE_LEVEL_ERROR, "Serialized packet bigger than 60Kb .. dismissed");
#line 117 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		result = FALSE;
#line 117 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		return result;
#line 738 "MCastTransp.c"
	}
	{
		GSocket* _tmp2_;
		GInetSocketAddress* _tmp3_;
		gsize _tmp4_ = 0;
		guint8* _tmp5_;
#line 121 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp2_ = self->priv->SendingSocket;
#line 121 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp3_ = self->priv->MCastSoxAddr;
#line 121 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp5_ = g_bytes_get_data (data, &_tmp4_);
#line 121 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_socket_send_to (_tmp2_, (GSocketAddress*) _tmp3_, _tmp5_, (gsize) _tmp4_, NULL, &_inner_error0_);
#line 121 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 755 "MCastTransp.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* ex = NULL;
		GError* _tmp6_;
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		ex = _inner_error0_;
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_inner_error0_ = NULL;
#line 124 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp6_ = ex;
#line 124 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		protocol_bus_ilogger_LoggerTraceWithErr ((ProtocolBusILogger*) self, PROTOCOL_BUS_TRACE_LEVEL_ERROR, "Error in SendPck. ", _tmp6_);
#line 125 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		result = FALSE;
#line 125 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_error_free0 (ex);
#line 125 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		return result;
#line 778 "MCastTransp.c"
	}
	__finally0:
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 783 "MCastTransp.c"
		gboolean _tmp7_ = FALSE;
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_clear_error (&_inner_error0_);
#line 120 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		return _tmp7_;
#line 791 "MCastTransp.c"
	}
#line 128 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	result = TRUE;
#line 128 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return result;
#line 797 "MCastTransp.c"
}

static Block2Data*
block2_data_ref (Block2Data* _data2_)
{
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return _data2_;
#line 807 "MCastTransp.c"
}

static void
block2_data_unref (void * _userdata_)
{
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 817 "MCastTransp.c"
		ProtocolBusMCastTransp* self;
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		self = _data2_->self;
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_main_loop_unref0 (_data2_->loop);
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_object_unref0 (_data2_->kancel);
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_object_unref0 (self);
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_slice_free (Block2Data, _data2_);
#line 829 "MCastTransp.c"
	}
}

static void
__lambda7_ (Block2Data* _data2_)
{
	ProtocolBusMCastTransp* self;
	ProtocolBusAppSync* _tmp0_;
	ProtocolBusManualResetEvent* _tmp1_;
	ProtocolBusManualResetEvent* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	const gchar* _tmp13_;
	const gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	const gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* _tmp23_;
#line 140 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self = _data2_->self;
#line 141 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp0_ = ((ProtocolBusTransport*) self)->theSync;
#line 141 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp1_ = protocol_bus_app_sync_GetFinishedWH (_tmp0_);
#line 141 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp2_ = _tmp1_;
#line 141 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_wait_handle_Wait ((ProtocolBusWaitHandle*) _tmp2_);
#line 141 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (_tmp2_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp3_ = g_strdup_printf ("%i", 142);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp4_ = _tmp3_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp5_ = g_strconcat ("MCastTransp.vala" ", L-", _tmp4_, NULL);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp6_ = _tmp5_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp7_ = g_strconcat (_tmp6_, ": ", NULL);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp8_ = _tmp7_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp9_ = g_strconcat (_tmp8_, "ProtocolBus.MCastTransp.MainLoop._lambda7_", NULL);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp10_ = _tmp9_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp11_ = g_strconcat (_tmp10_, "-->", NULL);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp12_ = _tmp11_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp13_ = protocol_bus_transport_get_Name ((ProtocolBusTransport*) self);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp14_ = _tmp13_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp15_ = g_strconcat (_tmp12_, _tmp14_, NULL);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp16_ = _tmp15_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp17_ = g_strconcat (_tmp16_, ": ", NULL);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp18_ = _tmp17_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp19_ = g_strconcat (_tmp18_, " Transp. auxLoop finished -", NULL);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp20_ = _tmp19_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp21_ = g_type_name (G_TYPE_FROM_INSTANCE ((GObject*) self));
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp22_ = g_strconcat (_tmp20_, _tmp21_, NULL);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp23_ = _tmp22_;
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_ilogger_LoggerTrace ((ProtocolBusILogger*) self, PROTOCOL_BUS_TRACE_LEVEL_INFO, _tmp23_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp23_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp20_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp18_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp16_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp12_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp10_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp8_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp6_);
#line 142 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp4_);
#line 144 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_cancellable_cancel (_data2_->kancel);
#line 145 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_main_loop_quit (_data2_->loop);
#line 939 "MCastTransp.c"
}

static gpointer
___lambda7__gthread_func (gpointer self)
{
	gpointer result;
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	__lambda7_ (self);
#line 948 "MCastTransp.c"
	result = NULL;
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	block2_data_unref (self);
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return result;
#line 954 "MCastTransp.c"
}

static gboolean
__lambda8_ (Block2Data* _data2_,
            GSocket* s,
            GIOCondition cond)
{
	ProtocolBusMCastTransp* self;
	gboolean result;
#line 149 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self = _data2_->self;
#line 149 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_val_if_fail (s != NULL, FALSE);
#line 150 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_mcast_transp_Receive (self, _data2_->kancel);
#line 151 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	result = TRUE;
#line 151 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return result;
#line 974 "MCastTransp.c"
}

static gboolean
___lambda8__gsocket_source_func (GSocket* socket,
                                 GIOCondition condition,
                                 gpointer self)
{
	gboolean result;
	result = __lambda8_ (self, socket, condition);
#line 149 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return result;
#line 986 "MCastTransp.c"
}

static void
protocol_bus_mcast_transp_real_MainLoop (ProtocolBusTransport* base)
{
	ProtocolBusMCastTransp * self;
	Block2Data* _data2_;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	const gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	GCancellable* _tmp21_;
	GMainContext* ctx = NULL;
	GMainContext* _tmp22_;
	GMainLoop* _tmp23_;
	GThread* aux = NULL;
	const gchar* _tmp24_;
	const gchar* _tmp25_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	GThread* _tmp28_;
	GThread* _tmp29_;
	GSource* source = NULL;
	GSocket* _tmp30_;
	GSource* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	gchar* _tmp34_;
	gchar* _tmp35_;
	gchar* _tmp36_;
	gchar* _tmp37_;
	gchar* _tmp38_;
	gchar* _tmp39_;
	gchar* _tmp40_;
	gchar* _tmp41_;
	const gchar* _tmp42_;
	const gchar* _tmp43_;
	gchar* _tmp44_;
	gchar* _tmp45_;
	gchar* _tmp46_;
	gchar* _tmp47_;
	gchar* _tmp48_;
	gchar* _tmp49_;
	const gchar* _tmp50_;
	gchar* _tmp51_;
	gchar* _tmp52_;
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self = (ProtocolBusMCastTransp*) base;
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_data2_ = g_slice_new0 (Block2Data);
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_data2_->_ref_count_ = 1;
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_data2_->self = g_object_ref (self);
#line 132 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	((ProtocolBusTransport*) self)->isStarted = TRUE;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp0_ = g_strdup_printf ("%i", 133);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp1_ = _tmp0_;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp2_ = g_strconcat ("MCastTransp.vala" ", L-", _tmp1_, NULL);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp3_ = _tmp2_;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp4_ = g_strconcat (_tmp3_, ": ", NULL);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp5_ = _tmp4_;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp6_ = g_strconcat (_tmp5_, "ProtocolBus.MCastTransp.MainLoop", NULL);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp7_ = _tmp6_;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp8_ = g_strconcat (_tmp7_, "-->", NULL);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp9_ = _tmp8_;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp10_ = protocol_bus_transport_get_Name ((ProtocolBusTransport*) self);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp11_ = _tmp10_;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp12_ = g_strconcat (_tmp9_, _tmp11_, NULL);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp13_ = _tmp12_;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp14_ = g_strconcat (_tmp13_, ": ", NULL);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp15_ = _tmp14_;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp16_ = g_strconcat (_tmp15_, " Transp. Mainloop started -", NULL);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp17_ = _tmp16_;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp18_ = g_type_name (G_TYPE_FROM_INSTANCE ((GObject*) self));
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp19_ = g_strconcat (_tmp17_, _tmp18_, NULL);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp20_ = _tmp19_;
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_ilogger_LoggerTrace ((ProtocolBusILogger*) self, PROTOCOL_BUS_TRACE_LEVEL_INFO, _tmp20_);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp20_);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp17_);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp15_);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp13_);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp9_);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp7_);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp5_);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp3_);
#line 133 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp1_);
#line 134 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp21_ = g_cancellable_new ();
#line 134 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_data2_->kancel = _tmp21_;
#line 136 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp22_ = g_main_context_new ();
#line 136 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	ctx = _tmp22_;
#line 137 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp23_ = g_main_loop_new (ctx, FALSE);
#line 137 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_data2_->loop = _tmp23_;
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp24_ = protocol_bus_transport_get_Name ((ProtocolBusTransport*) self);
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp25_ = _tmp24_;
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp26_ = g_strconcat ("ML_aux_", _tmp25_, NULL);
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp27_ = _tmp26_;
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp28_ = g_thread_new (_tmp27_, ___lambda7__gthread_func, block2_data_ref (_data2_));
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp29_ = _tmp28_;
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp27_);
#line 139 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	aux = _tmp29_;
#line 148 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp30_ = self->priv->ListeningSocket;
#line 148 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp31_ = g_socket_create_source (_tmp30_, G_IO_IN, NULL);
#line 148 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	source = _tmp31_;
#line 149 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_source_set_callback (source, (GSourceFunc) ___lambda8__gsocket_source_func, block2_data_ref (_data2_), block2_data_unref);
#line 153 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_source_attach (source, ctx);
#line 155 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_main_loop_run (_data2_->loop);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp32_ = g_strdup_printf ("%i", 157);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp33_ = _tmp32_;
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp34_ = g_strconcat ("MCastTransp.vala" ", L-", _tmp33_, NULL);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp35_ = _tmp34_;
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp36_ = g_strconcat (_tmp35_, ": ", NULL);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp37_ = _tmp36_;
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp38_ = g_strconcat (_tmp37_, "ProtocolBus.MCastTransp.MainLoop", NULL);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp39_ = _tmp38_;
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp40_ = g_strconcat (_tmp39_, "-->", NULL);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp41_ = _tmp40_;
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp42_ = protocol_bus_transport_get_Name ((ProtocolBusTransport*) self);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp43_ = _tmp42_;
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp44_ = g_strconcat (_tmp41_, _tmp43_, NULL);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp45_ = _tmp44_;
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp46_ = g_strconcat (_tmp45_, ": ", NULL);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp47_ = _tmp46_;
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp48_ = g_strconcat (_tmp47_, " Transp. Mainloop finished -", NULL);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp49_ = _tmp48_;
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp50_ = g_type_name (G_TYPE_FROM_INSTANCE ((GObject*) self));
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp51_ = g_strconcat (_tmp49_, _tmp50_, NULL);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp52_ = _tmp51_;
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_ilogger_LoggerTrace ((ProtocolBusILogger*) self, PROTOCOL_BUS_TRACE_LEVEL_INFO, _tmp52_);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp52_);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp49_);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp47_);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp45_);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp41_);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp39_);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp37_);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp35_);
#line 157 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (_tmp33_);
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_source_unref0 (source);
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_thread_unref0 (aux);
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_main_context_unref0 (ctx);
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	block2_data_unref (_data2_);
#line 131 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_data2_ = NULL;
#line 1234 "MCastTransp.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 168 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return self ? g_object_ref (self) : NULL;
#line 1242 "MCastTransp.c"
}

static guint8*
_vala_array_dup4 (guint8* self,
                  gssize length)
{
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	if (length > 0) {
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 1253 "MCastTransp.c"
	}
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	return NULL;
#line 1257 "MCastTransp.c"
}

static void
protocol_bus_mcast_transp_Receive (ProtocolBusMCastTransp* self,
                                   GCancellable* k)
{
	GSocketAddress* aux = NULL;
	guint8* bytes = NULL;
	guint8* _tmp0_;
	gint bytes_length1;
	gint _bytes_size_;
	guint64 BytesRead = 0ULL;
	GError* _inner_error0_ = NULL;
#line 160 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_if_fail (self != NULL);
#line 160 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_return_if_fail (k != NULL);
#line 162 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp0_ = g_new0 (guint8, 64000);
#line 162 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	bytes = _tmp0_;
#line 162 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	bytes_length1 = 64000;
#line 162 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_bytes_size_ = bytes_length1;
#line 1283 "MCastTransp.c"
	{
		gssize _tmp1_ = 0L;
		GSocket* _tmp2_;
		GSocketAddress* _tmp3_ = NULL;
		gssize _tmp4_;
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp2_ = self->priv->ListeningSocket;
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp4_ = g_socket_receive_from (_tmp2_, &_tmp3_, bytes, (gsize) bytes_length1, k, &_inner_error0_);
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_object_unref0 (aux);
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		aux = _tmp3_;
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp1_ = _tmp4_;
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			if (_inner_error0_->domain == G_IO_ERROR) {
#line 1303 "MCastTransp.c"
				goto __catch0_g_io_error;
			}
			goto __finally0;
		}
#line 166 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		BytesRead = (guint64) _tmp1_;
#line 167 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		if (BytesRead > ((guint64) 0)) {
#line 1312 "MCastTransp.c"
			GInetSocketAddress* aux2 = NULL;
			GInetSocketAddress* _tmp5_;
			gboolean _tmp6_ = FALSE;
			GInetSocketAddress* _tmp7_;
			guint _tmp8_;
			guint _tmp9_;
#line 168 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (aux, g_inet_socket_address_get_type (), GInetSocketAddress));
#line 168 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			aux2 = _tmp5_;
#line 169 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			_tmp7_ = aux2;
#line 169 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			_tmp8_ = g_inet_socket_address_get_port (_tmp7_);
#line 169 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			_tmp9_ = _tmp8_;
#line 169 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			if (((guint) self->priv->LocalPort) == _tmp9_) {
#line 169 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp6_ = !((ProtocolBusTransport*) self)->ReceiveOwnMessages;
#line 1333 "MCastTransp.c"
			} else {
#line 169 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp6_ = FALSE;
#line 1337 "MCastTransp.c"
			}
#line 169 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			if (_tmp6_) {
#line 1341 "MCastTransp.c"
				gchar* _tmp10_;
				gchar* _tmp11_;
				gchar* _tmp12_;
				gchar* _tmp13_;
				gchar* _tmp14_;
				gchar* _tmp15_;
				gchar* _tmp16_;
				gchar* _tmp17_;
				gchar* _tmp18_;
				gchar* _tmp19_;
				const gchar* _tmp20_;
				const gchar* _tmp21_;
				gchar* _tmp22_;
				gchar* _tmp23_;
				gchar* _tmp24_;
				gchar* _tmp25_;
				gchar* _tmp26_;
				gchar* _tmp27_;
				GInetSocketAddress* _tmp28_;
				guint _tmp29_;
				guint _tmp30_;
				gchar* _tmp31_;
				gchar* _tmp32_;
				gchar* _tmp33_;
				gchar* _tmp34_;
				gchar* _tmp35_;
				gchar* _tmp36_;
				const gchar* _tmp37_;
				gchar* _tmp38_;
				gchar* _tmp39_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp10_ = g_strdup_printf ("%i", 170);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp11_ = _tmp10_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp12_ = g_strconcat ("MCastTransp.vala" ", L-", _tmp11_, NULL);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp13_ = _tmp12_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp14_ = g_strconcat (_tmp13_, ": ", NULL);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp15_ = _tmp14_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp16_ = g_strconcat (_tmp15_, "ProtocolBus.MCastTransp.Receive", NULL);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp17_ = _tmp16_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp18_ = g_strconcat (_tmp17_, "-->", NULL);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp19_ = _tmp18_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp20_ = protocol_bus_transport_get_Name ((ProtocolBusTransport*) self);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp21_ = _tmp20_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp22_ = g_strconcat (_tmp19_, _tmp21_, NULL);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp23_ = _tmp22_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp24_ = g_strconcat (_tmp23_, ": ", NULL);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp25_ = _tmp24_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp26_ = g_strconcat (_tmp25_, " Dissmissing own message on port ", NULL);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp27_ = _tmp26_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp28_ = aux2;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp29_ = g_inet_socket_address_get_port (_tmp28_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp30_ = _tmp29_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp31_ = g_strdup_printf ("%u", _tmp30_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp32_ = _tmp31_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp33_ = g_strconcat (_tmp27_, _tmp32_, NULL);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp34_ = _tmp33_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp35_ = g_strconcat (_tmp34_, " ", NULL);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp36_ = _tmp35_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp37_ = g_type_name (G_TYPE_FROM_INSTANCE ((GObject*) self));
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp38_ = g_strconcat (_tmp36_, _tmp37_, NULL);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp39_ = _tmp38_;
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				protocol_bus_ilogger_LoggerTrace ((ProtocolBusILogger*) self, PROTOCOL_BUS_TRACE_LEVEL_INFO, _tmp39_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp39_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp36_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp34_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp32_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp27_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp25_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp23_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp19_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp17_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp15_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp13_);
#line 170 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_free0 (_tmp11_);
#line 1458 "MCastTransp.c"
			} else {
				guint8* _tmp40_;
				gint _tmp40__length1;
				GBytes* _tmp41_;
				GBytes* _tmp42_;
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp40_ = (bytes != NULL) ? _vala_array_dup4 (bytes + 0, ((gint) BytesRead) - 0) : bytes;
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp40__length1 = ((gint) BytesRead) - 0;
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp41_ = g_bytes_new_take (_tmp40_, _tmp40__length1);
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_tmp42_ = _tmp41_;
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				protocol_bus_transport_ParseAndEnqueue ((ProtocolBusTransport*) self, _tmp42_);
#line 174 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
				_g_bytes_unref0 (_tmp42_);
#line 1476 "MCastTransp.c"
			}
#line 167 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
			_g_object_unref0 (aux2);
#line 1480 "MCastTransp.c"
		}
	}
	goto __finally0;
	__catch0_g_io_error:
	{
		GError* err = NULL;
		gchar* _tmp43_;
		gchar* _tmp44_;
		gchar* _tmp45_;
		gchar* _tmp46_;
		gchar* _tmp47_;
		gchar* _tmp48_;
		gchar* _tmp49_;
		gchar* _tmp50_;
		gchar* _tmp51_;
		gchar* _tmp52_;
		const gchar* _tmp53_;
		const gchar* _tmp54_;
		gchar* _tmp55_;
		gchar* _tmp56_;
		gchar* _tmp57_;
		gchar* _tmp58_;
		gchar* _tmp59_;
		gchar* _tmp60_;
		GError* _tmp61_;
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		err = _inner_error0_;
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_inner_error0_ = NULL;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp43_ = g_strdup_printf ("%i", 180);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp44_ = _tmp43_;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp45_ = g_strconcat ("MCastTransp.vala" ", L-", _tmp44_, NULL);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp46_ = _tmp45_;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp47_ = g_strconcat (_tmp46_, ": ", NULL);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp48_ = _tmp47_;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp49_ = g_strconcat (_tmp48_, "ProtocolBus.MCastTransp.Receive", NULL);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp50_ = _tmp49_;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp51_ = g_strconcat (_tmp50_, "-->", NULL);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp52_ = _tmp51_;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp53_ = protocol_bus_transport_get_Name ((ProtocolBusTransport*) self);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp54_ = _tmp53_;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp55_ = g_strconcat (_tmp52_, _tmp54_, NULL);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp56_ = _tmp55_;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp57_ = g_strconcat (_tmp56_, ": ", NULL);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp58_ = _tmp57_;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp59_ = g_strconcat (_tmp58_, "error or cancelled", NULL);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp60_ = _tmp59_;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_tmp61_ = err;
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		protocol_bus_ilogger_LoggerTraceWithErr ((ProtocolBusILogger*) self, PROTOCOL_BUS_TRACE_LEVEL_ERROR, _tmp60_, _tmp61_);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp60_);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp58_);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp56_);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp52_);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp50_);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp48_);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp46_);
#line 179 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_free0 (_tmp44_);
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_error_free0 (err);
#line 1568 "MCastTransp.c"
	}
	__finally0:
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		bytes = (g_free (bytes), NULL);
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		_g_object_unref0 (aux);
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		g_clear_error (&_inner_error0_);
#line 165 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
		return;
#line 1583 "MCastTransp.c"
	}
#line 160 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	bytes = (g_free (bytes), NULL);
#line 160 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (aux);
#line 1589 "MCastTransp.c"
}

static void
protocol_bus_mcast_transp_class_init (ProtocolBusMCastTranspClass * klass,
                                      gpointer klass_data)
{
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	protocol_bus_mcast_transp_parent_class = g_type_class_peek_parent (klass);
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	g_type_class_adjust_private_offset (klass, &ProtocolBusMCastTransp_private_offset);
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	((ProtocolBusTransportClass *) klass)->SendBytes = (gboolean (*) (ProtocolBusTransport*, GBytes*)) protocol_bus_mcast_transp_real_SendBytes;
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	((ProtocolBusTransportClass *) klass)->MainLoop = (void (*) (ProtocolBusTransport*)) protocol_bus_mcast_transp_real_MainLoop;
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	G_OBJECT_CLASS (klass)->finalize = protocol_bus_mcast_transp_finalize;
#line 1606 "MCastTransp.c"
}

static void
protocol_bus_mcast_transp_instance_init (ProtocolBusMCastTransp * self,
                                         gpointer klass)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv = protocol_bus_mcast_transp_get_instance_private (self);
#line 16 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->TTL = 1;
#line 17 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->SendBuffer = 134217727;
#line 18 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->ReceiveBuffer = 134217727;
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->isBroadcast = FALSE;
#line 22 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp0_ = g_strdup ("Any");
#line 22 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->LocalStrAddr = _tmp0_;
#line 25 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->LocalPort = 50000;
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_tmp1_ = g_strdup ("239.255.0.1");
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->MCastStrAddr = _tmp1_;
#line 30 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self->priv->MCastPort = (guint16) 40069;
#line 1637 "MCastTransp.c"
}

static void
protocol_bus_mcast_transp_finalize (GObject * obj)
{
	ProtocolBusMCastTransp * self;
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PROTOCOL_BUS_TYPE_MCAST_TRANSP, ProtocolBusMCastTransp);
#line 13 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (self->priv->SendingSocket);
#line 14 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (self->priv->ListeningSocket);
#line 22 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (self->priv->LocalStrAddr);
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (self->priv->LocalAddr);
#line 24 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (self->priv->LocalSoxAddr);
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_free0 (self->priv->MCastStrAddr);
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (self->priv->MCastAddr);
#line 29 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	_g_object_unref0 (self->priv->MCastSoxAddr);
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/MCastTransp.vala"
	G_OBJECT_CLASS (protocol_bus_mcast_transp_parent_class)->finalize (obj);
#line 1664 "MCastTransp.c"
}

static GType
protocol_bus_mcast_transp_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ProtocolBusMCastTranspClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) protocol_bus_mcast_transp_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ProtocolBusMCastTransp), 0, (GInstanceInitFunc) protocol_bus_mcast_transp_instance_init, NULL };
	GType protocol_bus_mcast_transp_type_id;
	protocol_bus_mcast_transp_type_id = g_type_register_static (PROTOCOL_BUS_TYPE_TRANSPORT, "ProtocolBusMCastTransp", &g_define_type_info, 0);
	ProtocolBusMCastTransp_private_offset = g_type_add_instance_private (protocol_bus_mcast_transp_type_id, sizeof (ProtocolBusMCastTranspPrivate));
	return protocol_bus_mcast_transp_type_id;
}

GType
protocol_bus_mcast_transp_get_type (void)
{
	static volatile gsize protocol_bus_mcast_transp_type_id__once = 0;
	if (g_once_init_enter (&protocol_bus_mcast_transp_type_id__once)) {
		GType protocol_bus_mcast_transp_type_id;
		protocol_bus_mcast_transp_type_id = protocol_bus_mcast_transp_get_type_once ();
		g_once_init_leave (&protocol_bus_mcast_transp_type_id__once, protocol_bus_mcast_transp_type_id);
	}
	return protocol_bus_mcast_transp_type_id__once;
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (mem && byte_size != 0) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		new_mem = g_malloc (byte_size);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		memcpy (new_mem, mem, byte_size);
#line 1700 "MCastTransp.c"
	} else {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		new_mem = NULL;
#line 1704 "MCastTransp.c"
	}
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return new_mem;
#line 1708 "MCastTransp.c"
}

