/* Transport.c generated by valac 0.56.0, the Vala compiler
 * generated from Transport.vala, do not modify */

#include "protocolbus.h"
#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gio/gio.h>

enum  {
	PROTOCOL_BUS_TRANSPORT_0_PROPERTY,
	PROTOCOL_BUS_TRANSPORT_IS_STARTED_PROPERTY,
	PROTOCOL_BUS_TRANSPORT_NAME_PROPERTY,
	PROTOCOL_BUS_TRANSPORT_NUM_PROPERTIES
};
static GParamSpec* protocol_bus_transport_properties[PROTOCOL_BUS_TRANSPORT_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_thread_unref0(var) ((var == NULL) ? NULL : (var = (g_thread_unref (var), NULL)))

#define PROTOCOL_BUS_TYPE_DOMAIN (protocol_bus_domain_get_type ())
#define PROTOCOL_BUS_DOMAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PROTOCOL_BUS_TYPE_DOMAIN, ProtocolBusDomain))
#define PROTOCOL_BUS_DOMAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PROTOCOL_BUS_TYPE_DOMAIN, ProtocolBusDomainClass))
#define PROTOCOL_BUS_IS_DOMAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PROTOCOL_BUS_TYPE_DOMAIN))
#define PROTOCOL_BUS_IS_DOMAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PROTOCOL_BUS_TYPE_DOMAIN))
#define PROTOCOL_BUS_DOMAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PROTOCOL_BUS_TYPE_DOMAIN, ProtocolBusDomainClass))

typedef struct _ProtocolBusDomain ProtocolBusDomain;
typedef struct _ProtocolBusDomainClass ProtocolBusDomainClass;
typedef struct _Block3Data Block3Data;
#define _protobuf_decode_buffer_unref0(var) ((var == NULL) ? NULL : (var = (protobuf_decode_buffer_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_bytes_unref0(var) ((var == NULL) ? NULL : (var = (g_bytes_unref (var), NULL)))
#define _protobuf_encode_buffer_unref0(var) ((var == NULL) ? NULL : (var = (protobuf_encode_buffer_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
enum  {
	PROTOCOL_BUS_TRANSPORT_ENCRYPT_SIGNAL,
	PROTOCOL_BUS_TRANSPORT_DECRYPT_SIGNAL,
	PROTOCOL_BUS_TRANSPORT_SEND_PCK_TO_XCONNECTED_TRANSPORTS_SIGNAL,
	PROTOCOL_BUS_TRANSPORT_NUM_SIGNALS
};
static guint protocol_bus_transport_signals[PROTOCOL_BUS_TRANSPORT_NUM_SIGNALS] = {0};

struct _Block3Data {
	int _ref_count_;
	ProtocolBusTransport* self;
	ProtocolBusPacket* myPacket;
	GeeArrayList* msgList;
};

static gpointer protocol_bus_transport_parent_class = NULL;

VALA_EXTERN GType protocol_bus_domain_get_type (void) G_GNUC_CONST ;
static GBytes* _protocol_bus_domain_Encrypt_protocol_bus_transport_encrypt (ProtocolBusTransport* _sender,
                                                                     GBytes* bytes,
                                                                     gpointer self);
static GBytes* _protocol_bus_domain_Decrypt_protocol_bus_transport_decrypt (ProtocolBusTransport* _sender,
                                                                     GBytes* bytes,
                                                                     gpointer self);
static GBytes* ___lambda4_ (ProtocolBusTransport* self,
                     GBytes* b);
static GBytes* ____lambda4__protocol_bus_transport_encrypt (ProtocolBusTransport* _sender,
                                                     GBytes* bytes,
                                                     gpointer self);
static GBytes* ___lambda5_ (ProtocolBusTransport* self,
                     GBytes* b);
static GBytes* ____lambda5__protocol_bus_transport_decrypt (ProtocolBusTransport* _sender,
                                                     GBytes* bytes,
                                                     gpointer self);
static gpointer _protocol_bus_transport_MainLoop_gthread_func (gpointer self);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
static void ___lambda6_ (Block3Data* _data3_,
                  ProtocolBusMsg* msg);
static void _g_object_unref0_ (gpointer var);
static void ____lambda6__gfunc (gconstpointer data,
                         gpointer self);
static guint8* _vala_array_dup5 (guint8* self,
                          gssize length);
static gboolean _protocol_bus_transport_SendPck_protocol_bus_transport_send_pck_to_xconnected_transports (ProtocolBusTransport* _sender,
                                                                                                   ProtocolBusPacket* myPck,
                                                                                                   gpointer self);
static gboolean protocol_bus_transport_real_SendBytes (ProtocolBusTransport* self,
                                                GBytes* data);
static void protocol_bus_transport_real_MainLoop (ProtocolBusTransport* self);
static inline void _g_list_free__g_object_unref0_ (GList* self);
static void g_cclosure_user_marshal_BOXED__BOXED (GClosure * closure,
                                           GValue * return_value,
                                           guint n_param_values,
                                           const GValue * param_values,
                                           gpointer invocation_hint,
                                           gpointer marshal_data);
static void g_cclosure_user_marshal_BOOLEAN__OBJECT (GClosure * closure,
                                              GValue * return_value,
                                              guint n_param_values,
                                              const GValue * param_values,
                                              gpointer invocation_hint,
                                              gpointer marshal_data);
static void protocol_bus_transport_finalize (GObject * obj);
static GType protocol_bus_transport_get_type_once (void);
static void _vala_protocol_bus_transport_get_property (GObject * object,
                                                guint property_id,
                                                GValue * value,
                                                GParamSpec * pspec);
static void _vala_protocol_bus_transport_set_property (GObject * object,
                                                guint property_id,
                                                const GValue * value,
                                                GParamSpec * pspec);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

static gpointer
_g_object_ref0 (gpointer self)
{
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return self ? g_object_ref (self) : NULL;
#line 120 "Transport.c"
}

static GBytes*
_protocol_bus_domain_Encrypt_protocol_bus_transport_encrypt (ProtocolBusTransport* _sender,
                                                             GBytes* bytes,
                                                             gpointer self)
{
	GBytes* result;
	result = protocol_bus_domain_Encrypt ((ProtocolBusDomain*) self, bytes);
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 132 "Transport.c"
}

static GBytes*
_protocol_bus_domain_Decrypt_protocol_bus_transport_decrypt (ProtocolBusTransport* _sender,
                                                             GBytes* bytes,
                                                             gpointer self)
{
	GBytes* result;
	result = protocol_bus_domain_Decrypt ((ProtocolBusDomain*) self, bytes);
#line 24 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 144 "Transport.c"
}

static gpointer
_g_bytes_ref0 (gpointer self)
{
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return self ? g_bytes_ref (self) : NULL;
#line 152 "Transport.c"
}

static GBytes*
___lambda4_ (ProtocolBusTransport* self,
             GBytes* b)
{
	GBytes* _tmp0_;
	GBytes* result;
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (b != NULL, NULL);
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp0_ = _g_bytes_ref0 (b);
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	result = _tmp0_;
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 169 "Transport.c"
}

static GBytes*
____lambda4__protocol_bus_transport_encrypt (ProtocolBusTransport* _sender,
                                             GBytes* bytes,
                                             gpointer self)
{
	GBytes* result;
	result = ___lambda4_ ((ProtocolBusTransport*) self, bytes);
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 181 "Transport.c"
}

static GBytes*
___lambda5_ (ProtocolBusTransport* self,
             GBytes* b)
{
	GBytes* _tmp0_;
	GBytes* result;
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (b != NULL, NULL);
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp0_ = _g_bytes_ref0 (b);
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	result = _tmp0_;
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 198 "Transport.c"
}

static GBytes*
____lambda5__protocol_bus_transport_decrypt (ProtocolBusTransport* _sender,
                                             GBytes* bytes,
                                             gpointer self)
{
	GBytes* result;
	result = ___lambda5_ ((ProtocolBusTransport*) self, bytes);
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 210 "Transport.c"
}

ProtocolBusTransport*
protocol_bus_transport_construct (GType object_type,
                                  ProtocolBusDomain* domain,
                                  const gchar* name)
{
	ProtocolBusTransport * self = NULL;
	ProtocolBusDomain* _tmp0_;
	gchar* _tmp1_;
	ProtocolBusDomain* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
#line 19 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (domain != NULL, NULL);
#line 19 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 19 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self = (ProtocolBusTransport*) protocol_bus_ilogger_construct (object_type);
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp0_ = _g_object_ref0 (domain);
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_object_unref0 (self->myDomain);
#line 20 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self->myDomain = _tmp0_;
#line 21 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp1_ = g_strdup (name);
#line 21 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_free0 (self->myName);
#line 21 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self->myName = _tmp1_;
#line 22 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp2_ = self->myDomain;
#line 22 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp3_ = protocol_bus_domain_get_HasCipheringKey (_tmp2_);
#line 22 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp4_ = _tmp3_;
#line 22 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if (_tmp4_) {
#line 250 "Transport.c"
		ProtocolBusDomain* _tmp5_;
		ProtocolBusDomain* _tmp6_;
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp5_ = self->myDomain;
#line 23 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_signal_connect_object (self, "encrypt", (GCallback) _protocol_bus_domain_Encrypt_protocol_bus_transport_encrypt, _tmp5_, 0);
#line 24 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp6_ = self->myDomain;
#line 24 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_signal_connect_object (self, "decrypt", (GCallback) _protocol_bus_domain_Decrypt_protocol_bus_transport_decrypt, _tmp6_, 0);
#line 261 "Transport.c"
	} else {
#line 27 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_signal_connect_object (self, "encrypt", (GCallback) ____lambda4__protocol_bus_transport_encrypt, self, 0);
#line 28 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_signal_connect_object (self, "decrypt", (GCallback) ____lambda5__protocol_bus_transport_decrypt, self, 0);
#line 267 "Transport.c"
	}
#line 19 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return self;
#line 271 "Transport.c"
}

static gpointer
_protocol_bus_transport_MainLoop_gthread_func (gpointer self)
{
	gpointer result;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	protocol_bus_transport_MainLoop ((ProtocolBusTransport*) self);
#line 280 "Transport.c"
	result = NULL;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_object_unref (self);
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 286 "Transport.c"
}

void
protocol_bus_transport_StartMainLoop (ProtocolBusTransport* self)
{
	ProtocolBusAppSync* _tmp5_;
	GThread* _tmp6_;
#line 43 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (self != NULL);
#line 44 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if (!self->isStarted) {
#line 298 "Transport.c"
		const gchar* _tmp0_;
		const gchar* _tmp1_;
		gchar* _tmp2_;
		gchar* _tmp3_;
		GThread* _tmp4_;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp0_ = protocol_bus_transport_get_Name (self);
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp1_ = _tmp0_;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp2_ = g_strconcat ("ML_", _tmp1_, NULL);
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp3_ = _tmp2_;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp4_ = g_thread_new (_tmp3_, _protocol_bus_transport_MainLoop_gthread_func, g_object_ref (self));
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_thread_unref0 (self->myThread);
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		self->myThread = _tmp4_;
#line 45 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp3_);
#line 320 "Transport.c"
	}
#line 46 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self->isStarted = TRUE;
#line 47 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp5_ = self->theSync;
#line 47 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp6_ = self->myThread;
#line 47 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	protocol_bus_app_sync_RegisterThread (_tmp5_, _tmp6_);
#line 330 "Transport.c"
}

static Block3Data*
block3_data_ref (Block3Data* _data3_)
{
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_atomic_int_inc (&_data3_->_ref_count_);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return _data3_;
#line 340 "Transport.c"
}

static void
block3_data_unref (void * _userdata_)
{
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
#line 350 "Transport.c"
		ProtocolBusTransport* self;
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		self = _data3_->self;
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_object_unref0 (_data3_->msgList);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_object_unref0 (_data3_->myPacket);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_object_unref0 (self);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_slice_free (Block3Data, _data3_);
#line 362 "Transport.c"
	}
}

static gint
_vala_g_bytes_get_length (GBytes* self)
{
	gint result;
#line 5832 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 5834 "glib-2.0.vapi"
	result = (gint) g_bytes_get_size (self);
#line 5834 "glib-2.0.vapi"
	return result;
#line 376 "Transport.c"
}

static GList*
vala_g_list_remove_full (GList* self,
                         gconstpointer data,
                         GFreeFunc func)
{
	GList* l = NULL;
	GList* result;
#line 5096 "glib-2.0.vapi"
	l = self;
#line 5097 "glib-2.0.vapi"
	while (TRUE) {
#line 390 "Transport.c"
		GList* _tmp0_;
		GList* _tmp1_;
		gconstpointer _tmp2_;
#line 5097 "glib-2.0.vapi"
		_tmp0_ = l;
#line 5097 "glib-2.0.vapi"
		if (!(_tmp0_ != NULL)) {
#line 5097 "glib-2.0.vapi"
			break;
#line 400 "Transport.c"
		}
#line 5098 "glib-2.0.vapi"
		_tmp1_ = l;
#line 5098 "glib-2.0.vapi"
		_tmp2_ = ((GList*) _tmp1_)->data;
#line 5098 "glib-2.0.vapi"
		if (_tmp2_ != data) {
#line 408 "Transport.c"
			GList* _tmp3_;
			GList* _tmp4_;
#line 5099 "glib-2.0.vapi"
			_tmp3_ = l;
#line 5099 "glib-2.0.vapi"
			_tmp4_ = ((GList*) _tmp3_)->next;
#line 5099 "glib-2.0.vapi"
			l = _tmp4_;
#line 417 "Transport.c"
		} else {
			GList* _tmp5_;
			gconstpointer _tmp6_;
			GList* _tmp7_;
#line 5101 "glib-2.0.vapi"
			_tmp5_ = l;
#line 5101 "glib-2.0.vapi"
			_tmp6_ = ((GList*) _tmp5_)->data;
#line 5101 "glib-2.0.vapi"
			func (_tmp6_);
#line 5102 "glib-2.0.vapi"
			_tmp7_ = l;
#line 5102 "glib-2.0.vapi"
			self = g_list_delete_link (self, (GList*) _tmp7_);
#line 5103 "glib-2.0.vapi"
			break;
#line 434 "Transport.c"
		}
	}
#line 5106 "glib-2.0.vapi"
	result = self;
#line 5106 "glib-2.0.vapi"
	return result;
#line 441 "Transport.c"
}

static void
_g_object_unref0_ (gpointer var)
{
#line 60 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 449 "Transport.c"
}

static void
___lambda6_ (Block3Data* _data3_,
             ProtocolBusMsg* msg)
{
	ProtocolBusTransport* self;
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self = _data3_->self;
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (msg != NULL);
#line 59 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) _data3_->msgList, msg);
#line 60 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_data3_->myPacket->messages = vala_g_list_remove_full (_data3_->myPacket->messages, msg, _g_object_unref0_);
#line 465 "Transport.c"
}

static void
____lambda6__gfunc (gconstpointer data,
                    gpointer self)
{
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	___lambda6_ (self, (ProtocolBusMsg*) data);
#line 474 "Transport.c"
}

gboolean
protocol_bus_transport_ParseAndEnqueue (ProtocolBusTransport* self,
                                        GBytes* data)
{
	GBytes* RedBytes = NULL;
	GBytes* _tmp0_ = NULL;
	GError* _inner_error0_ = NULL;
	gboolean result;
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 50 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (data != NULL, FALSE);
#line 51 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_signal_emit (self, protocol_bus_transport_signals[PROTOCOL_BUS_TRANSPORT_DECRYPT_SIGNAL], 0, data, &_tmp0_);
#line 51 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	RedBytes = _tmp0_;
#line 493 "Transport.c"
	{
		Block3Data* _data3_;
		ProtobufDecodeBuffer* decBuffer = NULL;
		gsize _tmp1_ = 0;
		guint8* _tmp2_;
		ProtobufDecodeBuffer* _tmp3_;
		gint _tmp4_;
		gint _tmp5_;
		ProtocolBusPacket* _tmp6_;
		gboolean _tmp7_ = FALSE;
		GeeArrayList* _tmp8_;
		GList* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		gchar* _tmp16_;
		gchar* _tmp17_;
		gchar* _tmp18_;
		gchar* _tmp19_;
		const gchar* _tmp20_;
		const gchar* _tmp21_;
		gchar* _tmp22_;
		gchar* _tmp23_;
		gchar* _tmp24_;
		gchar* _tmp25_;
		gchar* _tmp26_;
		gchar* _tmp27_;
		const gchar* _tmp28_;
		gchar* _tmp29_;
		gchar* _tmp30_;
		gint _tmp31_;
		gint _tmp32_;
		gchar* _tmp33_;
		gchar* _tmp34_;
		gchar* _tmp35_;
		gchar* _tmp36_;
		ProtocolBusDomain* _tmp37_;
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_data3_ = g_slice_new0 (Block3Data);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_data3_->_ref_count_ = 1;
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_data3_->self = g_object_ref (self);
#line 54 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp2_ = g_bytes_get_data (RedBytes, &_tmp1_);
#line 54 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp3_ = protobuf_decode_buffer_new (_tmp2_, _tmp1_, (gsize) 0, (gssize) -1);
#line 54 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		decBuffer = _tmp3_;
#line 55 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp4_ = _vala_g_bytes_get_length (data);
#line 55 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp5_ = _tmp4_;
#line 55 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp6_ = protocol_bus_packet_new_from_data (decBuffer, (gssize) _tmp5_);
#line 55 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_data3_->myPacket = _tmp6_;
#line 56 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_signal_emit (self, protocol_bus_transport_signals[PROTOCOL_BUS_TRANSPORT_SEND_PCK_TO_XCONNECTED_TRANSPORTS_SIGNAL], 0, _data3_->myPacket, &_tmp7_);
#line 57 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp8_ = gee_array_list_new (PROTOCOL_BUS_TYPE_MSG, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 57 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_data3_->msgList = _tmp8_;
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp9_ = _data3_->myPacket->messages;
#line 58 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_list_foreach (_tmp9_, ____lambda6__gfunc, _data3_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp10_ = g_strdup_printf ("%i", 62);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp11_ = _tmp10_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp12_ = g_strconcat ("Transport.vala" ", L-", _tmp11_, NULL);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp13_ = _tmp12_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp14_ = g_strconcat (_tmp13_, ": ", NULL);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp15_ = _tmp14_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp16_ = g_strconcat (_tmp15_, "ProtocolBus.Transport.ParseAndEnqueue", NULL);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp17_ = _tmp16_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp18_ = g_strconcat (_tmp17_, "-->", NULL);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp19_ = _tmp18_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp20_ = protocol_bus_transport_get_Name (self);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp21_ = _tmp20_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp22_ = g_strconcat (_tmp19_, _tmp21_, NULL);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp23_ = _tmp22_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp24_ = g_strconcat (_tmp23_, ": ", NULL);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp25_ = _tmp24_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp26_ = g_strconcat (_tmp25_, "Recive from wire - ", NULL);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp27_ = _tmp26_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp28_ = g_type_name (G_TYPE_FROM_INSTANCE ((GObject*) self));
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp29_ = g_strconcat (_tmp27_, _tmp28_, NULL);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp30_ = _tmp29_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp31_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _data3_->msgList);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp32_ = _tmp31_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp33_ = g_strdup_printf ("%i", _tmp32_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp34_ = _tmp33_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp35_ = g_strconcat (_tmp30_, _tmp34_, NULL);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp36_ = _tmp35_;
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		protocol_bus_ilogger_LoggerTrace ((ProtocolBusILogger*) self, PROTOCOL_BUS_TRACE_LEVEL_TRACE, _tmp36_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp36_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp34_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp30_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp27_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp25_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp23_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp19_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp17_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp15_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp13_);
#line 62 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp11_);
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp37_ = self->myDomain;
#line 65 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		protocol_bus_domain_OnMsgReceived (_tmp37_, _data3_->msgList);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_protobuf_decode_buffer_unref0 (decBuffer);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		block3_data_unref (_data3_);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_data3_ = NULL;
#line 652 "Transport.c"
	}
	goto __finally0;
	__catch0_g_io_error:
	{
		GError* e = NULL;
		gchar* _tmp38_;
		gchar* _tmp39_;
		gchar* _tmp40_;
		gchar* _tmp41_;
		gchar* _tmp42_;
		gchar* _tmp43_;
		gchar* _tmp44_;
		gchar* _tmp45_;
		gchar* _tmp46_;
		gchar* _tmp47_;
		GError* _tmp48_;
		const gchar* _tmp49_;
		gchar* _tmp50_;
		gchar* _tmp51_;
		GError* _tmp52_;
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		e = _inner_error0_;
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_inner_error0_ = NULL;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp38_ = g_strdup_printf ("%i", 68);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp39_ = _tmp38_;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp40_ = g_strconcat ("Transport.vala" ": ", _tmp39_, NULL);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp41_ = _tmp40_;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp42_ = g_strconcat (_tmp41_, ", ", NULL);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp43_ = _tmp42_;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp44_ = g_strconcat (_tmp43_, "ProtocolBus.Transport.ParseAndEnqueue", NULL);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp45_ = _tmp44_;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp46_ = g_strconcat (_tmp45_, "-->", NULL);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp47_ = _tmp46_;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp48_ = e;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp49_ = _tmp48_->message;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp50_ = g_strconcat (_tmp47_, _tmp49_, NULL);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp51_ = _tmp50_;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_tmp52_ = e;
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		protocol_bus_ilogger_LoggerTraceWithErr ((ProtocolBusILogger*) self, PROTOCOL_BUS_TRACE_LEVEL_ERROR, _tmp51_, _tmp52_);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp51_);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp47_);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp45_);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp43_);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp41_);
#line 68 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_free0 (_tmp39_);
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		result = FALSE;
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_error_free0 (e);
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_bytes_unref0 (RedBytes);
#line 69 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		return result;
#line 729 "Transport.c"
	}
	__finally0:
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 734 "Transport.c"
		gboolean _tmp53_ = FALSE;
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_g_bytes_unref0 (RedBytes);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_clear_error (&_inner_error0_);
#line 53 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		return _tmp53_;
#line 744 "Transport.c"
	}
#line 71 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	result = TRUE;
#line 71 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_bytes_unref0 (RedBytes);
#line 71 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 752 "Transport.c"
}

static guint8*
_vala_array_dup5 (guint8* self,
                  gssize length)
{
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if (length > 0) {
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		return _vala_memdup2 (self, length * sizeof (guint8));
#line 763 "Transport.c"
	}
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return NULL;
#line 767 "Transport.c"
}

gboolean
protocol_bus_transport_SendPck (ProtocolBusTransport* self,
                                ProtocolBusPacket* myPck)
{
	GBytes* BlackBytes = NULL;
	ProtobufEncodeBuffer* encBuffer = NULL;
	ProtobufEncodeBuffer* _tmp0_;
	guint8* _tmp1_;
	gint _tmp1__length1;
	gint _tmp2_ = 0;
	guint8* _tmp3_;
	gint _tmp3__length1;
	guint8* _tmp4_;
	gint _tmp4__length1;
	GBytes* _tmp5_;
	GBytes* _tmp6_;
	GBytes* _tmp7_ = NULL;
	gboolean result;
#line 74 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 74 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (myPck != NULL, FALSE);
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp0_ = protobuf_encode_buffer_new ((gsize) 1024);
#line 77 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	encBuffer = _tmp0_;
#line 78 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	protobuf_message_encode ((ProtobufMessage*) myPck, encBuffer);
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp1_ = protobuf_encode_buffer_get_data (encBuffer, &_tmp2_);
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp1__length1 = _tmp2_;
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp3_ = _tmp1_;
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp3__length1 = _tmp1__length1;
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp4_ = (_tmp3_ != NULL) ? _vala_array_dup5 (_tmp3_, _tmp3__length1) : _tmp3_;
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp4__length1 = _tmp3__length1;
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp5_ = g_bytes_new_take (_tmp4_, _tmp4__length1);
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp6_ = _tmp5_;
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_signal_emit (self, protocol_bus_transport_signals[PROTOCOL_BUS_TRANSPORT_ENCRYPT_SIGNAL], 0, _tmp6_, &_tmp7_);
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_bytes_unref0 (BlackBytes);
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	BlackBytes = _tmp7_;
#line 79 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_bytes_unref0 (_tmp6_);
#line 81 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	result = protocol_bus_transport_SendBytes (self, BlackBytes);
#line 81 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_protobuf_encode_buffer_unref0 (encBuffer);
#line 81 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_bytes_unref0 (BlackBytes);
#line 81 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 830 "Transport.c"
}

static gboolean
_protocol_bus_transport_SendPck_protocol_bus_transport_send_pck_to_xconnected_transports (ProtocolBusTransport* _sender,
                                                                                          ProtocolBusPacket* myPck,
                                                                                          gpointer self)
{
	gboolean result;
	result = protocol_bus_transport_SendPck ((ProtocolBusTransport*) self, myPck);
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 842 "Transport.c"
}

void
protocol_bus_transport_CrossConnect (ProtocolBusTransport* self,
                                     ProtocolBusTransport* t)
{
#line 84 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (self != NULL);
#line 84 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (t != NULL);
#line 85 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_signal_connect_object (self, "send-pck-to-xconnected-transports", (GCallback) _protocol_bus_transport_SendPck_protocol_bus_transport_send_pck_to_xconnected_transports, t, 0);
#line 87 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self->ReceiveOwnMessages = FALSE;
#line 857 "Transport.c"
}

static gboolean
protocol_bus_transport_real_SendBytes (ProtocolBusTransport* self,
                                       GBytes* data)
{
	gboolean _tmp0_ = FALSE;
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_critical ("Type `%s' does not implement abstract method `protocol_bus_transport_SendBytes'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return _tmp0_;
#line 869 "Transport.c"
}

gboolean
protocol_bus_transport_SendBytes (ProtocolBusTransport* self,
                                  GBytes* data)
{
	ProtocolBusTransportClass* _klass_;
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_klass_ = PROTOCOL_BUS_TRANSPORT_GET_CLASS (self);
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if (_klass_->SendBytes) {
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		return _klass_->SendBytes (self, data);
#line 885 "Transport.c"
	}
#line 90 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return FALSE;
#line 889 "Transport.c"
}

static void
protocol_bus_transport_real_MainLoop (ProtocolBusTransport* self)
{
#line 91 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_critical ("Type `%s' does not implement abstract method `protocol_bus_transport_MainLoop'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 91 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return;
#line 899 "Transport.c"
}

void
protocol_bus_transport_MainLoop (ProtocolBusTransport* self)
{
	ProtocolBusTransportClass* _klass_;
#line 91 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (self != NULL);
#line 91 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_klass_ = PROTOCOL_BUS_TRANSPORT_GET_CLASS (self);
#line 91 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if (_klass_->MainLoop) {
#line 91 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		_klass_->MainLoop (self);
#line 914 "Transport.c"
	}
}

gboolean
protocol_bus_transport_is4NumericAddress (ProtocolBusTransport* self,
                                          const gchar* texto)
{
	GRegex* regex = NULL;
	GRegex* _tmp0_;
	GError* _inner_error0_ = NULL;
	gboolean result;
#line 93 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 93 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (texto != NULL, FALSE);
#line 95 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp0_ = g_regex_new ("^[0-9.]+$", 0, 0, &_inner_error0_);
#line 95 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	regex = _tmp0_;
#line 95 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 936 "Transport.c"
		gboolean _tmp1_ = FALSE;
#line 95 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 95 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_clear_error (&_inner_error0_);
#line 95 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		return _tmp1_;
#line 944 "Transport.c"
	}
#line 98 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	result = g_regex_match (regex, texto, 0, NULL);
#line 98 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_regex_unref0 (regex);
#line 98 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 952 "Transport.c"
}

static inline void
_g_list_free__g_object_unref0_ (GList* self)
{
#line 111 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_list_free_full (self, (GDestroyNotify) _g_object_unref0_);
#line 960 "Transport.c"
}

GInetAddress*
protocol_bus_transport_GetLocalAddress (ProtocolBusTransport* self,
                                        const gchar* localaddres)
{
	GInetAddress* aux = NULL;
	const gchar* _tmp0_;
	GQuark _tmp2_ = 0U;
#line 103 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	static GQuark _tmp1_label0 = 0;
#line 103 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	static GQuark _tmp1_label1 = 0;
#line 103 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	static GQuark _tmp1_label2 = 0;
#line 103 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	static GQuark _tmp1_label3 = 0;
#line 978 "Transport.c"
	GError* _inner_error0_ = NULL;
	GInetAddress* result;
#line 101 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 101 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (localaddres != NULL, NULL);
#line 103 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp0_ = localaddres;
#line 103 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp2_ = (NULL == _tmp0_) ? 0 : g_quark_from_string (_tmp0_);
#line 103 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if ((_tmp2_ == ((0 != _tmp1_label0) ? _tmp1_label0 : (_tmp1_label0 = g_quark_from_static_string ("Any")))) || (_tmp2_ == ((0 != _tmp1_label1) ? _tmp1_label1 : (_tmp1_label1 = g_quark_from_static_string ("any"))))) {
#line 103 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		switch (0) {
#line 993 "Transport.c"
			default:
			{
				GInetAddress* _tmp3_;
#line 105 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
				_tmp3_ = g_inet_address_new_from_string ("0.0.0.0");
#line 105 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
				_g_object_unref0 (aux);
#line 105 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
				aux = _tmp3_;
#line 106 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
				break;
#line 1005 "Transport.c"
			}
		}
	} else if ((_tmp2_ == ((0 != _tmp1_label2) ? _tmp1_label2 : (_tmp1_label2 = g_quark_from_static_string ("Loopback")))) || (_tmp2_ == ((0 != _tmp1_label3) ? _tmp1_label3 : (_tmp1_label3 = g_quark_from_static_string ("loopback"))))) {
#line 103 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		switch (0) {
#line 1011 "Transport.c"
			default:
			{
				GInetAddress* _tmp4_;
#line 108 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
				_tmp4_ = g_inet_address_new_from_string ("127.0.0.1");
#line 108 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
				_g_object_unref0 (aux);
#line 108 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
				aux = _tmp4_;
#line 109 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
				break;
#line 1023 "Transport.c"
			}
		}
	} else {
#line 103 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		switch (0) {
#line 1029 "Transport.c"
			default:
			{
#line 111 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
				if (protocol_bus_transport_is4NumericAddress (self, localaddres)) {
#line 1034 "Transport.c"
					GInetAddress* _tmp5_;
#line 112 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					_tmp5_ = g_inet_address_new_from_string (localaddres);
#line 112 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					_g_object_unref0 (aux);
#line 112 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					aux = _tmp5_;
#line 1042 "Transport.c"
				} else {
					GResolver* resolver = NULL;
					GResolver* _tmp6_;
					GList* addresses = NULL;
					GResolver* _tmp7_;
					GList* _tmp8_;
					GList* _tmp9_;
					gconstpointer _tmp10_;
					GInetAddress* _tmp11_;
#line 115 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					_tmp6_ = g_resolver_get_default ();
#line 115 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					resolver = _tmp6_;
#line 116 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					_tmp7_ = resolver;
#line 116 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					_tmp8_ = g_resolver_lookup_by_name (_tmp7_, localaddres, NULL, &_inner_error0_);
#line 116 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					addresses = _tmp8_;
#line 116 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 116 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
						_g_object_unref0 (resolver);
#line 116 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
						_g_object_unref0 (aux);
#line 116 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 116 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
						g_clear_error (&_inner_error0_);
#line 116 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
						return NULL;
#line 1074 "Transport.c"
					}
#line 117 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					_tmp9_ = addresses;
#line 117 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					_tmp10_ = g_list_nth_data (_tmp9_, (guint) 0);
#line 117 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					_tmp11_ = _g_object_ref0 ((GInetAddress*) _tmp10_);
#line 117 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					_g_object_unref0 (aux);
#line 117 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					aux = _tmp11_;
#line 111 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					(addresses == NULL) ? NULL : (addresses = (_g_list_free__g_object_unref0_ (addresses), NULL));
#line 111 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
					_g_object_unref0 (resolver);
#line 1090 "Transport.c"
				}
#line 119 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
				break;
#line 1094 "Transport.c"
			}
		}
	}
#line 121 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	result = aux;
#line 121 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 1102 "Transport.c"
}

gboolean
protocol_bus_transport_get_IsStarted (ProtocolBusTransport* self)
{
	gboolean result;
#line 34 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 34 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	result = self->isStarted;
#line 34 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 1115 "Transport.c"
}

void
protocol_bus_transport_set_IsStarted (ProtocolBusTransport* self,
                                      gboolean value)
{
#line 35 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (self != NULL);
#line 35 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self->isStarted = value;
#line 35 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_object_notify_by_pspec ((GObject *) self, protocol_bus_transport_properties[PROTOCOL_BUS_TRANSPORT_IS_STARTED_PROPERTY]);
#line 1128 "Transport.c"
}

const gchar*
protocol_bus_transport_get_Name (ProtocolBusTransport* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp0_ = self->myName;
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	result = _tmp0_;
#line 39 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	return result;
#line 1144 "Transport.c"
}

void
protocol_bus_transport_set_Name (ProtocolBusTransport* self,
                                 const gchar* value)
{
	gchar* _tmp0_;
#line 40 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (self != NULL);
#line 40 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp0_ = g_strdup (value);
#line 40 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_free0 (self->myName);
#line 40 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self->myName = _tmp0_;
#line 40 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_object_notify_by_pspec ((GObject *) self, protocol_bus_transport_properties[PROTOCOL_BUS_TRANSPORT_NAME_PROPERTY]);
#line 1162 "Transport.c"
}

static void
g_cclosure_user_marshal_BOXED__BOXED (GClosure * closure,
                                      GValue * return_value,
                                      guint n_param_values,
                                      const GValue * param_values,
                                      gpointer invocation_hint,
                                      gpointer marshal_data)
{
	typedef gpointer (*GMarshalFunc_BOXED__BOXED) (gpointer data1, gpointer arg_1, gpointer data2);
	register GMarshalFunc_BOXED__BOXED callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	gpointer v_return;
	cc = (GCClosure *) closure;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (return_value != NULL);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (n_param_values == 2);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		data1 = closure->data;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		data2 = param_values->data[0].v_pointer;
#line 1190 "Transport.c"
	} else {
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		data1 = param_values->data[0].v_pointer;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		data2 = closure->data;
#line 1196 "Transport.c"
	}
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	callback = (GMarshalFunc_BOXED__BOXED) (marshal_data ? marshal_data : cc->callback);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	v_return = callback (data1, g_value_get_boxed (param_values + 1), data2);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_value_take_boxed (return_value, v_return);
#line 1204 "Transport.c"
}

static void
g_cclosure_user_marshal_BOOLEAN__OBJECT (GClosure * closure,
                                         GValue * return_value,
                                         guint n_param_values,
                                         const GValue * param_values,
                                         gpointer invocation_hint,
                                         gpointer marshal_data)
{
	typedef gboolean (*GMarshalFunc_BOOLEAN__OBJECT) (gpointer data1, gpointer arg_1, gpointer data2);
	register GMarshalFunc_BOOLEAN__OBJECT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	gboolean v_return;
	cc = (GCClosure *) closure;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (return_value != NULL);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_return_if_fail (n_param_values == 2);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		data1 = closure->data;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		data2 = param_values->data[0].v_pointer;
#line 1232 "Transport.c"
	} else {
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		data1 = param_values->data[0].v_pointer;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		data2 = closure->data;
#line 1238 "Transport.c"
	}
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	callback = (GMarshalFunc_BOOLEAN__OBJECT) (marshal_data ? marshal_data : cc->callback);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	v_return = callback (data1, g_value_get_object (param_values + 1), data2);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_value_set_boolean (return_value, v_return);
#line 1246 "Transport.c"
}

static void
protocol_bus_transport_class_init (ProtocolBusTransportClass * klass,
                                   gpointer klass_data)
{
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	protocol_bus_transport_parent_class = g_type_class_peek_parent (klass);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	((ProtocolBusTransportClass *) klass)->SendBytes = (gboolean (*) (ProtocolBusTransport*, GBytes*)) protocol_bus_transport_real_SendBytes;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	((ProtocolBusTransportClass *) klass)->MainLoop = (void (*) (ProtocolBusTransport*)) protocol_bus_transport_real_MainLoop;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_protocol_bus_transport_get_property;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_protocol_bus_transport_set_property;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	G_OBJECT_CLASS (klass)->finalize = protocol_bus_transport_finalize;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), PROTOCOL_BUS_TRANSPORT_IS_STARTED_PROPERTY, protocol_bus_transport_properties[PROTOCOL_BUS_TRANSPORT_IS_STARTED_PROPERTY] = g_param_spec_boolean ("IsStarted", "IsStarted", "IsStarted", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), PROTOCOL_BUS_TRANSPORT_NAME_PROPERTY, protocol_bus_transport_properties[PROTOCOL_BUS_TRANSPORT_NAME_PROPERTY] = g_param_spec_string ("Name", "Name", "Name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	protocol_bus_transport_signals[PROTOCOL_BUS_TRANSPORT_ENCRYPT_SIGNAL] = g_signal_new ("encrypt", PROTOCOL_BUS_TYPE_TRANSPORT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_BOXED__BOXED, G_TYPE_BYTES, 1, G_TYPE_BYTES);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	protocol_bus_transport_signals[PROTOCOL_BUS_TRANSPORT_DECRYPT_SIGNAL] = g_signal_new ("decrypt", PROTOCOL_BUS_TYPE_TRANSPORT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_BOXED__BOXED, G_TYPE_BYTES, 1, G_TYPE_BYTES);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	protocol_bus_transport_signals[PROTOCOL_BUS_TRANSPORT_SEND_PCK_TO_XCONNECTED_TRANSPORTS_SIGNAL] = g_signal_new ("send-pck-to-xconnected-transports", PROTOCOL_BUS_TYPE_TRANSPORT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_BOOLEAN__OBJECT, G_TYPE_BOOLEAN, 1, PROTOCOL_BUS_TYPE_PACKET);
#line 1275 "Transport.c"
}

static void
protocol_bus_transport_instance_init (ProtocolBusTransport * self,
                                      gpointer klass)
{
	ProtocolBusAppSync* _tmp0_;
	ProtocolBusAppSync* _tmp1_;
#line 11 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self->isStarted = FALSE;
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp0_ = protocol_bus_app_sync_GetInstance ();
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self->theSync = _tmp1_;
#line 13 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self->ReceiveOwnMessages = FALSE;
#line 1294 "Transport.c"
}

static void
protocol_bus_transport_finalize (GObject * obj)
{
	ProtocolBusTransport * self;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PROTOCOL_BUS_TYPE_TRANSPORT, ProtocolBusTransport);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_object_unref0 (self->myDomain);
#line 9 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_free0 (self->myName);
#line 10 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_thread_unref0 (self->myThread);
#line 12 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	_g_object_unref0 (self->theSync);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	G_OBJECT_CLASS (protocol_bus_transport_parent_class)->finalize (obj);
#line 1313 "Transport.c"
}

static GType
protocol_bus_transport_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ProtocolBusTransportClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) protocol_bus_transport_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ProtocolBusTransport), 0, (GInstanceInitFunc) protocol_bus_transport_instance_init, NULL };
	GType protocol_bus_transport_type_id;
	protocol_bus_transport_type_id = g_type_register_static (PROTOCOL_BUS_TYPE_ILOGGER, "ProtocolBusTransport", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
	return protocol_bus_transport_type_id;
}

GType
protocol_bus_transport_get_type (void)
{
	static volatile gsize protocol_bus_transport_type_id__once = 0;
	if (g_once_init_enter (&protocol_bus_transport_type_id__once)) {
		GType protocol_bus_transport_type_id;
		protocol_bus_transport_type_id = protocol_bus_transport_get_type_once ();
		g_once_init_leave (&protocol_bus_transport_type_id__once, protocol_bus_transport_type_id);
	}
	return protocol_bus_transport_type_id__once;
}

static void
_vala_protocol_bus_transport_get_property (GObject * object,
                                           guint property_id,
                                           GValue * value,
                                           GParamSpec * pspec)
{
	ProtocolBusTransport * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, PROTOCOL_BUS_TYPE_TRANSPORT, ProtocolBusTransport);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	switch (property_id) {
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		case PROTOCOL_BUS_TRANSPORT_IS_STARTED_PROPERTY:
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_value_set_boolean (value, protocol_bus_transport_get_IsStarted (self));
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		break;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		case PROTOCOL_BUS_TRANSPORT_NAME_PROPERTY:
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		g_value_set_string (value, protocol_bus_transport_get_Name (self));
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		break;
#line 1359 "Transport.c"
		default:
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		break;
#line 1365 "Transport.c"
	}
}

static void
_vala_protocol_bus_transport_set_property (GObject * object,
                                           guint property_id,
                                           const GValue * value,
                                           GParamSpec * pspec)
{
	ProtocolBusTransport * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, PROTOCOL_BUS_TYPE_TRANSPORT, ProtocolBusTransport);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
	switch (property_id) {
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		case PROTOCOL_BUS_TRANSPORT_IS_STARTED_PROPERTY:
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		protocol_bus_transport_set_IsStarted (self, g_value_get_boolean (value));
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		break;
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		case PROTOCOL_BUS_TRANSPORT_NAME_PROPERTY:
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		protocol_bus_transport_set_Name (self, g_value_get_string (value));
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		break;
#line 1391 "Transport.c"
		default:
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 7 "/home/chuco/MyProgs/Vala/VK6Bus/src/Transport.vala"
		break;
#line 1397 "Transport.c"
	}
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	if (mem && byte_size != 0) {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		new_mem = g_malloc (byte_size);
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		memcpy (new_mem, mem, byte_size);
#line 1412 "Transport.c"
	} else {
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
		new_mem = NULL;
#line 1416 "Transport.c"
	}
#line 8 "/home/chuco/MyProgs/Vala/VK6Bus/src/GenericsPubSub.vala"
	return new_mem;
#line 1420 "Transport.c"
}

